### ISSUE TITLE
Make library available as PCL, profile 111

### ISSUE THREAD

**Issue by fubar-coder** [GregFinzer/Compare-Net-Objects#1]
This would allow the usage in a .NET Core, Xamarin Mac, iOS, and Android project.

The target would be portable-net45+netcore45+wpa81

EDIT: Updated PCL identifier

**Comment by GregFinzer** [comment]
@fubar-coder It already has a portable class library version in the solution.

**Comment by fubar-coder** [comment]
Please reopen this issue, because it's not fixed. Yes, there is a PCL version, but it's for an inferior PCL profile (136 vs 111).

**Comment by GregFinzer** [comment]
Ok

**Comment by steviehailey** [comment]
Hey,
I wanted to try out Compare .Net Objects on Linux using .net Core and managed to get a new-style PCL building a nuget package which works.
I have raised a PR with the relevant changes: https://github.com/GregFinzer/Compare-Net-Objects/pull/8
Hopefully this can also solve you use case @fubar-coder 
Cheers,
Stevie

**Comment by GregFinzer** [comment]
New .NET Core Version is Up with latest version
