### ISSUE TITLE
Another Possible IgnoreCollectionOrder issue 

### ISSUE THREAD

**Issue by dgranov** [GregFinzer/Compare-Net-Objects#10]
Hi team,

First of all thank you for the great library, it helps a lot.
Could you please verify why the library finds two sets of objects different while i am expecting they are equal. Could it be a bug or misconfiguration on my side?
`

        public class TestContent
        {
            public string Title { get; set; }
            public IList<TestLocalisation> Localisations { get; set; }
        }
        public class TestLocalisation
        {
            public TestLanguage Language { get; set; }
            // here might be another List<> which should also ignore order
        }
        public class TestLanguage
        {
            public string Code { get; set; }
        }

        var expected = new List<TestContent>
        {
            new TestContent
            {
                Title = "1", 
                Localisations = new List<TestLocalisation>
                {
                    new TestLocalisation
                    {
                        Language = new TestLanguage {Code = "en"}
                    }, 
                    new TestLocalisation
                    {
                        Language = new TestLanguage {Code = "de"}
                    }
                }
            }
        };

        var actual = new List<TestContent>
        {
            new TestContent
            {
                Title = "1", 
                Localisations = new List<TestLocalisation>
                {
                    new TestLocalisation
                    {
                        Language = new TestLanguage {Code = "de"}
                    }, 
                    new TestLocalisation
                    {
                        Language = new TestLanguage {Code = "en"}
                    }
                }
            }
        };

        var config = new ComparisonConfig
        {
            CompareFields = false,
            ComparePrivateFields = false,
            CompareStaticFields = false,
            CompareStaticProperties = false,
            MaxStructDepth = 100,
            IgnoreCollectionOrder = true
        };
        var comparer = new CompareLogic(config);
        var comparisonResult = comparer.Compare(expected, actual);
`
The library returns the following:
Begin Differences (1 differences):
Types [String,String], Item Expected[Title:1].Localisations[Language:TestLanguage].Language.Code != Actual[Title:1].Localisations[Language:TestLanguage].Language.Code, Values (en,de)
End Differences (Maximum of 1 differences shown).

Tried configuring CollectionMatchingSpec but with no luck.

Thanks in advance

**Comment by GregFinzer** [comment]
dgranov,

You are not going to be able to do a collection matching spec unless you have some sort of id in the TestLanguage.

Thanks,
Greg
