### ISSUE TITLE
Comparing nested objects

### ISSUE THREAD

**Issue by alxtr1bal** [GregFinzer/Compare-Net-Objects#105]
I have classes like this : 
class Product {
   long Id {get; set;}
   string Label{get; set;}; 
}
class Offer {
   long Id {get; set;}
   string Label {get; set;}; 

   List<Product> Products {get; set;}; 
}
class Booking {
       List<Offer> Offers {get; set;}; 
}

So i Have 2 objects of Type Booking that i want to compare.
bookingOld
bookingNew

For testing, at start, my 2 objects are identicals (clones)

If i modify bookingOld, changing  the label of an Offer, i have a difference.
if i modify bookingOld, changing product label inside Offfer, i have a difference.

BUT 
If i modify the label of an offer, and i modify the product label inside the offer, i have only a difference for the offer, but not the product !

What am i doing wrong ?

**Comment by alxtr1bal** [comment]
Forgot to say i was comparing bookingOld with bookingNew :)

//TESTING
bookingNew.Offers[0].Label = "Popol";
bookingNew.Offers[0].Products[1].Label = "Tutu";
bookingOld.Offers[0].Products[4].Label = "Lollipop";

var res = logic.Compare(bookingOld, bookingNew);

Only difference for the Offer object, not the Products inside

**Comment by GregFinzer** [comment]
Please read the manual:  
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Getting-Started

**Comment by GregFinzer** [comment]
Please provide a failing NUnit test.  The code that you have provided above is not enough to go on.

**Comment by alxtr1bal** [comment]
```csharp
    [TestFixture]
    public class Tests
    {
        [Test]
        public void TestCompare()
        {
            //Arrange
            var bookingOld = new Booking();
            bookingOld.Offers.Add(new Offer
            {
                Id = 1,
                Label = "Offer 1",
                Order = 1
            });
            bookingOld.Offers[0].Products.Add(new BookingProduct
            {
                Id = 1,
                ProductId =  1,
                OfferId = 1,
                Label =  "Product 1",
                Amount = 10
            });
            bookingOld.Offers[0].Products.Add(new BookingProduct
            {
                Id = 2,
                ProductId =  2,
                OfferId = 1,
                Label =  "Product 2",
                Amount = 15
            });

            var bookingNew = new Booking();
            bookingNew.Offers.Add(new Offer
            {
                Id = 1,
                Label = "Change Label",
                Order = 1
            });
            bookingNew.Offers[0].Products.Add(new BookingProduct
            {
                Id = 1,
                ProductId =  1,
                OfferId = 1,
                Label =  "Product 1",
                Amount = 10
            });
            bookingNew.Offers[0].Products.Add(new BookingProduct
            {
                Id = 2,
                ProductId =  3,
                OfferId = 1,
                Label =  "Product 2 New",
                Amount = 15
            });


            //Act
            var config = new ComparisonConfig {MaxDifferences = 100, IgnoreCollectionOrder = true};
            var logic = new CompareLogic(config);
            var res = logic.Compare(bookingOld, bookingNew);

            //Assert
            Assert.False(res.AreEqual);
        }
```

Here, i can see the Offer has been modified (label changed), that's OK. But i 'm not seeing the differences for the products (i changed the product nb 2)

**Comment by GregFinzer** [comment]
You need to specify a collection matching spec for each class type if you are ignoring the order.
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths

**Comment by GregFinzer** [comment]
FYI, without the ignore order, I am getting these differences from your test:

Begin Differences (3 differences):
Types [String,String], Item Expected.Offers[0].Label != Actual.Offers[0].Label, Values (Offer 1,Change Label)
Types [String,String], Item Expected.Offers[0].Products[1].Label != Actual.Offers[0].Products[1].Label, Values (Product 2,Product 2 New)
Types [Int32,Int32], Item Expected.Offers[0].Products[1].ProductId != Actual.Offers[0].Products[1].ProductId, Values (2,3)
End Differences (Maximum of 100 differences shown).

**Comment by alxtr1bal** [comment]
Ok , but i need the ignore order as well.
Yes, i did something like
```csharp
var spec = new Dictionary<Type, IEnumerable<string>>
{
      {typeof(List<Offer>), new[] {"Id"}},
      {typeof(List<Product>), new[] {"Id"}},
}
var config = new ComparisonConfig {MaxDifferences = 100, IgnoreCollectionOrder = true, CollectionMatchingSpec = spec};
```
What i don't understand is why do i get the differences about Products if i don't modify the Offer ?

### Without modifying the offer : 
Begin Differences (2 differences):
Types [Product,null], Item Expected.Offers ...].Products[...]
Types [null,Product], Item Expected.Offers...].Products[...]
End Differences (Maximum of 100 differences shown).

### Modifying the offer and the product : 
Begin Differences (2 differences):
Types [Offer,null], Item Expected.Offers[Id:1,Order:1,...].Item, Values (Offer,(null))
Types [null,Offer], Item Expected.Offers[Id:1,Order:1,...].Item, Values ((null), Offer)
End Differences (Maximum of 100 differences shown).

Then i tried : 
var spec = new Dictionary<Type, IEnumerable<string>>
{
      {typeof(Offer), new[] {"Id"}},
      {typeof(Product), new[] {"Id"}},
      {typeof(List<Offer>), new[] {"Id"}},
      {typeof(List<Product>), new[] {"Id"}},
}
But now the differences are about the class members that i changed, but not about the class itself, as before.


Begin Differences (3 differences):
Types [String,String], Item Expected.Offers[Id:1].Label != Actual.Offers[Id:1].Label, Values (Offer 1,ChangeLabel)
Types [Int64,Int64], Item Expected.Offers[Id:1].Products[Id:2].ProductId != Actual.Offers[Id:1].Products[Id:2].ProductId, Values (2,3)
Types [String,String], Item Expected.Offers[Id:1].Products[Id:2].Label != Actual.Offers[Id:1].Products[Id:2].Label, Values (Product 2,Change Label)
End Differences (Maximum of 100 differences shown).

I'm confused :-)

**Comment by GregFinzer** [comment]
I am swamped at work.  It will be a while until I can respond.  You might want to step through the Compare Logic code to see what it is doing.

**Comment by GregFinzer** [comment]
Can you try this?

var spec = new Dictionary<Type, IEnumerable<string>>
{
      {typeof(Offer), new[] {"Id"}},
      {typeof(Product), new[] {"Id"}},
}
var config = new ComparisonConfig {MaxDifferences = 100, IgnoreCollectionOrder = true, CollectionMatchingSpec = spec};

**Comment by GregFinzer** [comment]
This is working as expected.  See the IgnoreOrderTests.NestedObjectShouldCompare

Please also do a get latest of the source which now throws exceptions for Invalid Collection Matching Specs
