### ISSUE TITLE
Add netstandard2.0 target

### ISSUE THREAD

**Issue by ltrzesniewski** [GregFinzer/Compare-Net-Objects#107]
Hi,

Could you add a netstandard2.0 target to the NuGet please?

Using the netstandard1.3 version forces me to add an explicit reference to `System.Reflection.TypeExtensions` and a binding redirect, as the netstandard1.3 version uses an older (incompatible) version.

netstandard1.3 is considered legacy anyway.

**Comment by ltrzesniewski** [comment]
PS: this *may* be related to #102

**Comment by GregFinzer** [comment]
It will be a while until I can get to this.  I am drowning in work.

**Comment by ltrzesniewski** [comment]
OK, turns out what I *really* need here is a netstandard2.0 target which does *not* reference `System.Reflection.TypeExtensions` at all.

I made a PR => #108
