### ISSUE TITLE
Singe Array Element mismatch creates two messages.

### ISSUE THREAD

**Issue by aspnetlabs** [GregFinzer/Compare-Net-Objects#109]
var p = new Phone[]
                {
                    new Phone()
                    {
                        Moblie = "4444", Home = "555"
                    }, 
                }

var p1 =  new Phone[]
                {
                    new Phone()
                    {
                        Moblie = "4444", Home = "*555"
                    }, 
                }

It creates 2 messages for one mismatch.

Types [Phone,null], Item Expected.Phones[Moblie:4444,Home:555].Item != Actual.Phones[Moblie:4444,Home:555].Item, Values (ConsoleApp4.Phone,(null))

Types [null,Phone], Item Expected.Phones[Moblie:4444,Home:*555].Item != Actual.Phones[Moblie:4444,Home:*555].Item, Values ((null),ConsoleApp4.Phone)

**Comment by aspnetlabs** [comment]
namespace ClassLibreary1
{
    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DOB { get; set; }
        public Phone[] Phones { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }

    }

    public class Phone
    {
        public int Id { get; set; }
        public string Moblie { get; set; }
        public string Home { get; set; }
    }

    public class Program
    {
        public static void Compare()
        {
            
            ComparisonConfig config = new ComparisonConfig()
            {
                MaxDifferences = 1000,
                IgnoreCollectionOrder = true,
                CaseSensitive = false 
            }; 
            var _compare = new CompareLogic(config);

            Person p = new Person()
            {
                Phones = new Phone[]
                {
                    new Phone()
                    {
                      Id=1,  Moblie = "4444", Home = "555"
                    },
                }, 
            };
            Person p2 = new Person()
            {
                Phones = new Phone[]
               {
                      new Phone()
                    {
                       Id=1, Moblie = "4444", Home = "*555"
                    },
               }, 
            }; 
            var result = _compare.Compare(p, p2);
            var t = result.Differences.Select(x => new { k = x.ToString() }); 
        } 
    }
}

**Comment by GregFinzer** [comment]
Please add a Collection Matching Spec for Phone for the Id:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths
