### ISSUE TITLE
ComparisonResult visibility changes requested

### ISSUE THREAD

**Issue by jvdonk** [GregFinzer/Compare-Net-Objects#11]
Hi,

Please make the AddParent and RemoveParent methods more visible(currently: internal) so that one can implement a custom ListComparer.

Thank you, awesome package!

**Comment by GregFinzer** [comment]
Done.  Now protected internal.

**Comment by jvdonk** [comment]
Oh, crap. I missed the ExcludeLogic class.

This one is also internal.

Any clue when these changes will be release into a new nuget release?

Thank you.

**Comment by GregFinzer** [comment]
jvdonk,

It will be several months before I can do a build.  My day job is crazy right now and I am behind on everything else.

Sorry.

Greg

**Comment by jvdonk** [comment]
No, problem. I already mitigated the problem for now (use the source like ;))

Ever looked @ TeamCity/Octopus Deploy? Free for small teams/projects and amazing @ saving time. :) 

Cheers!

**Comment by GregFinzer** [comment]
Unfortunately team city and octopus do not help with painting the steps, doing the bathroom grout, and other household chores.  :)

**Comment by jvdonk** [comment]
Well, with a stunning CI pipeline one saves time to do more projects, make more money and hire people to do these for you. In this saved time one can do even more projects and make even more money to buy a new house in which one doesn't have to paint the steps for a few years which saves even more...

But no, not really ;)

**Comment by GregFinzer** [comment]
ExcludeLogic is now public

**Comment by jvdonk** [comment]
Awesome, waiting for the new release on nuget so I can drop a fork.

**Comment by GregFinzer** [comment]
Done:
https://www.nuget.org/packages/CompareNETObjects/
