### ISSUE TITLE
Xml documentation and DifferencesString are different

### ISSUE THREAD

**Issue by bhavishyachandra** [GregFinzer/Compare-Net-Objects#112]
Hello

https://github.com/GregFinzer/Compare-Net-Objects/blob/a254647508ccbb8bc2044f5097c70243f7d842f1/Compare-NET-Objects/ICompareLogic.cs#L20

The DifferencesString refers to the objects as Expected and Actual. Can we update the xml documentation to match it?

Thanks

**Comment by GregFinzer** [comment]
It will take me a while until I can get to this.  I am recovering from an injury.

**Comment by GregFinzer** [comment]
Fixed.
