### ISSUE TITLE
option for case-insensitive member match

### ISSUE THREAD

**Issue by DmitryBryluk** [GregFinzer/Compare-Net-Objects#115]
is there some option for case-insensitive member name match?

also custom property matcher and/or regex pairs to match property names will be nice

**Comment by GregFinzer** [comment]
Please see the documentation:

https://github.com/GregFinzer/Compare-Net-Objects/wiki/String-Options

https://github.com/GregFinzer/Compare-Net-Objects/wiki/Ignoring-Members

**Comment by DmitryBryluk** [comment]
I mean member name match, i.e. Class1.ID match with Class2.id
also regex pairs: [/id/i, /(primary_?)?id/i] will match Class1.{id|ID|Id|...} to Class2.{id|ID|Id|PrimaryId|primary_id|...}

**Comment by GregFinzer** [comment]
@DmitryBryluk I understand.  No it does not have that functionality.
