### ISSUE TITLE
Support DateTime when Kind is specified

### ISSUE THREAD

**Issue by tatejones** [GregFinzer/Compare-Net-Objects#116]
Hi,

I understand that the DateTime type does not take into account Kind (zones).  Compares the ticks only.
Converting the DateTime to DateTimeOffset the compare passes.
compareLogic.Compare(new DateTimeOffset(dateTimeUtcNow), new DateTimeOffset(dateTimeNow)).AreEqual.Should().BeTrue();

        [Fact]
        public void TestUtcvsLocalDates()
        {
            var dateTimeUtcNow = DateTime.UtcNow;
            var dateTimeNow = dateTimeUtcNow.ToLocalTime();
            CompareLogic compareLogic = new CompareLogic();
            // fails
            compareLogic.Compare(dateTimeNow, dateTimeUtcNow).AreEqual.Should().BeTrue(); 
        }

Do you think this library should support the config to allow DateTime types to be compare when in different timezones or should I write my own custom comparer?

**Comment by GregFinzer** [comment]
I think the config option sounds good.  Please implement and I will be happy to merge in the pull request.

**Comment by GregFinzer** [comment]
Fantastic.  Thanks so much.  I will do a deployment over the weekend.

**Comment by GregFinzer** [comment]
Pushed to NuGet
