### ISSUE TITLE
CompareType in custom comparer not parsing

### ISSUE THREAD

**Issue by tdzwakhals** [GregFinzer/Compare-Net-Objects#118]
I am working on a custom comparer, but the compiler keeps telling me
`'DataAssetComparer' does not implement inherited abstract member 'BaseTypeComparer.CompareType(CompareParms)'`

in 

```
public class DataAssetComparer : BaseTypeComparer
    {
        public DataAssetComparer(RootComparer rootComparer) : base(rootComparer) { }

        public override bool IsTypeMatch(Type type1, Type type2)
        {
            return type1 == typeof(DataAsset);
        }

        public override void CompareType(ComparisonResult result, object object1, object object2, string breadCrumb)
        {
            var st1 = (DataAsset)object1;
            var st2 = (DataAsset)object2;

            if (st1.value != st2.value || st1.amount != st2.amount)
            {
                Difference difference = new Difference
                {
                    PropertyName = breadCrumb,
                    Object1Value = object1.ToString(),
                    Object2Value = object2.ToString()
                };

                result.Differences.Add(difference);
            }
        }
    }
```

How can I solve this problem?

**Comment by GregFinzer** [comment]
Take a look at this example:

using System;

namespace KellermanSoftware.CompareNetObjects.TypeComparers
{
    /// <summary>
    /// Logic to compare to enum values
    /// </summary>
    public class EnumComparer : BaseTypeComparer
    {
        /// <summary>
        /// Constructor with a default root comparer
        /// </summary>
        /// <param name="rootComparer"></param>
        public EnumComparer(RootComparer rootComparer) : base(rootComparer)
        {
        }

        /// <summary>
        /// Returns true if both objects are of type enum
        /// </summary>
        /// <param name="type1">The type of the first object</param>
        /// <param name="type2">The type of the second object</param>
        /// <returns></returns>
        public override bool IsTypeMatch(Type type1, Type type2)
        {
            return TypeHelper.IsEnum(type1) && TypeHelper.IsEnum(type2);
        }

        /// <summary>
        /// Compare two enums
        /// </summary>
        public override void CompareType(CompareParms parms)
        {
            if (parms.Object1.ToString() != parms.Object2.ToString())
            {
                AddDifference(parms);
            }
        }
    }
}
