### ISSUE TITLE
Order-independent collection comparison relies on ToString output

### ISSUE THREAD

**Issue by jamezor** [GregFinzer/Compare-Net-Objects#125]
If you are comparing two collections with `IgnoreCollectionOrder` set to true, then the `ToString` value of the instances in the collection seems to be relied upon during the comparison. This is not great, since there are no guarantees around the output of `ToString` and in our case we output data which is not part of the 'identity' of the instances.

See failing test here: b5c83f0b5e63ba61883b36dfbb0f7002b0c09504

**Comment by GregFinzer** [comment]
@jamezor You will need to define a collection matching spec.  Please see the wiki:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths
