### ISSUE TITLE
MembersToInclude

### ISSUE THREAD

**Issue by cico88** [GregFinzer/Compare-Net-Objects#127]
public class Person
    {
        public DateTime DateCreated { get; set; }
        public string Name { get; set; }
        public Category Category { get; set; }
    }

    public class Category
    {
        public string Title { get; set; }
    }

            // Works
            CompareLogic compareLogic = new CompareLogic();
            // Works
            CompareLogic compareLogic = new CompareLogic(new ComparisonConfig { MembersToIgnore = new List<string> { "Category.Title" } });
            // DOES NOT WORK (am I missing something?)
            CompareLogic compareLogic = new CompareLogic(new ComparisonConfig { MembersToInclude = new List<string> { "Category.Title" } });

            //Create a couple objects to compare
            Person person1 = new Person();
            person1.DateCreated = DateTime.Now;
            person1.Name = "Greg";
            person1.Category = new Category { Title = "A" };

            Person person2 = new Person();
            person2.Name = "Greg";
            person2.DateCreated = person1.DateCreated;
            person2.Category = new Category { Title = "B" };

**Comment by GregFinzer** [comment]
Once you start adding MembersToInclude then you have to define everything you want included.  You are missing the Person class

**Comment by cico88** [comment]
I have to miss something.

            //Create a couple objects to compare
            Person person1 = new Person();
            person1.DateCreated = DateTime.Now;
            person1.Name = "Greg";
            person1.Category = new Category { Title = "A" };

            Person person2 = new Person();
            person2.Name = "Greg";
            person2.DateCreated = person1.DateCreated;
            person2.Category = new Category { Title = "B" };

            // RESULT: Category Title: A CHANGED TO -> B
            //CompareLogic compareLogic = new CompareLogic();

            // RESULT: No difference, fine this is expected
            //CompareLogic compareLogic = new CompareLogic(new ComparisonConfig { MembersToIgnore = new List<string> { "Category.Title" } });

            // RESULT: No difference, I expected "Category Title: A CHANGED TO -> B" (same member is ignored above, but not included here)
            CompareLogic compareLogic = new CompareLogic(new ComparisonConfig { MembersToInclude = new List<string> { "Category.Title" } });

            ComparisonResult result = compareLogic.Compare(person1, person2);

            UserFriendlyReport friendlyReport = new UserFriendlyReport();
            Console.WriteLine(friendlyReport.OutputString(result.Differences));

**Comment by GregFinzer** [comment]
Once you start adding MembersToInclude then you have to define everything you want included. You are missing the Person class
