### ISSUE TITLE
Access to wiki and documentation suggestion

### ISSUE THREAD

**Issue by MNF** [GregFinzer/Compare-Net-Objects#13]
I wanted to add an example with config to wiki, but it is not enabled for editing. Is it intentional?

Could you please add to Getting Started documentation an example of using ComparisonConfig?
It also will be good to have full help on searchable github site.

Please also add a link to  [CodeProject Tutorial ](http://www.codeproject.com/Tips/754435/Compare-NET-Objects-Tutorial)

**Comment by GregFinzer** [comment]
MNF,

While I appreciate your suggestions, I prefer the CHM file which is included with the source code.  The CHM file has a config example.  The CodeProject tutorial is dated and uses a previous version which is obsolete.  I am still unsure if I am going to stick with GitHub.  GitHub might be a fad like CodePlex which is where I hosted before.  

Greg
