### ISSUE TITLE
Feature request: please provide a way to set the Date/Time format to be used in the reports

### ISSUE THREAD

**Issue by costabas** [GregFinzer/Compare-Net-Objects#131]
Hi,

Unless there isn't another way to do it, can you please provide a way via some (configuration) properties to set the Date/Time format to be used in the reports?

In my case I wanted the UserReport to display the dates in the format dd-MMM-yyyy. Because of this I have to write my own report. 

Thanks!

**Comment by GregFinzer** [comment]
Sounds like a good feature.  Please implement and I will merge in the pull request.

Thanks,
Greg
