### ISSUE TITLE
Compare properties based on attributes

### ISSUE THREAD

**Issue by biju-ps** [GregFinzer/Compare-Net-Objects#133]
Hi 
Is there any method to compare object based on property attributes. 
For example : 
```
public class Person {
    [AuditTrailEnabled]
    public String Name {get;set;}
    public DateTime DOB {get;set;}
    [AuditTrailEnabled]
    public String Sex  {get;set;}
    public String Address {get;set;}

}

``` 
in the above class, only properties with [AuditTrailEnabled] attributes should compare . 
Any luck ?

**Comment by GregFinzer** [comment]
Sorry no, there is only IgnoreMembers:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Ignoring-Members

Thanks,
Greg
