### ISSUE TITLE
Report OutputStream does not flush streamwriter

### ISSUE THREAD

**Issue by istrupin** [GregFinzer/Compare-Net-Objects#137]
Hello,

I think I may have found a small bug in the `CsvReport.OutputStream` method.  

A flush is never forced on the writer, so there is potential to miss some data when writing to the stream.  A call to `Close` or a using statement (similar to `CsvReport.OutputFile`) would likely resolve the issue.

I would be more than happy to send you a PR with a proposed fix if you'd like.

**Comment by GregFinzer** [comment]
Fixed
