### ISSUE TITLE
Compare Error

### ISSUE THREAD

**Issue by ramuambati** [GregFinzer/Compare-Net-Objects#138]
Can someone tell why it is different if the dates are matching exactly? Thanks

Begin Differences (1 differences):
Types [DateTime,DateTime], Item Expected[1].Names[2].OrgNmBeginDt != Actual[1].Names[2].OrgNmBeginDt, Values (7/17/2010 8:39:02 AM,7/17/2010 8:39:02 AM)
End Differences (Maximum of 1 differences shown).

**Comment by GregFinzer** [comment]
There is a difference in milliseconds.  You can ignore millisecond differences.  See this link.
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Date-Options

**Comment by ramuambati** [comment]
> There is a difference in milliseconds. You can ignore millisecond differences. See this link.
> https://github.com/GregFinzer/Compare-Net-Objects/wiki/Date-Options

I still see same issue. I am getting data from same data source and there is no way time is different. I added the property as you suggested but same error.

**Comment by ramuambati** [comment]
I tried all these and even I ignored but no luck

            compareLogic.Config.TreatStringEmptyAndNullTheSame = true;
            compareLogic.Config.CompareDateTimeOffsetWithOffsets = false;
            compareLogic.Config.CaseSensitive = false;
            compareLogic.Config.ComparePrivateProperties = false;
            compareLogic.Config.AttributesToIgnore.Add(dsf.OrgNmBeginDt.GetType());

**Comment by GregFinzer** [comment]
I would try this:
compare.Config.MaxMillisecondsDateDifference = 999;

**Comment by GregFinzer** [comment]
If that does not work you will need to debug Compare .NET Objects to see what is going wrong.

**Comment by ramuambati** [comment]
> I would try this:
> compare.Config.MaxMillisecondsDateDifference = 999;

This works for me now. Thank you GregFinzer!

**Comment by ramuambati** [comment]
Closing issue. Works now with the latest recommendation.
