### ISSUE TITLE
CHM is empty for me

### ISSUE THREAD

**Issue by ToXinE** [GregFinzer/Compare-Net-Objects#14]
![image](https://cloud.githubusercontent.com/assets/6205053/16773224/5dd912de-4857-11e6-843c-6ba127a56d81.png)

seems like every section is empty for me :'(

Running on windows 10 x64

**Comment by GregFinzer** [comment]
You will need to unblock it.

http://www.jeff.wilcox.name/2008/11/unblock-chms/

**Comment by ToXinE** [comment]
thank you !
