### ISSUE TITLE
IgnoreStringLeadingTrailingWhitespace Missing From ComparisonConfig

### ISSUE THREAD

**Issue by willpowr** [GregFinzer/Compare-Net-Objects#141]
I'm currently using version 4.57.0.0. Despite being mentioned in search results https://github.com/GregFinzer/Compare-Net-Objects/search?q=IgnoreStringLeadingTrailingWhitespace&unscoped_q=IgnoreStringLeadingTrailingWhitespace

**Comment by GregFinzer** [comment]
It has been a while since the last release.  4.57 was released on October 11, 2018.  The IgnoreStringLeadingTrailingWhitespace was put in December 2018

**Comment by GregFinzer** [comment]
Released 4.5.8 
https://www.nuget.org/packages/CompareNETObjects/4.58.0

**Comment by willpowr** [comment]
Fast work. I'll check it out tomorrow. Cheers.
