### ISSUE TITLE
BeyondCompareReport is not include

### ISSUE THREAD

**Issue by seanmars** [GregFinzer/Compare-Net-Objects#142]
I'm using version 4.58.0, but there is no BeyondCompareReport. Am I missing something?

**Comment by GregFinzer** [comment]
@seanmars It is only included in the .NET Framework Version, not in the .NET Standard Version.  .NET Standard can be run in environments where Beyond Compare does not exist.  Example, an Android Phone.

**Comment by seanmars** [comment]
> @seanmars It is only included in the .NET Framework Version, not in the .NET Standard Version. .NET Standard can be run in environments where Beyond Compare does not exist. Example, an Android Phone.

Ok, I see, but I think you can use the detection platform to let it work on Windows/macOS with .NET Standard?

**Comment by GregFinzer** [comment]
How would I do that?  Specifically I am detecting the location of Beyond compare in the registry and then using shell to run Beyond Compare.

How would I do something similar for MacOS and Linux?

**Comment by seanmars** [comment]
[Using BComp instead of Beyond Compare.app for VCS and OSX Command Line Utilities](https://www.scootersoftware.com/vbulletin/forum/beyond-compare-4-discussion/mac/9359-using-bcomp-instead-of-beyond-compare-app-for-vcs-and-osx-command-line-utilities)

Maybe this is a way to do that.

**Comment by GregFinzer** [comment]
I may just end up detecting windows and only running it for that.

**Comment by GregFinzer** [comment]
Implemented
