### ISSUE TITLE
Custom Compare + Expando = Ignored Ignores

### ISSUE THREAD

**Issue by Ali-Al1** [GregFinzer/Compare-Net-Objects#143]
Hello,

I wrote a custom compare class (that checks if the string is actually a float)

so things like "1" and "1.000000" won't show up as a difference

but when using said custom compare class, my MembersToIgnore list is not longer being respected

`        [Test]
        public void test()
        {
            abc a = new abc()
            {
                ex = JsonConvert.DeserializeObject<ExpandoObject>("{\"test\": \"1\"}")
            };

            abc b = new abc()
            {
                ex = new ExpandoObject()
            };

            CompareLogic compareLogic = new CompareLogic();
            compareLogic.Config.MembersToIgnore.Add("*test*");
            compareLogic.Config.MembersToIgnore.Add("*ex.test*");
            compareLogic.Config.MembersToIgnore.Add("*.ex.test*");
            compareLogic.Config.MembersToIgnore.Add("*abc.ex.test*");
            compareLogic.Config.MembersToIgnore.Add("*.abc.ex.test*");
            compareLogic.Config.MembersToIgnore.Add("test*");
            compareLogic.Config.MembersToIgnore.Add("ex.test*");
            compareLogic.Config.MembersToIgnore.Add(".ex.test*");
            compareLogic.Config.MembersToIgnore.Add("abc.ex.test*");
            compareLogic.Config.MembersToIgnore.Add(".abc.ex.test*");
            compareLogic.Config.MembersToIgnore.Add("*test");
            compareLogic.Config.MembersToIgnore.Add("*ex.test");
            compareLogic.Config.MembersToIgnore.Add("*.ex.test");
            compareLogic.Config.MembersToIgnore.Add("*abc.ex.test");
            compareLogic.Config.MembersToIgnore.Add("*.abc.ex.test");
            compareLogic.Config.MembersToIgnore.Add("test");
            compareLogic.Config.MembersToIgnore.Add("ex.test");
            compareLogic.Config.MembersToIgnore.Add(".ex.test");
            compareLogic.Config.MembersToIgnore.Add("abc.ex.test");
            compareLogic.Config.MembersToIgnore.Add(".abc.ex.test");
            compareLogic.Config.CustomComparers.Add(new StringMightBeFloat(RootComparerFactory.GetRootComparer()));
            compareLogic.Config.MaxDifferences = 50;

            ComparisonResult result = compareLogic.Compare(a, b);
        }

        public class abc
        {
            public ExpandoObject ex;
        }
        public class StringMightBeFloat : BaseTypeComparer
        {
            public StringMightBeFloat(RootComparer rootComparer) : base(rootComparer)
            {
            }

            public override bool IsTypeMatch(Type type1, Type type2)
            {
                return type1 == typeof(string) && type2 == typeof(string);
            }

            public override void CompareType(CompareParms parms)
            {
                {

                    var st1 = (string)parms.Object1;
                    var st2 = (string)parms.Object2;

                    if (st1.Equals(st2))
                    {
                        return;
                    }

                    float flt1;
                    float flt2;

                    if (float.TryParse(st1, out flt1) && float.TryParse(st2, out flt2))
                    {
                        if (flt1.Equals(flt2))
                        {
                            return;
                        }
                    }

                    AddDifference(parms);
                }
            }
        }`

**Comment by GregFinzer** [comment]
Thanks for reporting this issue.

**Comment by GregFinzer** [comment]
@Ali-Al1 I was looking at this today.  I am unable to get the test above to compile.  Specifically it is not compiling this line:
ex = JsonConvert.DeserializeObject("{"test": "1"}")

Cannot convert source type object to System.Dynamic.ExpandoObject

**Comment by Ali-Al1** [comment]
Are you in a .net 4.5 project?

**Comment by GregFinzer** [comment]
The test project is 4.6.1

**Comment by GregFinzer** [comment]
Can you create a pull request that has everything that is needed for this test to compile?

**Comment by GregFinzer** [comment]
I haven't heard anything back.  Closing issue.

**Comment by GregFinzer** [comment]
@Ali-Al1 Thanks so much for providing the failing test.  It will be a while until I can get to this.

**Comment by Ali-Al1** [comment]
@GregFinzer No problem, sorry for the late reply.

**Comment by GregFinzer** [comment]
@Ali-Al1 I had a couple minutes today in between tasks.  This test is running and passing.  Is this what you were needing?

        [Test]
        public void ExpandoObject()
        {
            DynamicContainer a = new DynamicContainer()
            {
                expando = JsonConvert.DeserializeObject<ExpandoObject>("{\"test\": \"1\"}")
            };

            DynamicContainer b = new DynamicContainer()
            {
                expando = new ExpandoObject()
            };

            CompareLogic compareLogic = new CompareLogic();
            compareLogic.Config.MembersToIgnore.Add("expando");
            compareLogic.Config.CustomComparers.Add(new StringMightBeFloat(RootComparerFactory.GetRootComparer()));
            compareLogic.Config.MaxDifferences = 50;

            ComparisonResult result = compareLogic.Compare(a, b);

            Console.WriteLine(result.DifferencesString);
            Assert.IsTrue(result.AreEqual);
        }

**Comment by GregFinzer** [comment]
Fixed in this commit.  See your test inside.

https://github.com/GregFinzer/Compare-Net-Objects/commit/d75847b3b7e59dcf49d98104627aede635bff075

**Comment by GregFinzer** [comment]
Closing after the fix
