### ISSUE TITLE
ComparisonConfig.CompareDateTimeOffsetWithOffsets meaning should be inverted

### ISSUE THREAD

**Issue by lezhnevitransition** [GregFinzer/Compare-Net-Objects#145]
Looks that the ComparisonConfig.CompareDateTimeOffsetWithOffsets does not work as expected. 
Source DateTimeOffsetComparer.cs: 
`date1 = new DateTimeOffset(date1.DateTime, TimeSpan.Zero);
            date2 = new DateTimeOffset(date2.DateTime, TimeSpan.Zero);
            if (Math.Abs((date1 - date2).TotalMilliseconds) > parms.Config.MaxMillisecondsDateDifference)
            {
                AddDifference(parms);
            }
            else if (parms.Config.CompareDateTimeOffsetWithOffsets && date1.Offset != date2.Offset)
            {
                AddDifference(parms);
            }`
My unit test:
[Test]
        public void CompareDateTimeOffsetIgnore()
        {
            DateTime now = DateTime.Now;
            DateTimeOffset date1 = new DateTimeOffset(
                now.Year, now.Month, now.Day, now.Hour, now.Minute, now.Second, new TimeSpan(0, 0, 0));
            DateTimeOffset date2 = new DateTimeOffset(
                now.Year, now.Month, now.Day, now.Hour, now.Minute, now.Second, new TimeSpan(3, 0 , 0));
            
            _compare.Config.CompareDateTimeOffsetWithOffsets = false;
            ComparisonResult result = _compare.Compare(date1, date2);

            if (!result.AreEqual)
                throw new Exception(result.DifferencesString);
        }

**Comment by GregFinzer** [comment]
Thank you for reporting the issue.  It was not working.  Fixed.  See these tests:

When_CompareDateTimeOffsetWithOffsets_Is_False_Do_Not_Compare_Offsets

When_CompareDateTimeOffsetWithOffsets_Is_True_Compare_Offsets

**Comment by lezhnevitransition** [comment]
Looks good for me, thank you for this fix.
