### ISSUE TITLE
When used for a few hours, the cpu reaches 90%

### ISSUE THREAD

**Issue by pyengwoei** [GregFinzer/Compare-Net-Objects#147]
This is the main code
List<T> Alist, List<T> Blist;
for (int i = 0; i < Blist.Count; i++)
{
   if (Alist.Exists(x => x.name == new[i].name{
        var locold = Alist.Find(x => x.name == Blist[i].name);
 CompareLogic compareLogic = new CompareLogic(Config);
              ComparisonResult result = compareLogic.Compare(Blist[i], locold);
}
}

**Comment by GregFinzer** [comment]
I would take the constructor outside the loop to see if that helps.  If not,  use a profiler to see which line of code is causing the issue.   Create a fix and I will merge in the pull request.

**Comment by pyengwoei** [comment]
> I would take the constructor outside the loop to see if that helps. If not, use a profiler to see which line of code is causing the issue. Create a fix and I will merge in the pull request.

ok， i try first

**Comment by GregFinzer** [comment]
Any update?  It has been a week.

**Comment by pyengwoei** [comment]
> Any update? It has been a week.

sorry reply later， still need to wait a few days

**Comment by pyengwoei** [comment]
`List Alist, List Blist;
CompareLogic compareLogic = new CompareLogic(Config);
for (int i = 0; i < Blist.Count; i++)
{
if (Alist.Exists(x => x.name == new[i].name{
var locold = Alist.Find(x => x.name == Blist[i].name);
ComparisonResult result = compareLogic.Compare(Blist[i], locold);
}
}`
 the  code like this now,but cpu still very high

**Comment by GregFinzer** [comment]
Use a profiler to see which line of code is causing the issue.  After you create a fix for the issue, create a pull request and I will merge in the fix.

**Comment by GregFinzer** [comment]
I haven't heard anything back.  Closing issue.
