### ISSUE TITLE
Trying to confirm the DoublePrecision is working as expected

### ISSUE THREAD

**Issue by rubans** [GregFinzer/Compare-Net-Objects#148]
I have the following values :
```
   double decimal1 = 32299999.1;
            double decimal2 = 32300000.2;
            double precision = .0001;
            var comparer = new CompareLogic()
            {
                Config = new ComparisonConfig()
                {
                    DoublePrecision = precision
                }
            };
            var diff = comparer.Compare(decimal1, decimal2);
            double acceptableDifference = Math.Abs(decimal1 * precision);
            Console.WriteLine($"Diff:{diff.Differences.Count()}:{Math.Abs(decimal1 - decimal2)} < {acceptableDifference}");
        }

```

I was expecting the tolerance level I have allowed for in the double precision of 0.0001 would highlight the fact the difference between the two values as it's over 1. However, the comparer doesn't show this as being different and in fact say it's equal. This doesn't seem right to me but I assuming I'm missing something. Would be good to understand why the above isn't highlighted as different?

**Comment by GregFinzer** [comment]
@rubans Thank you for reporting the issue.  I have fixed it with this commit:
https://github.com/GregFinzer/Compare-Net-Objects/commit/d86e74fe58f50642ec90de11fb4f58cb3da41533

**Comment by GregFinzer** [comment]
I also added this test:

        [Test]
        public void RubansDifference()
        {
            double double1 = 32299999.1;
            double double2 = 32300000.2;
            _compare.Config.DoublePrecision =  .0001;
            ComparisonResult result = _compare.Compare(double1, double2);

            Assert.IsFalse(result.AreEqual);
        }

**Comment by rubans** [comment]
Thanks @GregFinzer, will try it out.

**Comment by rubans** [comment]
@GregFinzer , how do I get this latest commit into a nuget build? Currently I see 4.58.0
I'm not familiar with process so apologies if a silly Q :)

**Comment by GregFinzer** [comment]
You will have to wait until I do a build.   I will do a build the weekend of May 11th.
