### ISSUE TITLE
DateTimeOffsetComparer

### ISSUE THREAD

**Issue by ElliotSis** [GregFinzer/Compare-Net-Objects#15]
Hi,

The DateTimeOffset comparer compares the DateTime properties of the two objects.
Shouldn't it be comparing the UtcDateTime properties instead, as mentionned here : 
https://msdn.microsoft.com/en-us/library/system.datetimeoffset.compare(v=vs.110).aspx ?

Thanks,
Elliot.

**Comment by GregFinzer** [comment]
Sounds good to me.  I will change it.

**Comment by ElliotSis** [comment]
Great. Thanks.

**Comment by dradovic** [comment]
Had the same issue. Seems like the library is not comparing `DateTimeOffset`s correctly. Is there an expected release when this will be fixed?

**Comment by dradovic** [comment]
BTW, I'm using the following fix/workaround in the meantime:

        private class FixedDateTimeOffSetComparer : DateTimeOffSetComparer
        {
            public FixedDateTimeOffSetComparer(RootComparer rootComparer) : base(rootComparer)
            {
            }

            public override void CompareType(CompareParms parms)
            {
                if (parms.Object1 == null || parms.Object2 == null || 
                    (Math.Abs(((DateTimeOffset)parms.Object1).DateTime.Subtract(((DateTimeOffset)parms.Object2).DateTime).TotalMilliseconds) <= (double)parms.Config.MaxMillisecondsDateDifference &&
                    ((DateTimeOffset)parms.Object1).Offset == ((DateTimeOffset)parms.Object2).Offset))
                    return;
                AddDifference(parms);
            }
        }

and then:

            compareLogic.Config.CustomComparers.Add(new FixedDateTimeOffSetComparer(RootComparerFactory.GetRootComparer()));

**Comment by GregFinzer** [comment]
Sorry, there is no timeline.

**Comment by dradovic** [comment]
Good to know. Thank you for your wonderful library. It helped me a lot.

One more thing to mention: the Equals on DateTimeOffset compares if two DateTimeOffset represent the same point in time. So they could have different offset and date-time parts but still be "equal". I can imagine that for this library there would be both use cases. So it might be some option that should be added.

**Comment by ElliotSis** [comment]
I added a pull request regarding that issue.

**Comment by dradovic** [comment]
@ElliotSis: so your fix covers the other use-case. In my use-case, I also wanted to assure that the timezoneoffsets are equal, otherwise I want to treat the objects as not equal.

**Comment by ElliotSis** [comment]
Yes, it's probably best to add that in the conf and let the user decide whether or not he wants to compare the offsets.
The default behavior should be to compare the UtcDateTime properties though, as mentionned by MSDN.
I'll commit a change with that feature later during the week.

**Comment by ElliotSis** [comment]
It's done, let me know if that's what you had in mind.

**Comment by dradovic** [comment]
@ElliotSis: nice. From my point of view, all we need.
