### ISSUE TITLE
MembersToIgnore not working in a certain scenario with ClassName.PropertyName

### ISSUE THREAD

**Issue by rubans** [GregFinzer/Compare-Net-Objects#152]
When I set it to ignore a specific ClassName.PropertyName inside a class, it doesn't seem ignore the property in a certain scenario, I tracked down the the issue when used with IgnoreCollectionOrder.
For e.g. 
compare.Config.MembersToIgnore.Add("Person.Name");

It still shows as a diff in the comparision result but does work as expected when IgnoreCollectionOrder = false is true.

It also works if I just specify the Name without ClassName prefix, to me logically it feels it should just work regardless IgnoreCollectionOrder.
Let me know if you need anymore info...

**Comment by GregFinzer** [comment]
@rubans Thank you for reporting the issue.  Can you create a failing unit test please?

**Comment by GregFinzer** [comment]
No response.  Closing issue.
