### ISSUE TITLE
There is a bug in KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.RespectNumberToString(Object o)

### ISSUE THREAD

**Issue by zhyy2008z** [GregFinzer/Compare-Net-Objects#154]
Source Code of KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.RespectNumberToString(Object o):
```
switch (Type.GetTypeCode(o.GetType()))
            {
                case TypeCode.Decimal:
                    return ((decimal)o).ToString("G29");
                case TypeCode.Double:
                case TypeCode.Single:
                    return ((double)o).ToString("G");
                default:
                    return o.ToString();
 }
```
When o is float type, `((double)o).ToString("G");` will throw an InvalidCastException!

test codes:
[https://dotnetfiddle.net/lKbH5I](https://dotnetfiddle.net/lKbH5I)

**Comment by GregFinzer** [comment]
@zhyy2008z Thanks for reporting this issue.  Please fix the defect, create a pull request and I will be happy to merge it in.
