### ISSUE TITLE
Possibility to add functional & generic compare interface?

### ISSUE THREAD

**Issue by goyzhang** [GregFinzer/Compare-Net-Objects#155]
Hi,
I follow the Wiki to use `Custom Comparers`, everything is good. But I'm wondering if we can improve this custom behavior a little bit by adding functional-like interfaces that allow the user to define how to compare easily (and the predication can be dynamic!)
The following is a VERY ROUGH proposal that ONLY addresses the idea:

  ```
 class CustomComparer<T1, T2> : BaseTypeComparer
    {
        public Func<T1, T2, bool> HowToCompare = (o1, o2) => false;
        public CustomComparer(RootComparer rootComparer) : base(rootComparer)
        {
        }

        public override void CompareType(CompareParms parms)
        {
            if (HowToCompare((T1)parms.Object1, (T2)parms.Object2))
            {
                AddDifference(parms);
            }
        }

        public override bool IsTypeMatch(Type type1, Type type2)
        {
            return type1 == typeof(T1) && type2 == typeof(T2);
        }
    }
```

Use:
```
var doubleComparer = new CustomComparer<double, double>(RootComparerFactory.GetRootComparer());
            doubleComparer.HowToCompare = (double1, double2) => double1 < double2;
```

**Comment by GregFinzer** [comment]
How would this affect the existing code?  What benefit would this have?

**Comment by goyzhang** [comment]
I think we prefer to "extend" rather than change?
One benefit is a more easy-to-use and flexible API, and users can change their compare predictions by simply sending their own function as a parameter at runtime. I'm not a system designer so I'm not sure how much side-effect would this bring.

**Comment by GregFinzer** [comment]
Thanks for the new feature!
