### ISSUE TITLE
Switch off Objects comparison based on HashCode

### ISSUE THREAD

**Issue by jhlogis** [GregFinzer/Compare-Net-Objects#157]
Could It be possible to add new switch to config to switch of feature "objects with the same HashCode are considered as the same"?

Unfortunately We use HashCodes for another logic in application and they cannot be unique for each object.

And HashCodes in general can be same even for two different objects of same type.

**Comment by GregFinzer** [comment]
How could objects be identified without the hash code?

**Comment by jhlogis** [comment]
I don´t know exactly how You mean it. In general Hash Code is not unique identifier over objects of one type, let alone objects of any type. 
In Our case object's HashCode is ID column from database, so sequence number. Each entity has it's own sequence of ID's. So entity A has object with HashCode 1 and entity B has also object with HashCode 1. And these objects are definitely not the same.

I see in source code that HashCode is checked only on this place (in FieldComparer and PropertyComparer):
`            
            bool object1IsParent = objectValue1 != null && (objectValue1 == parms.Object1 || parms.Result.Parents.ContainsKey(objectValue1.GetHashCode()));
            bool object2IsParent = objectValue2 != null && (objectValue2 == parms.Object2 || parms.Result.Parents.ContainsKey(objectValue2.GetHashCode()));

            //Skip fields that point to the parent
            if ((TypeHelper.IsClass(item.FieldType) || TypeHelper.IsInterface(item.FieldType))
                && (object1IsParent || object2IsParent))
            {
                return;
            }
`

So when parent object has the same HashCode as nested object and even if each of them has different type, they are considered as same and comparison of nested object will not happen. 

Enough for me would be, if there would be some switch in config which would ensure skipping those expressions: || parms.Result.Parents.ContainsKey(objectValue1.GetHashCode()).

**Comment by GregFinzer** [comment]
The problem is if we switch off the GetHashCode, detecting circular references will break.  I think the best idea is for you to fork compare .net objects to your specific needs.  Good luck with your project.
