### ISSUE TITLE
Ignore certain members - how?

### ISSUE THREAD

**Issue by grzesiek-galezowski** [GregFinzer/Compare-Net-Objects#16]
Hi,

I tried to find some way of comparing two data structures without certain specific members.
I thought maybe the `.Config.MembersToIgnore` could be used for that, but I cannot find any examples on how to use it for this purpose. Just adding a name of ignored property to that list doesn't seem to work (e.g. when I have a property called `Span`, then adding "Span" to `MembersToIgnore` doesn't seem to make it ignored).

Is there such functionality? If so, how to use it?

**Comment by GregFinzer** [comment]
Please see the help file and all the unit tests.
