### ISSUE TITLE
Compare Xamarin.Forms UI objects?

### ISSUE THREAD

**Issue by Lelelo1** [GregFinzer/Compare-Net-Objects#160]
Is it possible to compare Xamarin.Forms UI objects with this library? I am running into some issues:

```
Xamarin.Forms.Label l = new Label() { Text="Yo" };
Xamarin.Forms.Label la = new Label();
CompareLogic compareLogic = new CompareLogic();
compareLogic.Config = new ComparisonConfig() { MaxDifferences = Int32.MaxValue, ComparePrivateFields = true, ComparePrivateProperties = true }; // SkipInvalidIndexers = true, IgnoreObjectTypes = true 
var diff = compareLogic.Compare(la, l);
```

I get `System.Exception` with message `Cannot compare objects with a non integer indexer for object Resources`

When setting `SkipInvalidIndexers = true` I get `System.NotSupportedException` with message `Cannot compare object of type Boolean`; When also setting `IgnoreObjectTypes = true`  I get `System.ArgumentException` with message `Object must be of type Double`.

When trying with `Xamarin.Forms.Stacklayout`instead of `Label` the `compareLogic.Compare(la, l)` runs - but only if `SkipInvalidIndexers = true` is set in config.

**Comment by GregFinzer** [comment]
I would say that you will need to write your own comparer for Xamarin Forms as it is not possible to loop through non integer indexes.
