### ISSUE TITLE
Duplicate differences count-length-long length

### ISSUE THREAD

**Issue by harry9876** [GregFinzer/Compare-Net-Objects#162]
When I use a simple array and there is a difference in the length of arrays  I get 3 differences:

> Types [ChildObject[],ChildObject[]], Item Expected.C.Count != Actual.C.Count, Values (2,1)
Types [Int32,Int32], Item Expected.C.Length != Actual.C.Length, Values (2,1)
Types [Int64,Int64], Item Expected.C.LongLength != Actual.C.LongLength, Values (2,1)

When I change the arrey to list, a single difference will appear.

> Types [List`1,List`1], Item Expected.C.Count != Actual.C.Count, Values (2,1)

There is a way to use the array and get a single difference?

**Comment by harry9876** [comment]
I put:
`    CompareLogic compareLogic = new CompareLogic(config);
            compareLogic.Config.MembersToIgnore.Add("*Length");
            ComparisonResult result = compareLogic.Compare(deep1, deep2);`

and it works fine.

**Comment by GregFinzer** [comment]
@harry9876 I am glad you figured it out.
