### ISSUE TITLE
Cant find IgnoreProperty Method in Config as describe in wiki.

### ISSUE THREAD

**Issue by himel951** [GregFinzer/Compare-Net-Objects#163]
In this wiki https://github.com/GregFinzer/Compare-Net-Objects/wiki/Ignoring-Members Ignore By Expression does not work as i can't find IgnoreProperty method. Could you please help me to solve this problem.

**Comment by GregFinzer** [comment]
@himel951 Sorry, there has not been a NuGet build for that yet.  I will do one over the weekend.

**Comment by himel951** [comment]
@GregFinzer Thanks :)

**Comment by rdeslonde-eichleay** [comment]
@GregFinzer Can I use that IgnoreProperty method to ignore conditionally? Something like:

comparer.Config.IgnoreProperty<NetworkInterfaceInfoDocument>(x => x.NetworkInterfaceType == "Wireless80211" ? x.Speed : x.NodeId);

I basically want to be able to ignore Speed property, but only if the NetworkInterfaceType is "Wireless80211".

**Comment by GregFinzer** [comment]
I have no idea.  You will have to ask @ajepst who implemented that feature.

**Comment by ajepst** [comment]
Hi!  Unfortunately, that won’t work. The Ignore code I added is just a very light layer on top of the existing code. If you take a look at the implementation, it is doing a simple grab of the property name from the expression and feeding that as a string into the already-existing string collection of property names to reduce having to rely on magic strings matching properties. It does not have any capabilities different from the string-based version of Ignore.  If, however, you wanted to do a richer  implementation that accepts the kind of conditional expression you propose, I can confirm that @GregFinzer accepts pull requests!

**Comment by GregFinzer** [comment]
Deployed to NuGet as Version 4.61.  Closing issue.
