### ISSUE TITLE
Custom comparison for specific member(s)

### ISSUE THREAD

**Issue by TomYip** [GregFinzer/Compare-Net-Objects#165]
First of all, very nice library for deep comparison! I'm trying to compare 2 complex objects, and for one specific string field, I wanted to have the rule:

If (x.Field1 == "Value1" && y.Field1 == "Value2"), the objects are still equal. 

I looked into the option of using custom comparer, I think it will work if I compare all the fields in the class, but if the class has new fields added, then the custom comparer will need to be updated as well. Which makes the code less manageable.

Is there a way to use the root comparer to the objects and get the diff first, then have custom comparer to override the result by checking the diff and make a decision? 

Thanks :)

**Comment by GregFinzer** [comment]
That option is not available.   It sounds like you need some custom code before using Compare .Net Objects or implement IComparable.
