### ISSUE TITLE
O(n²) in unordered lists

### ISSUE THREAD

**Issue by jsobell** [GregFinzer/Compare-Net-Objects#167]
When collection orders are ignored performance is taking a huge hit. A simple comparison of two arrays of integers is unusable above 5000, so we really need a way of either overriding specific property comparisons (to allow, for example, a passed in Func that compares a specific item) or looking at assigning one side to a dictionary to fast-lookup the other side items.
Obviously any unsorted list generic comparison will be O(n²), but for basic types perhaps we could shortcut things by defaulting to use of Hash?

```Csharp
        [Test]
        public void ComparerIgnoreOrderNumericArraysTest()
        {
            const int len = 5000;
            var a = new Int32[len];
            var b = new Int32[len];
            for (var i = 0; i < len; i++)
            {
                a[i] = i;
                b[len - 1 - i] = i;
            }

            var comparer = new CompareLogic();
            comparer.Config.IgnoreCollectionOrder = true;
            comparer.Config.MaxDifferences = 1;

            ComparisonResult result = comparer.Compare(a, b);
            Console.WriteLine(result.DifferencesString);
            Assert.IsTrue(result.AreEqual);
        }
```

**Comment by GregFinzer** [comment]
@jsobell Sounds good.  Please implement and I will merge in the pull request.

**Comment by GregFinzer** [comment]
@jsobell Did you see the collection matching spec?
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths

**Comment by jsobell** [comment]
I'd assumed that meant any remaining items would be considered differences:
`[1,2,2]` vs `[1,1,2]` gives differences of `"2","(null)"` and `"(null)","1"`
`[1,2,3]` vs `[4,3,2,1]` give difference of `"(null)","4"` and various Length and Count properties

I'll submit a PR for a dictionary based match that you can check out. I've not used this library before today, so please check carefully to see if there is any breaking functionality that wasn't covered by the unit tests :)

**Comment by GregFinzer** [comment]
Merged.  Thanks so much!

**Comment by jsobell** [comment]
No problem 😃 
When would you normally push to NuGet?

**Comment by GregFinzer** [comment]
@jsobell I usually release in at least three enhancements/bugs.  There is one bug left and one enhancement in progress.  Let me check with the other developer doing the enhancement.

**Comment by GregFinzer** [comment]
Released
