### ISSUE TITLE
Library does not compare correctly due to fundamental issue

### ISSUE THREAD

**Issue by maxcherednik** [GregFinzer/Compare-Net-Objects#169]
>GetHashCode must be unique for each object. If the hash code is the >same for two objects, they will be considered equal.

**This is very wrong.**
This statement contradicts the whole idea behind the GetHashCode and Equals.

> Two objects that are equal return hash codes that are equal. However, the reverse is not true: equal hash codes do not imply object equality, because different (unequal) objects can have identical hash codes. Furthermore, .NET does not guarantee the default implementation of the GetHashCode method, and the value this method returns may differ between .NET implementations, such as different versions of .NET Framework and .NET Core, and platforms, such as 32-bit and 64-bit platforms.

https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=netframework-4.8#remarks

We had a false positive equality of two objects which were not equal.

**Comment by GregFinzer** [comment]
@maxcherednik Sorry, there is nothing that can be done about this.  To my knowledge there is no other way to keep track of objects except for the hash code.  That is how the parents and children are tracked for circular references.

**Comment by maxcherednik** [comment]
@GregFinzer 
1. I think json.net somehow does it while serializing - we can have a look there.
2. Even if we don't do number 1, we can follow the general convention and use Equals so that to actually check if object are the same.

**Comment by GregFinzer** [comment]
I have been thinking about this for a few hours now.  I will see what I can do.

**Comment by GregFinzer** [comment]
Fixed

**Comment by maxcherednik** [comment]
And the next release is?

**Comment by GregFinzer** [comment]
I still need to fix this bug:
https://github.com/GregFinzer/Compare-Net-Objects/issues/166

@SteveDunn is still working on this enhancement:
https://github.com/GregFinzer/Compare-Net-Objects/issues/164

**Comment by GregFinzer** [comment]
Released
