### ISSUE TITLE
Security issues in Compare-Net-Objects library

### ISSUE THREAD

**Issue by harry9876** [GregFinzer/Compare-Net-Objects#170]
Hi, How do you plan to deal with future security issues in Compare-Net-Objects library?

**Comment by GregFinzer** [comment]
@harry9876 There are currently no security features.  If you request something, you would be responsible for implementing the change.

**Comment by harry9876** [comment]
I didn't mean to add security features.
I meant to ask what if security **vulnerabilities** will be found in the library in the future? Do you plan to review and fix them?

**Comment by GregFinzer** [comment]
@harry9876 No sorry I do not plan to review and fix security vulnerabilities in the future.  If you would like to fix security vulnerabilities I would be happy to merge in any pull requests.
