### ISSUE TITLE
Comparing List

### ISSUE THREAD

**Issue by wireless90** [GregFinzer/Compare-Net-Objects#171]
Hi quick question.
List1: {1, 2, 3}
List2: {1, 2}

Is it possible for it to tell me that List 1 has '3' but List 2 doesnt, instead of telling me List1.count!= List2.count

**Comment by GregFinzer** [comment]
@wireless90 Sorry it does not have that ability.  You can certainly add it and I will be happy to merge in the pull request.

**Comment by GregFinzer** [comment]
@wireless90 I must have been tired.  Yes it does support that:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths
