### ISSUE TITLE
Produce more helpful `Difference.ObjectXValue` for objects without `.ToString()` override

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-clarksons** [GregFinzer/Compare-Net-Objects#172]
This would especially help with simple cases where one of the objects is a `null` (other cases are mostly fine because then the library goes down to the primitive-valued properties). It's especially of issue for IEnumerables.

Currently, what the library outputs is a very lengthy and hard to understand piece of text:
```
Types [WhereSelectEnumerableIterator`2,null], Item expected != actual, Values (System.Linq.Enumerable+WhereSelectEnumerableIterator`2[MyOrganization.MyApp.SomeFeature.Core.Model.Blah.SomeEntity,MyOrganization.MyApp.SomeFeature.Core.Model.Blah.SomeEntity],(null))
```
A perfect value to choose in these would be a serialization of the object (would handle IEnumerables and named and anonymous objects alike), e.g. to JSON.

If an extra dependency is a problem here, perhaps provide a way for users to plug this in, .e.g. `ComparisonConfig.GetNoToStringFallbackValue`. A simple function to detect that there's no `ToString` override is:
```
bool IsToStringMethodFromObject(object value) => value != null && value.GetType().GetMethod("ToString", types: new Type[0]).DeclaringType == typeof(object);
```

If, for some reason, this solution is not an option, what could be considered at least is adding support for `IEnumerables` (e.g. display `[].Count=5` instead of the `System.Linq.Enumerable+WhereSelectEnumerableIterator``2[...]`).

**Comment by GregFinzer** [comment]
I don't want to introduce a JSON.NET dependency.  The other two options are fine.  Please implement and I will merge in the pull request.

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Thanks.
As for implementation, this is only for quite a busy project at work - I don't think I can convince the stakeholders to allow me to familiarize myself with the codebase and fully implement this to contribution standards any time soon. Nevertheless, I felt it was a worthy suggestion to give. If this means that implementing the feature though other means won't happen, feel free to close the issue.

**Comment by GregFinzer** [comment]
@slawomir-brzezinski-at-clarksons , I will leave open for a while in case someone wants to help.  I know what you mean by busy.  I have a day job, a side business, and three kids.

**Comment by GregFinzer** [comment]
Closing inactive issue.
