### ISSUE TITLE
Add Postprocessing to Custom Comparers

### ISSUE THREAD

**Issue by Krizzzn** [GregFinzer/Compare-Net-Objects#173]
In my project I've implemented a custom comparer for being able to extract the actual string (that resides inside an object within a dictionary) instead of the object type name. This was working perfectly fine until I've added a new entry to the dictionary that did not exist before. The result would always be `Texts Val[[ EN Requirements, Text Item]] Item: (null) CHANGED TO -> [EN_Requirements, TextItem]`.
The custom comparer is not called if any value is null before. Instead the default behaviour is being run because of: 
https://github.com/GregFinzer/Compare-Net-Objects/blob/473b020c63e52290fafc4c62cc97c259b0d1d9a9/Compare-NET-Objects/RootComparer.cs#L59

That's why I added a Post Processing method to my custom comparer like this:

```
ComparisonResult result = compareLogic.Compare(one, two);
foreach (var item in result.Differences)
{
    textComparer.PostProcess(item);
}
```
After the comparison is run over all the differences and call this new method `PostProcess` on my custom comparer.

This then overwrites the ObjectValues in the given `Difference`:
```
public class CompareTexts : BaseTypeComparer {
[...]
        public void PostProcess(Difference item)
        {
            if (!IsTypeMatch(item.Object1?.GetType(), item.Object2?.GetType()))
                return;

            if (item.Object1 != null && item.Object2 != null)
                return;

            if (item.Object1 != null)
            {
                var comparison = (KeyValuePair<string, TextItem>)item.Object1;
                item.Object1Value = comparison.Value.MarkdownText;
            }
            if (item.Object2 != null)
            {
                var comparison = (KeyValuePair<string, TextItem>)item.Object2;
                item.Object2Value = comparison.Value.MarkdownText;
            }
        }
[...]
}
```
Maybe you like the Idea and add it to next version

**Comment by GregFinzer** [comment]
@Krizzzn I think it would be more useful to simply display the dictionary value without having a PostProcess to fill in.  Do you think this would be something you could implement?

**Comment by GregFinzer** [comment]
@Krizzzn Great job!
