### ISSUE TITLE
Comparing HashSet<T> with List<T> does not find differences

### ISSUE THREAD

**Issue by TimSirmovics** [GregFinzer/Compare-Net-Objects#176]
When comparing a `HashSet<T>` to another collection type like `List<T>`, the differences are not returned.

```
var hashSet = new HashSet<int> { 1 };
var list = new List<int> { 2 };

var compare = new CompareLogic();
compare.Config.IgnoreObjectTypes = true;

var result = _compare.Compare(hashSet, list);
// result.AreEqual is true
```

I had a dig through the other issues and the Wiki but couldn't find anything specific to HashSets.

**Comment by GregFinzer** [comment]
@TimSirmovics The compare .NET Objects Library does not support something like that.  The IgnoreObjectTypes is more at the class level.  So if you have a Customer object and a Vendor object both deriving from a Person object with similar properties then you can compare that.  There has been no implementation made for comparing lists of different types.  This would be an enhancement.

**Comment by TimSirmovics** [comment]
@GregFinzer Looking at unit test `CollectionsSame` in `CompareCollectionsTests`, this test creates 2 collections with different types and uses the `IgnoreObjectTypes` to make the comparison work.

It seems that `CollectionComparer` was written to compare any two objects that implement `ICollection`, but `HashSet<T>` only implements `ICollection<T>` and not `ICollection` so this comparer is not used.

Would you be happy for me to see if I can get `CollectionComparer` working with `ICollection<T>`? And if so are you still happy for this to work because of  `IgnoreObjectTypes`?

**Comment by GregFinzer** [comment]
@TimSirmovics Yes that sounds like a wonderful enhancement.  Please remember to add your test above to the test project.  Thanks so much!

**Comment by GregFinzer** [comment]
Closing inactive issue.

**Comment by shihalv** [comment]
Can we reopen this issue? This looks to be quite critical for what the library is supposedly meant to achieve.

**Comment by GregFinzer** [comment]
@shihalv Sure, please implement this functionality with a unit test and I will merge in the pull request.

**Comment by TimSirmovics** [comment]
I had a look at this and implemented a `GenericCollectionComparer` inserted into the `RootComparer` immediately after the existing `CollectionComparer`, along with unit tests.

This caused some other unit tests to fail, some of which I am not sure how to proceed.

**CompareDynamicTests.CompareLogicShouldHandleExpandoObjects()**
Although `ExpandoObject` implements `ICollection<KeyValuePair<string, object>>`, you cannot access the properties of that interface.
I'm not too familiar with this object or dynamic in general, so I just excluded this type from the `GenericCollectionComparer`.
There may be a better solution.

**CompareIndexerTests.TestIndexerLengthNegative()**
This test compares two `ListClass<Person>`, which implement `ICollection<Person>`.
Currently this is dealt with by the `ClassComparer`, but would not get picked up by the `GenericCollectionComparer`.
The result is 3 differences, the 3rd of which is the index of the last item in List 1, [3], which List 2 doesn't contain.
This different is identified by the `IndexerComparer`.
My problem is the implementation of `IgnoreCollectionOrder` within the `IndexerComparer`.
The documentation for [Comparing Lists of Different Lengths](https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths) says that the comparison will end as soon as it reaches the end of one of the lists.
This is how the `CollectionComparer` works, it stops at the end of list 2 and does not register a difference.
The implementation in `IndexerComparer` also looks at this option, but will compare to the end of the longest list, registering differences for each index missing from one of the lists.
I would assume we would want the `GenericCollectionComparer` to act the same as  `CollectionComparer`, however that would be a breaking change, at least for this test case.

@GregFinzer thoughts?

**Comment by GregFinzer** [comment]
With over 15 million downloads as of right now we want to prevent any breaking changes.   Implement similar to what is there today to get all the tests to pass.  If the counts of the collections are different then simply log a difference and exit immediately otherwise compare the collection items.  You might need to implement something in the IgnoreOrderLogic for your GenericCollectionComparer as well.

**Comment by TimSirmovics** [comment]
Yeah.. I'm just going to leave it.
There are inconsistencies in how collection differences are reported, depending on which comparer you end up in.
I don't want to add any breaking changes but the end result in my opinion is confusing.. using the same options and changing the collection types will give you different results.

**Comment by GregFinzer** [comment]
Ok @TimSirmovics thanks for looking into this.
