### ISSUE TITLE
Ignore inherited Properties of a class does not work

### ISSUE THREAD

**Issue by pagratios** [GregFinzer/Compare-Net-Objects#177]
```
public class Base
{
  public int Id { get; set; }
}

public class Foo : Base
{
  public string Name { get; set; }
  public List<Bar> Bars { get; set; }
}

public class Bar : Base
{

  public bool IsAvailable { get; set; }
  public int Code { get; set; }
}

[Test]
public void CompareTests()
{
  var item1 = new Foo
  {
    Id = 1,
    Name = "Foo",
    Bars = new List<Bar>
    {
      new Bar
      {
        Id = 1,
        Code = 101,
        IsAvailable = true
      }
    }
  };

  var item2 = new Foo
  {
    Id = 1,
    Name = "Foo",
    Bars = new List<Bar>
    {
      new Bar
      {
        Id = 3,
        Code = 101,
        IsAvailable = true
      }
    }
  };

  var config = new ComparisonConfig();
  config.IgnoreProperty<Bar>(x => x.Id);
  var comparer = new CompareLogic {Config = config};
  Assert.IsTrue(comparer.Compare(item1, item2).AreEqual); //return false
}
```

In the example above, I am trying to compare 2 Foo types where Foo.Id must be the same and Bar.Id could be different.

It seems that IgnoreProperty methods does `MembersToIgnore.Add(typeof(TClass).Name + "." + name);`

but the ExcludeLogic.ShouldExcludeMember checks for `config.MembersToIgnore.Contains(info.DeclaringType.Name + "." + info.Name);` where declaring type is my Base class.

I changed the `info.DeclaringType.Name` with `info.ReflectedType.Name` and all your tests passed

Maybe due to backward compatibility a new option to ComparisonConfig might be a solution.
MemberInfo.ReflectedType is not available to .Net Standard 1.3

**Comment by GregFinzer** [comment]
You can certainly create a PR that accounts for .NET Standard 1.3 and .NET Standard 2.0 by using compiler pre-processor directives.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if

**Comment by pagratios** [comment]
on `PropertyComparer.AddPropertyInfos` is created a `PropertyEntity` with `DeclaringType` the type of the comparing object, although `PropertyInfo.DeclaringType` return the class  base class.

on `ExcludeLogic.ShouldExcludeDynamicMember` is called with `PropertyEntity.DeclaringType` 
although `ExcludeLogic.ShouldExcludeMember` is called with `PropertyEntity.PropertyIfo`

Is the behavior correct?

**Comment by GregFinzer** [comment]
@pagratios Correct or not, I do not want to change it with over 2 million users now using the library they are depending upon the existing implementation.

**Comment by pagratios** [comment]
You are right about the backward compatibility. 
If I break something will your tests fail?

**Comment by GregFinzer** [comment]
Fixed with https://github.com/GregFinzer/Compare-Net-Objects/pull/178

Thanks!
