### ISSUE TITLE
Enhancement for ShouldExcludeMember

### ISSUE THREAD

**Issue by dgauerke** [GregFinzer/Compare-Net-Objects#18]
This function is globally excluding member names, not something specific to a class.  For example, if I have classes like this:
    public class ClassWithGuid
    {
        public ClassWithGuid()
        {
            MyGuid = Guid.NewGuid();
        }

```
    public Guid MyGuid { get; set; }
    public int SomeInteger { get; set; }
}

public class AnotherClassWithGuid
{
    public AnotherClassWithGuid()
    {
        MyGuid = Guid.NewGuid();
    }

    public Guid MyGuid { get; set; }
    public int SomeInteger { get; set; }
}

public class ClassWithClassWithGuid
{
    public ClassWithClassWithGuid()
    {
        cls = new ClassWithGuid();
        aCls = new AnotherClassWithGuid();
    }

    public ClassWithGuid cls { get; set; }
    public AnotherClassWithGuid aCls { get; set; }
}
```

if will ignore the member name in both classes.  I would like to make a suggestion to change this function to something like this:

```
    public static bool ShouldExcludeMember(ComparisonConfig config, MemberInfo info)
    {
        //Only compare specific field names
        if (config.MembersToInclude.Count > 0 && !config.MembersToInclude.Contains(info.Name))
            return true;

        **var name = info.Name;
        if (info.DeclaringType != null)
            name = info.DeclaringType.Name + "." + name;

        //If we should ignore it, skip it
        if (config.MembersToIgnore.Count > 0 && config.MembersToIgnore.Contains(name))
            return true;**

        if (IgnoredByAttribute(config, info))
            return true;

        return false;
    }
```

And then when adding members to exclude, the syntax would be:
MembersToIgnore.Add("ClassWithGuid.MyGuid");

Making it configurable to support backward compatibility would be fine.  Just need to add an option to the Config.

Thanks,
David Gauerke

**Comment by GregFinzer** [comment]
That is a good idea.  I will put it on the list.

**Comment by miro-ur** [comment]
+1 Vote. .. Just what I was looking for. Thumbs up for the change !

**Comment by GregFinzer** [comment]
Done:
https://www.nuget.org/packages/CompareNETObjects/
