### ISSUE TITLE
Getting error while comparing two datatables - System.Exception: 'Indexer must have a corresponding Count property that is an integer for object DefaultView[0]

### ISSUE THREAD

**Issue by etashutoshkumar** [GregFinzer/Compare-Net-Objects#180]
Hi Team,
            
I am getting error - **System.Exception: 'Indexer must have a corresponding Count property that is an integer for object DefaultView[0]** while comparing two datatables.  Below is my sample code. Can someone please assist me on this issue? Thanks in advance

DataTable dt = new DataTable();
            dt.Clear();
            dt.Columns.Add("Name");
            dt.Columns.Add("Marks");
            DataRow _ravi = dt.NewRow();
            _ravi["Name"] = "ravi";
            _ravi["Marks"] = "500";
            dt.Rows.Add(_ravi);

            DataTable dt1 = new DataTable();
            dt1.Clear();
            dt1.Columns.Add("Name");
            dt1.Columns.Add("Marks");
            DataRow _ravi1 = dt1.NewRow();
            _ravi1["Name"] = "ravi";
            _ravi1["Marks"] = "234";
            dt1.Rows.Add(_ravi1);

            var comparer = new CompareLogic
            {
                Config =
                {
                    MaxDifferences = int.MaxValue
                }
            };

            var differences = comparer.Compare(dt, dt1);

**Comment by GregFinzer** [comment]
Sorry, no time to review this now.

**Comment by GregFinzer** [comment]
@etashutoshkumar 

Please add a data type for each column.  That is the problem.

Thanks,
Greg
