### ISSUE TITLE
Regression Introduced in v4.62.0

### ISSUE THREAD

**Issue by aescharfenberg** [GregFinzer/Compare-Net-Objects#181]
I am a long-time user of the CompareNetObjects library, and I believe I have discovered a regression that was introduced in v4.62.0.  When I revert back to v4.61.0 or prior, my code works again.  The following is the code to produce the issue:

        [TestMethod]
        public void Subject_Validate_Valid()
        {
            // Arrange
            var subject = BuildSubject();
            var expected = new[] { ValidationResult.Success }; // ValidationResult.Success = null

            // Act
            var actual = subject.Validate(); // Also returns ValidationResult.Success

            // Assert
            var result = ObjectComparer.Compare(expected, actual);
            Assert.IsTrue(result.AreEqual, result.DifferencesString);
        }

ObjectComparer.Compare method:

        public static ComparisonResult Compare(object expectedObject, object actualObject, IEnumerable<string> membersToIgnore = null, bool redactValues = false)
        {
            var config = new ComparisonConfig
            {
                IgnoreCollectionOrder = true,
                IgnoreObjectTypes = true,
                MaxDifferences = 100
            };

            if (membersToIgnore != null)
            {
                config.MembersToIgnore = new List<string>(membersToIgnore);
            }

            if (redactValues)
            {
                config.DifferenceCallback = difference =>
                {
                    difference.Object1Value = Constants.RedactedText;
                    difference.Object2Value = Constants.RedactedText;
                };
            }

            var compare = new CompareLogic(config);
            var result = compare.Compare(expectedObject, actualObject);
            return result;
        }

The expected result is that the unit test passes successfully.  The result I know get is the following exception (as produced by our TFS gated build):

System.NullReferenceException: Object reference not set to an instance of an object.
Stack Trace:
at System.Object.GetType()
at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareOutOfOrder(CompareParms parms, Boolean reverseCompare)
at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)

The ObjectComparer.Compare method is a common method used throughout the unit and integration tests in my Visual Studio solution to make sure that object graphs are compared the same way each time.  I would really like to not have to fiddle with the ComparisonConfig based off of whether or not I am expecting something in the object graph to be null vs. not null.

Can this issue be addressed in an upcoming version of CompareNetObjects?  I really love the library, and I would like to be able to stay up-to-date with future versions of the library.  Right now, I am stuck on v4.61.0 until this issue is addressed (or a workaround is identified).

Thanks!
Allen

**Comment by GregFinzer** [comment]
Allen,

I would need the full test code to reproduce locally.

Thanks,
Greg

**Comment by aescharfenberg** [comment]
I will get that to you today.

**Comment by aescharfenberg** [comment]
Greg,

The following is the full test code as requested:

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using KellermanSoftware.CompareNetObjects;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    namespace CompareNETObjectsIssue181
    {
        class Program
        {
            static void Main(string[] args)
            {
                var libraryVersion = typeof(CompareLogic).Assembly.GetName().Version;
                Console.Out.WriteLine($"Using KellermanSoftware.CompareNETObjects v{libraryVersion}");

                try
                {
                    Console.Out.WriteLine("Creating test class.");
                    var testClass = new TestClass();
                    Console.Out.WriteLine("Calling test method.");
                    testClass.Subject_Validate_Valid();
                }
                catch (NullReferenceException ex)
                {
                    Console.Out.WriteLine("Regression encountered.");
                    Console.Out.WriteLine(ex.ToString());
                    return;
                }

                Console.Out.WriteLine("No regression. Expected behavior.");
            }
        }

        [TestClass]
        public class TestClass
        {
            [TestMethod]
            public void Subject_Validate_Valid()
            {
                // Arrange
                var subject = new object();
                var expected = new[] { ValidationResult.Success };

                // Act
                var actual = subject.Validate();

                // Assert
                var result = ObjectComparer.Compare(expected, actual);
                Assert.IsTrue(result.AreEqual, result.DifferencesString);
            }
        }  

        public static class ObjectComparer
        {
            public static ComparisonResult Compare(object expectedObject, object actualObject, IEnumerable<string> membersToIgnore = null, bool redactValues = false)
            {
                var config = new ComparisonConfig
                {
                    IgnoreCollectionOrder = true,
                    IgnoreObjectTypes = true,
                    MaxDifferences = 100
                };

                if (membersToIgnore != null)
                {
                    config.MembersToIgnore = new List<string>(membersToIgnore);
                }

                if (redactValues)
                {
                    config.DifferenceCallback = difference =>
                    {
                        difference.Object1Value = Constants.RedactedText;
                        difference.Object2Value = Constants.RedactedText;
                    };
                }

                var compare = new CompareLogic(config);
                var result = compare.Compare(expectedObject, actualObject);
                return result;
            }
        }

        public static class ValidationExtensions
        {
            public static IEnumerable<ValidationResult> Validate<T>(this T subject)
            {
                if (subject == null)
                    throw new ArgumentNullException(nameof(subject));

                var result = new List<ValidationResult>();
                var context = new ValidationContext(subject);

                if (Validator.TryValidateObject(subject, context, result, validateAllProperties: true))
                    return new[] { ValidationResult.Success };

                return result.AsReadOnly();
            }
        }

        public static class Constants
        {
            public const string RedactedText = "**redacted**";
        }
    }

The test solution I created is in Visual Studio 2019 as a .NET Core 3.0 console application.  Package references are as follows:

- CompareNETObjects (4.63.0)
- MSTest.TestFramework (2.0.0)

Technically, the MSTest.TestFramework is not needed to reproduce the issue, but I built the full test code that way because that's how I originally reported the issue above (as it was originally discovered in a unit test).  If that becomes confusing or gets in the way, please let me know, and I will rework the sample to pull that out.

Please let me know how else I can help.

Thanks!
Allen

**Comment by GregFinzer** [comment]
Thanks Allen.  I will look at this as soon as I can.

**Comment by aescharfenberg** [comment]
Thanks, Greg.  I really appreciate it!  If I can help with anything, please let me know.

**Comment by GregFinzer** [comment]
@aescharfenberg Sorry I could not figure out the issue using the provided code.  I checked in a new branch for you.  Please modify to get it to fail:
https://github.com/GregFinzer/Compare-Net-Objects/tree/AescharfenbergObjectReference

**Comment by GregFinzer** [comment]
@aescharfenberg Fixed.  Please get the source and try locally

**Comment by GregFinzer** [comment]
@aescharfenberg Did you try it out?

**Comment by aescharfenberg** [comment]
Greg, I apologize, I just now saw this.  The notification emails I received only contained your first comment after the code sample, so I thought they were duplicates.  I am working tomorrow morning on a system upgrade, and I will have time to try it out then.  I will let you know the results tomorrow.

Thank you so much for your help!

**Comment by aescharfenberg** [comment]
Greg, the latest from master worked great locally.  I also added a similar unit test as the one you created to check for this error going forward.  Looking forward to the next release with this fix in it.  Thank you for all your help!

**Comment by GregFinzer** [comment]
Released in V4.64
