### ISSUE TITLE
Eliminate possible recursion in Custom Comparer

### ISSUE THREAD

**Issue by jennilynhowell** [GregFinzer/Compare-Net-Objects#183]
Hello there,
I work with this library on a private project and it's been a huge help.

We are looking to apply custom compare logic only if certain attributes apply to the compared objects. Otherwise, we'd like to use the default compare functionality. Calling the base `RootComparer.Compare()` in this case results in recursion as the custom comparer gets called again.

Here's an example:

```
    public class CustomPetComparer : BaseTypeComparer
    {
        private readonly RootComparer _rootComparer;

        public CustomPetComparer(RootComparer rootComparer) : base(rootComparer)
        {
            _rootComparer = rootComparer;
        }

        public override bool IsTypeMatch(Type type1, Type type2)
        {
            return type1 == typeof(Pet);
        }

        public override void CompareType(CompareParms parameters)
        {
            var pet1 = (Pet) parameters.Object1;
            var pet2 = (Pet) parameters.Object2;

            if (pet2.TailWags > 5)
            {
                // create a custom difference
                AddDifference(parameters.Result, new Difference
                {
                    Object1 = parameters.Object1,
                    Object2 = null
                });
            }
            else
            {
                // process with default compare logic
                _rootComparer.Compare(parameters);
            }
        }
    }
```

I can work on a PR for this as time permits, but curious your thoughts. Thank you.

**Comment by GregFinzer** [comment]
@jennilynhowell The else portion is not needed.  Delete that code and you should be fine.

```
            else
            {
                // process with default compare logic
                _rootComparer.Compare(parameters);
            }
```

**Comment by jennilynhowell** [comment]
Hey Greg,
Thanks for taking a look.

Removing the `else` statement results in the objects being marked as equal. Calling `AddDifference(parameters);` resolves that, but only identifies the objects as not equal. 

The comparer is able to identify inequalities within objects of other types, and I'd like to have that same level of granularity within custom comparers (i.e. `Item Expected.Name != Actual.Name`). In other words, have the ability to define when the custom compare logic should and shouldn't be applied.

I added a [gist](https://gist.github.com/jennilynhowell/be42b1cb7b5f994d42457505989a2dd2) that may explain better. 

Appreciate your time!

**Comment by GregFinzer** [comment]
@jennilynhowell I am sorry but I am not understanding at all what you are requesting.  The Gist did not help.  I think it would be best if you simply implement IComparable since it seems this is a lot of custom logic.

**Comment by RedaAouad** [comment]
Hi @jennilynhowell 
I have exactly the same use case and problems as yours. Did you find a solution?

**Comment by jennilynhowell** [comment]
> Hi @jennilynhowell
> I have exactly the same use case and problems as yours. Did you find a solution?

Hey @RedaAouad -- Honestly can't remember what we were trying to solve, but I think we resolved it by implementing "pre-processing" that manipulates the objects (typically `List<object>`s in our case) to be compared in order to achieve the desired result.

So in the above example, we would determine before comparing that `pet2.TailWags > 5` and remove it from that `List<Pet> ListTwo`, so that it comes back as null in the comparison difference.

Hope that makes sense / helps. Happy coding!
