### ISSUE TITLE
Could not load file or assembly 'KellermanSoftware.Compare-NET-Objects

### ISSUE THREAD

**Issue by wuyanbing** [GregFinzer/Compare-Net-Objects#185]
My class library target netstandard 2.0, I add nuget package CompareNETObjects(4.63.0),but  CANNOT run it,below is the errors:
System.IO.FileNotFoundException:“Could not load file or assembly 'KellermanSoftware.Compare-NET-Objects, Version=4.63.0.0, Culture=neutral, PublicKeyToken=d970ace04cc85217'.

**Comment by GregFinzer** [comment]
What is happening most likely is that you have another .NET Framework assembly in your solution that is also referencing Compare .NET Objects that has a lower .NET Framework version than Compare .NET Objects.  Also check your build configuration x86 vs X64

**Comment by GregFinzer** [comment]
Closing inactive issue.
