### ISSUE TITLE
StringHelper.cs line 39 bug with dots and tabs

### ISSUE THREAD

**Issue by PTassou** [GregFinzer/Compare-Net-Objects#186]
static void Main(string[] args)
        {
            List<object> groundTruth = new List<object>();
            List<object> newResult = new List<object>();

            groundTruth.Add(new { boo = "hello", gg = "hello again" });
            groundTruth.Add(new { boo = "scorpio \t. .\r\n11-nov", gg = "hello again2" });
            newResult.Add(new { boo = "hello", gg = "hello again" });
            newResult.Add(new { boo = "  .....  ", gg = "hello again2" });

            CompareLogic compareLogicObject = new CompareLogic();
            compareLogicObject.Config.MaxDifferences = int.MaxValue;
            compareLogicObject.Config.IgnoreCollectionOrder = true;

            ComparisonResult assertionResult = compareLogicObject.Compare(groundTruth, newResult);

            Console.WriteLine(assertionResult.DifferencesString + "\n\n\n");

            UserFriendlyReport friendlyReport = new UserFriendlyReport();

            Console.WriteLine(friendlyReport.OutputString(assertionResult.Differences));

            Console.ReadLine();
        }

**Comment by GregFinzer** [comment]
It will be a while until I look at this.

**Comment by GregFinzer** [comment]
Fixed.

**Comment by GregFinzer** [comment]
Released in v4.65
