### ISSUE TITLE
Support for nullable Enum-Properties

### ISSUE THREAD

**Issue by raphaelSch** [GregFinzer/Compare-Net-Objects#189]
When comparing an object with a nullable enum property and set CompareChildren to false differences in these properties are not detected.

The TypeHelper.CanHaveChildren() - Method returns true.
I think the method IsSimpleType() should handle nullable enums as well

**Comment by GregFinzer** [comment]
Thanks for reporting this defect.  It will be a while until I can get to this.

**Comment by raphaelSch** [comment]
Let me know if I can support you in some way.

**Comment by GregFinzer** [comment]
If you would like to create a PR with a test to fix it that would speed up the process.

**Comment by raphaelSch** [comment]
Ok, I've created a PR.

**Comment by GregFinzer** [comment]
Merged thanks so much!

**Comment by raphaelSch** [comment]
Thank you!! :)

**Comment by raphaelSch** [comment]
Just one question: Do you also publish a new nuget package?

**Comment by GregFinzer** [comment]
There is one more Issue remaining before I publish

**Comment by GregFinzer** [comment]
Released in v4.65
