### ISSUE TITLE
Cannot compare collections with items of different types

### ISSUE THREAD

**Issue by IgorVyatkin** [GregFinzer/Compare-Net-Objects#19]
The library doesn't work correctly in case when you compare lists with items of different types. You are getting an exception like the following:

```
System.Exception : Invalid CollectionMatchingSpec.  No such property XXXXProperty for type YYYYYClass 
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.GetMatchIndex(ComparisonResult result, List`1 spec, Object currentObject)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareInOrder(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareInOrder(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object object1, Object object2)
```

If you set `IgnoreCollectionOrder = true` it works better but in some situations you also receive the exception below.

**Comment by GregFinzer** [comment]
Igor,

Please create a fix and I will merge in the code.

Thanks,
Greg

**Comment by dgauerke** [comment]
I found a similar issue, but not sure if it is related to this one.  The GetMatchIndex in IgnoreOrderLogic does not take into consideration the IgnoreObjectTypes in the config.  By adding a parameter to the function definition (I'm only passing in the IgnoreObjectTypes, but you may want to pass the whole parms or config object), I am able to compare two lists of similar objects with different types.

The call will look something like this:
string matchIndex1 = GetMatchIndex(parms.Result, matchingSpec, enumerator1.Current, parms.Config.IgnoreObjectTypes);

And then just before the return in the function:

            if (sb.Length == 0)
                if (ignoreType)
                    sb.Append(currentObject.GetType().Name);
                else
                    sb.Append(currentObject);

            return sb.ToString().TrimEnd(',');

**Comment by GregFinzer** [comment]
You will need to specify a collection matching spec for both types:

        [Test]
        public void CompareListsIgnoreOrderTwoDifferentTypes()
        {
            List<Person> list1 = new List<Person>();
            list1.Add(new Person() {ID = 1, Name = "Logan 5"});
            list1.Add(new Person() { ID = 2, Name = "Francis 7" });

            List<Officer> list2 = new List<Officer>();
            list2.Add(new Officer() { ID = 2, Name = "Francis 7" });
            list2.Add(new Officer() { ID = 1, Name = "Logan 5" });

            ComparisonConfig config = new ComparisonConfig();
            Dictionary<Type, IEnumerable<string>> collectionSpec = new Dictionary<Type, IEnumerable<string>>();
            collectionSpec.Add(typeof(Person), new string[] { "ID" });
            collectionSpec.Add(typeof(Officer), new string[] { "ID" });

            config.IgnoreObjectTypes = true;
            config.IgnoreCollectionOrder = true;
            config.CollectionMatchingSpec = collectionSpec;

            CompareLogic compareLogic = new CompareLogic(config);
            var result = compareLogic.Compare(list1, list2);
            Assert.IsTrue(result.AreEqual);
        }

**Comment by PalashBansal** [comment]
Hi @GregFinzer 
Sry for commenting in closed issue and Thanks for example of CollectionMatchingSpec.
I am comparing 2 xml's converting into objects with following hierarchy-
```
<mainParent>
   <uniquee>
      <parameter1>
         <Name>Palash</Name>
         <Value>180</Value>
      </parameter1>
      <parameter1>
         <Name>Adi</Name>
         <Value>104</Value>
      </parameter1>
   </uniquee>
   <orderX>6</orderX>
   <orderY>0</orderY>
   <dummy1>
      <dummy2>
         <someData>40a20686bcc82</someData>
         <dummy3 />
      </dummy2>
   </dummy1>
   <data1>
      <data2>
         <aa>abc</aa>
         <bb>def</bb>
         <cc>ghi</cc>
         <dd>jkl</dd>
      </data2>
      <data2>
         <aa>fgbb</aa>
         <bb>sc</bb>
         <cc>fgb</cc>
         <dd>mhg</dd>
      </data2>
      <data2>
         <aa>dwc</aa>
         <bb>dcz</bb>
         <cc>rtb</cc>
         <dd>scs</dd>
      </data2>
   </data1>
</mainParent>
<mainParent>
   <uniquee>
      <parameter1>
         <Name>Yaron</Name>
         <Value>180</Value>
      </parameter1>
      <parameter1>
         <Name>Efim</Name>
         <Value>204</Value>
      </parameter1>
   </uniquee>
   <orderX>6</orderX>
   <orderY>0</orderY>
   <dummy1>
      <dummy2>
         <someData>40a20686bcc82</someData>
         <dummy3 />
      </dummy2>
   </dummy1>
   <data1>
      <data2>
         <aa>ascbc</aa>
         <bb>dscef</bb>
         <cc>gschi</cc>
         <dd>jkscl</dd>
      </data2>
      <data2>
         <aa>fgscbb</aa>
         <bb>sdcsc</bb>
         <cc>fgcsdb</cc>
         <dd>mhscg</dd>
      </data2>
      <data2>
         <aa>dwscsc</aa>
         <bb>dscsdcz</bb>
         <cc>rsctb</cc>
         <dd>sccsdcs</dd>
      </data2>
   </data1>
</mainParent>
```
(Please use Notepad++ with xml language set for better readability.)
I want to specify             `collectionSpec.Add(typeof(mainParent), new string[] { "uniquee" });`
as the multiple values inside `<uniquee>` determines the key for me uniquely. For above example, unique key can be _Palash180Adi104_ and _Yaron180Efim204_

But _IgnoreOrderLogic.cs_ is not able to read inside parameter1 and making matchingIndex as **mainParent.uniquee.parameter1[]** empty array, eventually considering all set of mainParent as same type even though data in all are different. Note that **uniquee** is the only entity i have which is unique.

Other configs I am keeping-
SkipInvalidIndexers = true,
IgnoreCollectionOrder = true,

Can you please suggest what I can replace `collectionSpec.Add(typeof(mainParent), new string[] { "uniquee" });` with?

**Comment by GregFinzer** [comment]
@PalashBansal Sorry the Compare .NET Object Library is not going to work for something like this.  You will need to write your own comparison code.
