### ISSUE TITLE
Change License from Ms-PL to MIT

### ISSUE THREAD

**Issue by voneinem** [GregFinzer/Compare-Net-Objects#193]
Ms-PL unfortunately has some legally unclear aspects.
Would it be possible to move to MIT license instead?

**Comment by GregFinzer** [comment]
It will be a long time until I can look at this.

**Comment by voneinem** [comment]
Thanks a lot for the quick reply.
I guess that you've used Ms-PL because it was the standard license MS used long time ago.
Today MS uses mainly MIT.
I hope it's an easy change for you.

**Comment by GregFinzer** [comment]
@voneinem Sorry no, I am sticking with the Ms-PL
