### ISSUE TITLE
Ignoring List's Order not work for Complex-Object

### ISSUE THREAD

**Issue by lanluu** [GregFinzer/Compare-Net-Objects#194]
Hi,

As far as we could test, we could only ignore the Order of List's Items if Item is Simple Type.

In case Item is Complex-Object, the Ignoring Setting would not work at all.

Could you please help us in this case? Any feedback is precious!

Best regards
Lan

**Comment by GregFinzer** [comment]
Please read the documentation:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths
