### ISSUE TITLE
Reopen https://github.com/GregFinzer/Compare-Net-Objects/issues/194

### ISSUE THREAD

**Issue by lanluu** [GregFinzer/Compare-Net-Objects#195]
Hi, thank you for your feedback at Issue #194. We had read your mentioned document, and applied but it did not help us in our context. We try to describe the issue now with more information:

- The whole issue is related to the comparisson of generic list-objects in combination with usage of the config option "IgnoreCollectionOrder".
- If config option "IgnoreCollectionOrder" is set to "true", only object properties get compared but no fields. If the option is set to "false" fields are compared as expected.
- Furthermore changes in objects won't be detected when objects don't have properties of primitive type. In our case we sometimes have simple container objects which have only properties which contain further complex objects, without any primitive property (e. g. Id). As soon as complex objects contain an primitive property all changes are detected by the library as expected.
- For your understanding, we have prepared a small unit-test solution source code (given as attachment) so that you can try and see our current problems via the two failed tests which you can quickly find in the below screenshot.

We thank you so much for your efforts and supports!

Best regards
Lan

![image](https://user-images.githubusercontent.com/3998945/72628352-6c929700-394e-11ea-88ac-f603519ffa69.png)
[NetObjectsTest.zip](https://github.com/GregFinzer/Compare-Net-Objects/files/4077711/NetObjectsTest.zip)

**Comment by GregFinzer** [comment]
Thank you for providing the failing unit tests.  It will be a while until I can get to this.

**Comment by GregFinzer** [comment]
@lanluu Sorry Compare .NET Objects Ignoring the Order with classes that use fields as identifiers.  You will need to implement this feature.  Let me know when you have implemented the feature and I will merge in your pull request.
