### ISSUE TITLE
Output looks wrong when using IgnoreCollectionOrder

### ISSUE THREAD

**Issue by timrobinson33** [GregFinzer/Compare-Net-Objects#197]
```
var compareLogic = new CompareLogic();
compareLogic.Config.IgnoreCollectionOrder = true;
ComparisonResult result = compareLogic.Compare(new[] { "one" }, new[] { "two" });
Console.WriteLine(result.DifferencesString);
```
prints this output:
```
Types [String,null], Item Expected[one].Item != Actual[one].Item, Values (one,(null))
```
I'm not entirely sure what it's supposed to mean but it definitely seems to have printed "one" as both the expected and actual. Without the `IgnoreCollectionOrder` it prints
```
Types [String,String], Item Expected[0] != Actual[0], Values (one,two)
```
which seems fine.

I'm using the latest version 4.66.0

**Comment by gfinzerScotts** [comment]
@timrobinson33 It is working as expected.  The reason why the one appears as an id in both the Expect and the Actual is because it is.  It makes more sense if you set the MaxDifferences to a higher value:

```
        [Test]
        public void SimpleArrayTest()
        {
            var compareLogic = new CompareLogic();
            compareLogic.Config.IgnoreCollectionOrder = true;
            compareLogic.Config.MaxDifferences = Int32.MaxValue;
            ComparisonResult result = compareLogic.Compare(new[] { "one" }, new[] { "two" });
            Console.WriteLine(result.DifferencesString);
        }
```

This will yield the result:

Begin Differences (2 differences):
Types [String,null], Item Expected[one].Item != Actual[one].Item, Values (one,(null))
Types [null,String], Item Expected[two].Item != Actual[two].Item, Values ((null),two)
End Differences (Maximum of 2147483647 differences shown).

**Comment by timrobinson33** [comment]
Thanks. I still find the output difficult to interpret but I guess it's because it's using the object as a key to index a dictionary or some such.

**Comment by GregFinzer** [comment]
Sorry I am not sure what better format there could be.

**Comment by timrobinson33** [comment]
Yes, after thinking about it a bit more, I see the problem more clearly. If the lists aren't sorted, you can't tell the difference between "item X was is different in the 2 lists" and "item X was deleted and item Y was inserted".

To me that difference is obvious because each item in the list has a "key", so if there is an item in both lists with the same key, I know it's the "same" item even if there are differences, but you don't know what the key is.

So a workaround for me is to simply sort by my key and then set `IgnoreCollectionOrder = false`
