### ISSUE TITLE
IgnoreCollectionOrder is broken

### ISSUE THREAD

**Issue by Onzi12** [GregFinzer/Compare-Net-Objects#198]
Hi guys,
I'm not sure I'm using it right, but it seems that the IgnoreCollectionOrder doesn't work.
I'm using the latest version (I've also tried lower versions).

```C#
public void CheckIgnoreCollectionOrder()
        {
            var config = new ComparisonConfig { IgnoreCollectionOrder = true };
            var compareLogic = new CompareLogic(config);

            var actual = new Foo[] { new Foo(2), new Foo(1) };
            var expected = new Foo[] { new Foo(1), new Foo(2) };

            var result = compareLogic.Compare(expected, actual);

            Assert.IsTrue(result.AreEqual);
        }

        public class Foo
        {
            public int Prop { get; }

            public Foo(int prop)
            {
                this.Prop = prop;
            }
        }
```

**Comment by dominiquesamson** [comment]
Hi, I think that your problem lies in the fact that your property doesn't have a setter, just add set; to Prop and your example should work.

The secret seems to be in IgnoreOrderLogic.cs at line 281, where it says that a property must have "CanWrite" to true to be elligible to compose the key.

Another solution could be to set up a specific key for your object, as in there:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths

I'm not sure if which properties are elligible to compose the fallback key is missing in the documentation or is an actual bug.

Hope this help!

**Comment by GregFinzer** [comment]
@Onzi12 Put on a CollectionMatching Spec:

```
        [Test]
        public void CheckIgnoreCollectionOrder()
        {
            Dictionary<Type, IEnumerable<string>> collectionSpec = new Dictionary<Type, IEnumerable<string>>();
            collectionSpec.Add(typeof(Foo), new string[] { "Prop" });

            var config = new ComparisonConfig { IgnoreCollectionOrder = true, CollectionMatchingSpec = collectionSpec };
            var compareLogic = new CompareLogic(config);

            var actual = new Foo[] { new Foo(2), new Foo(1) };
            var expected = new Foo[] { new Foo(1), new Foo(2) };


            var result = compareLogic.Compare(expected, actual);
            Console.WriteLine(result.DifferencesString);
            Assert.IsTrue(result.AreEqual);
        }
```

**Comment by Onzi12** [comment]
Hi Greg,
Thanks for your quick reply!

The CollectionMatching solution is not so maintainable\scalable\user-friendly, as it removes the abstraction from the object under test - which is the main reason I use the framework.

Is there a C#\.NET limitation that prevents it from being comfortable as standard objects comparison?

By the way, the IgnoreCollectionOrder worked out of the box in early versions (really early, somewhere between v1-v2)

Regards,
On Albilia.

**Comment by GregFinzer** [comment]
It is a design choice to ignore properties without setters.  My thinking is that get only properties are calculated fields that should not be compared.  I have also had a bad experience with poorly implemented getters at companies.  If you wish to create an option to compare get only properties, please create a config option, the implementation, and tests with your pull request.
