### ISSUE TITLE
DataTableComparer does not compare column names

### ISSUE THREAD

**Issue by IainBapty** [GregFinzer/Compare-Net-Objects#20]
The current implementation of DataTableComparer only verifies that the column counts are the same between the data sets being compared. Comparing the column names would be a useful addition.

**Comment by GregFinzer** [comment]
Iain,

That is a great idea.  Please implement and I will merge in.  Please create NUnit tests to verify the functionality.

Thanks,
Greg

**Comment by IainBapty** [comment]
#21 submitted

**Comment by GregFinzer** [comment]
Merged
