### ISSUE TITLE
Comparing nesting objects

### ISSUE THREAD

**Issue by NexQueek** [GregFinzer/Compare-Net-Objects#200]
Hey,

I have a problem with inner objects. 
If one of the nested object is null and the newvalue isnt. The difference shows just the Object name and not the properties. 
Here a little example 
https://gist.github.com/NexQueek/34140ea0eadb59d1170bf462c0a0f951
And the difference shows that there is the object city but not the properties within

I have alot of nested Objects and sometimes they are null,
so the question is did i do anything wrong or does your comparison doest look into these nested object if one of them is null

Kind regards

**Comment by gfinzerScotts** [comment]
@NexQueek If an object is null it does not display the properties of the other object.  If you would like to add that as a new feature, please make a property in the ComparisonConfig called DisplayPropertiesWhenNull with a default of false.  Please also create unit tests.

**Comment by GregFinzer** [comment]
@NexQueek Do you have an ETA on the fix.  There is another developer @MatimalND that would like a build to NuGet.

**Comment by NexQueek** [comment]
Hi, i think its to difficult for me to create this feeature.

**Comment by GregFinzer** [comment]
Ok, no problem.  I will close this feature request then.
