### ISSUE TITLE
Ignored Member Get Property Accessed.

### ISSUE THREAD

**Issue by MatimalND** [GregFinzer/Compare-Net-Objects#201]
Trying to upgrade from 3.3 to 4.66 but my get the always throws an error is getting accessed even though I am excluding it.  This use to work in 3.3
Below is some code to test.  FYI, I tested all versions and it worked until 3.10.0
using System;
using KellermanSoftware.CompareNetObjects;

namespace ConsoleApp2
{
	class Program
	{
		static void Main(string[] args)
		{
			//This is the comparison class
			CompareLogic compareLogic = new CompareLogic();
			compareLogic.Config.MembersToIgnore.Add("Person.Name");
			// compareLogic.Config.MembersToIgnore.Add("Name");
			// compareLogic.Config.MembersToIgnore.Add("*Name");

			//Create a couple objects to compare
			Person person1 = new Person();
			person1.DateCreated = DateTime.Now;
			//person1.Name = "Greg";

			Person person2 = new Person();
			// person2.Name = "John";
			person2.DateCreated = person1.DateCreated;
			ComparisonResult result = compareLogic.Compare(person1, person2);

			//These will be different, write out the differences
			if (!result.AreEqual)
				Console.WriteLine(result.DifferencesString);
		}

	}

	internal class Person
	{
		public DateTime DateCreated { get; internal set; }
		public string Name
		{
			get
			{
				throw new NotImplementedException("Name should be ignored but this exception is thrown.");
			}
		}
	}
}

**Comment by GregFinzer** [comment]
@MatimalND I am not able to reproduce with the current version.  Here is my passing test:

        [Test]
        public void IgnoredMemberGetPropertyAccessed()
        {
            //This is the comparison class
            CompareLogic compareLogic = new CompareLogic();
            compareLogic.Config.MembersToIgnore.Add("Person.Name");

            //Create a couple objects to compare
            PersonWithNotImplementedProperty person1 = new PersonWithNotImplementedProperty();
            person1.DateCreated = DateTime.Now;

            PersonWithNotImplementedProperty person2 = new PersonWithNotImplementedProperty();
            person2.DateCreated = person1.DateCreated;
            ComparisonResult result = compareLogic.Compare(person1, person2);

            Assert.IsTrue(result.AreEqual);
        }

**Comment by MatimalND** [comment]
The class for the PersonWithNotImplementedProperty is missing in your example.  Also are you trying in Debug mode?  The code checking the properties is in a Try/Catch that will continue, but every time the property is accessed it's a big hit on performance having to catch the System.Reflection.TargetInvocationException.

Snippet from PropertyComparer.cs-> AddPropertyInfos.
                if (propertyEntity.CanRead && (propertyEntity.Indexers.Count == 0))
                {
                    try
                    {
                        propertyEntity.Value = property.GetValue(objectValue, null);
                    }
                    catch (System.Reflection.TargetInvocationException)
                    {
                    }

**Comment by GregFinzer** [comment]
Fixed.

**Comment by MatimalND** [comment]
Thank you Greg for the quick turn around!

**Comment by MatimalND** [comment]
When would this be updated in the NuGet package?

**Comment by GregFinzer** [comment]
Normally I do releases with at least three defect fixes or three features implemented.  There are two other issues that I am waiting to be completed by the two assigned developers.  One defect and one enhancement.  I will ask them when their work will be done.

**Comment by MatimalND** [comment]
Thank you so much for the quick responses. I know another developer had
issues when trying to update and just went back to 3.3 I will see what his
was and if reproducible in simple example.

**Comment by GregFinzer** [comment]
Released in Version 4.67 on NuGet
