### ISSUE TITLE
SaveConfiguration serialization of type causes exception

### ISSUE THREAD

**Issue by martincw2** [GregFinzer/Compare-Net-Objects#204]
To demonstrate the issue, I copied the SaveConfigurationTest in KellermanSoftware.CompareNetObjectsIntegrationTests.  I added a single line `_compare.Config.TypesToIgnore.Add(typeof(Guid));` before saving the configuration
which causes it to throw the error below.

> System.Runtime.Serialization.SerializationException
>   HResult=0x8013150C
>   Message=Type 'System.RuntimeType' with data contract name 'RuntimeType:http://schemas.datacontract.org/2004/07/System' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.
>   Source=System.Runtime.Serialization

As expected, `_compare.Config.TypesToInclude.Add(typeof(Guid));` or` _compare.Config.ClassTypesToIgnore.Add(typeof(FileInfo));` cause the same issue.

**Comment by GregFinzer** [comment]
Ok.  Thanks for reporting this issue.

**Comment by GregFinzer** [comment]
Fixed
