### ISSUE TITLE
[Question] any idea if code changes may be required for this library to support c# 9 record type and .net 5?

### ISSUE THREAD

**Issue by githubfanster** [GregFinzer/Compare-Net-Objects#206]
[Question] any idea if code changes may be required for this library to support c# 9 record type and .net 5?

we're planning to move to .net 5 asap and make use of the new c# 9 record type, so just wanted to know.

thanks!

**Comment by GregFinzer** [comment]
I am not sure what the record type is in C# 9.  It is quite possible that it may require changes.  There were code changes required to support DataSet, DataTable, DataRow, DataColumn, LinearGradient, URI, IPEndPoint.  I would try it out.  If it does not work, implement the changes and a unit test and do a pull request.
