### ISSUE TITLE
Is there a way to compare only properties that have a given attribute?

### ISSUE THREAD

**Issue by igorocampos** [GregFinzer/Compare-Net-Objects#207]
First of all, great work! 
I was looking at the Get started page and couldn't find a way to compare only properties that have an attribute.

I know you can do the opposite: ignore all properties that have an attribute, but how about ignore all that don't have it?

Thanks,
Igor

**Comment by GregFinzer** [comment]
Igor,

No it currently does not support that feature.  Feel free to implement the feature with unit tests and create a pull request.  

Thanks,
Greg

**Comment by igorocampos** [comment]
Got it, I'll try then, if time allows me :)

**Comment by igorocampos** [comment]
@GregFinzer it was not difficult at all to implement. Please review #208 and let me know if it needs any modifications

**Comment by GregFinzer** [comment]
Also updated the Wiki here:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Ignoring-Members

**Comment by GregFinzer** [comment]
Released in Version 4.67 on NuGet
