### ISSUE TITLE
Custom comparer on top of built-in comparer

### ISSUE THREAD

**Issue by RedaAouad** [GregFinzer/Compare-Net-Objects#209]
Hi,

I am comparing lists (of complex objects) which don't have the same order and may be of different length. So I'm using `IgnoreCollectionOrder = true` and setting comparison key in `CollectionMatchingSpec`.

Comparing the following lists returns `true`:

```
List1
|__ Item1
|__ Item2

List 2
|__ Item1
|__ Item2
|__ Item2
```

(yes, `Item2` is duplicated in `List2`).

For my purposes I'd like to return `false`. How is it possible to do that while keeping the built-in comparer that compares the complex inner objects?

I tried to implement a custom comparer to check for list lengths, but it seems to run instead of the built-in comparer, so only the length is checked as a result for the comparison.

**Comment by GregFinzer** [comment]
I would call this a defect.  If it finds all the items but the length is different it should return false.

**Comment by GregFinzer** [comment]
Fixed
