### ISSUE TITLE
If IgnoreCollectionOrder is true then it does not consider 'AttributesToIgnore' while matching list of a item

### ISSUE THREAD

**Issue by mahendra25aug** [GregFinzer/Compare-Net-Objects#211]
If IgnoreCollectionOrder is true then it does not consider 'AttributesToIgnore' while matching list of a item

**Comment by GregFinzer** [comment]
Thank you for reporting this issue.

**Comment by GregFinzer** [comment]
Please create a fix with a unit test.

**Comment by mahendra25aug** [comment]
@GregFinzer ...I am getting while pushing the changes

"Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

I think I don't have access.

**Comment by GregFinzer** [comment]
Please create a pull request.

**Comment by mahendra25aug** [comment]
I am not able to push the branch

**Comment by GregFinzer** [comment]
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by mahendra25aug** [comment]
Do I have write access?

**Comment by mahendra25aug** [comment]
I always get 'Permission to GregFinzer/Compare-Net-Objects.git denied to mahendra25aug', whenever I try to push a branch

**Comment by GregFinzer** [comment]
@mahendra25aug I am not giving you write access to check directly into the master branch.  You will need to create a pull request.  Everyone in the world has access to create a pull request.

**Comment by mahendra25aug** [comment]
To create a PR, I need to push a branch...but when I push a newly created branch , I get 'Permission to GregFinzer/Compare-Net-Objects.git denied to mahendra25aug'. I am not sure what I am doing wrong here.

Is there a way to create a PR without pushing the branch?
