### ISSUE TITLE
Comparing dictionaries return two differences for same key

### ISSUE THREAD

**Issue by fubar-coder** [GregFinzer/Compare-Net-Objects#214]
I have an object with a dictionary. When I compare both objects, the entry "a" is shown twice.

Example code:

```csharp
var oldDoc = new TestDoc()
{
	Fields =
	{
		["a"] = 1,
		["b"] = 2,
	},
};

var newDoc = new TestDoc()
{
	Fields =
	{
		["a"] = 3,
		["c"] = "asd",
	},
};

var cl = new CompareLogic()
{
	Config =
	{
		MaxDifferences = int.MaxValue,
	},
};

var cr = cl.Compare(newDoc, oldDoc);

// Shows four differences: a/a, b/null, a/a, null/c
cr.DifferencesString.Dump();

class TestDoc
{
	public IDictionary<string, object?> Fields {get;} = new Dictionary<string, object?>();
}
```

The differences shown are:

```text

Begin Differences (4 differences):
Types [Int32,Int32], Item Expected.Fields[a].Value != Actual.Fields[a].Value, Values (3,1)
Types [String,null], Item Expected.Fields[c].Value != Actual.Fields[c].Value, Values (asd,(null))
Types [Int32,Int32], Item Expected.Fields[a].Value != Actual.Fields[a].Value, Values (3,1)
Types [null,Int32], Item Expected.Fields[b].Value != Actual.Fields[b].Value, Values ((null),2)
End Differences (Maximum of 2147483647 differences shown).
```

I did expect that the line `Types [Int32,Int32], Item Expected.Fields[a].Value != Actual.Fields[a].Value, Values (3,1)` gets shown only once.

What is the expected behavior and is there a way to return only distinct changes?

**Comment by GregFinzer** [comment]
@fubar-coder it does not support the object data type.  You will need to create your comparer.

**Comment by fubar-coder** [comment]
@GregFinzer Can you please explain it a little bit? Because I see that the library can find differences, but it just shows a single difference twice, which is somewhat confusing, because there is only **one** entry with the given key `a`.

I'll try to rephrase my question: Why are there two entries for the key `a`? Even when the values cannot be compared, the keys **can** be compared and are shown. I just expect the change to be shown only once.

BTW: Please reopen the issue, because the problem also exists with `Dictionary<int, int>`.

New example:

```csharp
var oldDoc = new TestDoc()
{
	Fields =
	{
		["a"] = 1,
		["b"] = 2,
	},
};

var newDoc = new TestDoc()
{
	Fields =
	{
		["a"] = 3,
		["c"] = 5
	},
};

var cl = new CompareLogic()
{
	Config =
	{
		MaxDifferences = int.MaxValue,
	},
};

var cr = cl.Compare(newDoc, oldDoc);

// Shows four differences: a/a, c/null, a/a, null/b
cr.DifferencesString.Dump();

class TestDoc
{
	public IDictionary<string, int> Fields { get; } = new Dictionary<string, int>();
}
```

**Comment by GregFinzer** [comment]
I have no idea why it would be doing that.  Feel free to fix it.

**Comment by GregFinzer** [comment]
Fixed
