### ISSUE TITLE
Test Extensions like ShouldCompare should take Optional Config

### ISSUE THREAD

**Issue by drdamour** [GregFinzer/Compare-Net-Objects#215]
in some of my concurrent tests it becomes problematic to use the same Config instance over and over, it'd be better if i could pass in an instance of Config to ShouldCompare as an optional param defaulting to the static param...course the shared CompareLogic is also problematic and would need to take an instance of Config passed in the chain too, or some other way to support the concurrent running environment

**Comment by GregFinzer** [comment]
That is a great idea.  Please implement.

**Comment by drdamour** [comment]
@GregFinzer ok but how do you suggest going about the shared CompareLogic, is newing one up for each invoke acceptible?

**Comment by GregFinzer** [comment]
That would be fine.

**Comment by GregFinzer** [comment]
Released:  https://www.nuget.org/packages/CompareNETObjects/4.68.0
