### ISSUE TITLE
[Question] Are there any plans to support .NET 5.0?

### ISSUE THREAD

**Issue by Torsteinws** [GregFinzer/Compare-Net-Objects#217]
This library is so awesome, and it would be nice to be able to use it in .NET 5.0 projects.

**Comment by GregFinzer** [comment]
What needs to be done so that it works with .NET 5?  There is already a .NET Standard 2.0 version and a 4.7.2 build.  Those can't be used?

**Comment by GregFinzer** [comment]
After some research it seems I need to do a .NET Standard 2.1 build in order to support .NET 5.  
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by GregFinzer** [comment]
Implemented

**Comment by Torsteinws** [comment]
Works perfectly! Thank you so much!

**Comment by GregFinzer** [comment]
You are welcome.  Good luck with your project.

**Comment by Hawxy** [comment]
Just a note that .NET Standard versions are additive and therefore forwards-compatible, as with .NET Framework and .NET Core versions. The current massive list of targets this package has could be consolidated to `net40;net45;netstandard2.0` and still retain the exact same support matrix. No change was required to support .NET 5 as it can consume any library targeting `.NET Standard` or `.NET Core` 1.0 or higher.
