### ISSUE TITLE
Comparing a collection of a ComplexType with just ComplexType properties return no differences when IgnoreCollectionOrder is used.

### ISSUE THREAD

**Issue by mmoroni** [GregFinzer/Compare-Net-Objects#218]
Hi Greg

I think I found a bug where it returns that two lists of a complex type are equal, even though they have differences, when they are compared using IgnoreCollectionOrder set to true.

It fails because it tries to create a key using the properties of the complex type, but since all properties are also complex types, it can't generate one and then it treats all as duplicates.

```c#
[Test]
public void IgnoreOrderListOfComplexTypeWithNestedComplexType()
{
    CompareLogic compareLogic = new CompareLogic();
    compareLogic.Config.IgnoreCollectionOrder = true;

    var obj1 = new List<ComplexType> {
        new ComplexType {Item = new Item {Value = "20"}},
        new ComplexType {Item = new Item {Value = "21"}}
    };
    var obj2 = new List<ComplexType>
    {
        new ComplexType {Item = new Item {Value = "20"}},
        new ComplexType {Item = new Item {Value = "20"}}
    };
    
    var result = compareLogic.Compare(obj1, obj2);
    Console.WriteLine(result.DifferencesString);
    Assert.IsFalse(result.AreEqual);
}

public class ComplexType 
{
    public Item Item { get; set; }
}

public class Item
{
    public string Value { get; set; }
}
```

**Comment by GregFinzer** [comment]
This is a known limitation. 
https://github.com/GregFinzer/Compare-Net-Objects

You will need to add a primitive type to your complex type.  For best performance define a collection matching spec.
