### ISSUE TITLE
Include/Exclude optimization suggestion

### ISSUE THREAD

**Issue by adaskos** [GregFinzer/Compare-Net-Objects#221]
Going through `ComparisonConfig` and `ExcludeLogic`, it seems like you could improve comparison performance by using a `HashSet` instead of a `List` for both `MembersToInclude` and `MembersToIgnore`. Then all calls to `Contains()` will be O(1) instead of O(n). The effect is more apparent as properties and included/ignored members increase.

**Comment by GregFinzer** [comment]
That is a great idea thanks.

**Comment by GregFinzer** [comment]
Implemented.  Internal type is now a hash set.
