### ISSUE TITLE
Failed comparison of objects with complex dictionary property

### ISSUE THREAD

**Issue by Vasar007** [GregFinzer/Compare-Net-Objects#222]
Hello!

I tried to use this awesome library to compare complex object with dictionary of dictionaries (yeah, that's weird but I need such objects for my internal tests).

At the moment, I'm using manual comparison, which leads to a lot of code writing. So, I decided to replace this code with your library. Almost all looks fine but there is one case wheach leads to strange error.

I created minimal gist with example [here](https://gist.github.com/Vasar007/6e2aa1f3a2744431047e95fd9f4feb7a).

Library version: `4.72.0`

```txt
Begin Differences (1 differences):

Types [Dictionary`2,null], Item 
Expected.DicOfDics[System.Collections.Generic.Dictionary`2[System.Int16,System.Int32]].Value.Count !=
Actual.DicOfDics[System.Collections.Generic.Dictionary`2[System.Int16,System.Int32]].Value.Count, Values (2,0)

End Differences (Maximum of 1 differences shown).
```

So, it looks like library tries to compare different items (not the same one in dictionary, e.g. `pair1` is compared with `pair2` in dictionary). If dictionary contains only one item, everything is fine. However, two or more items library returns invalid result that objects are not equal. At the same time, manual comparison does not find any issues.

P.S. I found some issues for dictionary in this repository and tried to decrease version of package. On version `4.63.0` my code from example works without any issues. Any newer version produces the error I described above. It seems that something was broken in update `4.64.0` in dictionary comparison logic.

**Comment by GregFinzer** [comment]
Thanks for reporting this issue and for the example.

**Comment by GregFinzer** [comment]
I tried pasting the GenericCollections class into the test project.  It will not compile.  Please fix the Gist to work with the test project.

**Comment by Vasar007** [comment]
Yeah, sorry. I copied and made some changes in the code. Fixed.

**Comment by GregFinzer** [comment]
Fixed.  Let me know how it works for you.

**Comment by Vasar007** [comment]
I checked latest master version. It works, thanks a lot!
