### ISSUE TITLE
Compare string to null

### ISSUE THREAD

**Issue by kuba13666** [GregFinzer/Compare-Net-Objects#225]
https://github.com/GregFinzer/Compare-Net-Objects/blob/20ca55d9b804ee0a1692fca63470111cbc3aad7e/Compare-NET-Objects/Difference.cs#L200

**Comment by kuba13666** [comment]
i believe this line causes an issue when new value of object(Object2Value) is null, when you change string walue to null you get the difference as following- "someOldString", "(null)" insted of just null or "".

**Comment by GregFinzer** [comment]
This is intentional.  The differences formatter outputs (null) for null values so you can see null vs an empty string.  If you need the original values take a look at Object1 and Object2

`               [Test]
        public void CompareStringAndNull()
        {
            CompareLogic compareLogic = new CompareLogic();
            var result = compareLogic.Compare("someOldString", null);
            Console.WriteLine(result.DifferencesString);

            Assert.AreEqual("someOldString", result.Differences[0].Object1);
            Assert.AreEqual(null, result.Differences[0].Object2);
        }`
