### ISSUE TITLE
Have CompareResult compare AND contrast

### ISSUE THREAD

**Issue by drdamour** [GregFinzer/Compare-Net-Objects#226]
currently CompareResult only really contrasts as it only tracks differences ..though of course compare has grown to mean both in common language...regardless...

I would find it rather useful to have all the individual comparisons & contrasts tracked and collected into the CompareResult type and have Differences just be a "view" into the overall collection which would include type Similar which would probably derive from some type, like Comparison.  So we'd have a IEnumerable<Comparison> Comparisons IEnumerable<Similarity> Similarities IEnumerable<Difference> Differences

additionally could use Config to determine to track Similarities or not

thus all the reports could be generated from the ComparisonResult directly and not need the expected to be passed

u open to such a changeset?

**Comment by GregFinzer** [comment]
@drdamour What would be the use case for this?  Normally when I want to see similarities and differences I would just output both objects to JSON and then compare.

**Comment by drdamour** [comment]
Build compare/contrast reports of biz entities

**Comment by GregFinzer** [comment]
I can't see any usefulness in that.  Please fork the project to your own needs.

**Comment by drdamour** [comment]
Can do, but wish youd reconsider since you have all the plumbing. Having to walk the tree a second time in a report to compare next to the contrast is wasteful especially with all the semantics in config about what a diff is.

json compare cant account for case insensitivity, ignoring fields, and all the other logic youve accommodated for in config. Json compare loses that ability
