### ISSUE TITLE
Roadblocks when building CustomComparer

### ISSUE THREAD

**Issue by drdamour** [GregFinzer/Compare-Net-Objects#227]
I needed a comparer that treated some properties as case sensitive and some as case insensitive.  I originally attempted to derive from PropertyComparer but since it doesn't derive from BaseTypeComparer i can't add it to CustomComparer, so i went a different route with:

```
public override void CompareType(
            CompareParms parms
        )
        { 
            //TODO: don't use mutable config...instead copy construct or something...

            //need to remove me to avoid cyclic execution
            parms.Config.CustomComparers.Remove(this);

            var originalIncludeMembers = parms.Config.MembersToInclude;
            var originalCaseSensitivity = parms.Config.CaseSensitive;

            var caseSensitiveMembers = new List<string>(originalIncludeMembers);
            caseSensitiveMembers.AddRange(materialCaseSensitiveFields);
            parms.Config.MembersToInclude = caseSensitiveMembers;
            parms.Config.CaseSensitive = true;

            RootComparer.Compare(
                parms
            );

            var caseInsensitiveMembers = new List<string>(originalIncludeMembers);
            caseInsensitiveMembers.AddRange(materialCaseInsensitiveFields);
            parms.Config.MembersToInclude = caseInsensitiveMembers;
            parms.Config.CaseSensitive = false;

            RootComparer.Compare(
                parms
            );

            parms.Config.CaseSensitive = originalCaseSensitivity;
            parms.Config.MembersToInclude = originalIncludeMembers;
            //put me back
            parms.Config.CustomComparers.Add(this);
        }

```

which is pretty hacky but gets real close..the problem i ran into here was the include/exclude is all driven by the internal hashset "cache" which is only populated by a call to CompareLogic.

My next thought is to call CompareLogic with my mutated config and the copy back the Differences from that...which i think will work but is kinda ugly especially in terms of recreating the maxdifferences logic.

One idea i had was to move from BaseTypeComparer to ITypeComparer, cause then i at least could reuse PropertyComparer in a HasA type relationship...but that seems like the wrong direction.

Another option is to expose the calculate hashes method either directly, or indirectly.  Or to move it to be invoked from RootComparer (i didn't fully examine the consequences of this)

Any suggestions on best path to accomplish would be appreciated

**Comment by GregFinzer** [comment]
I would just simply create a custom string comparer based on this:
https://github.com/GregFinzer/Compare-Net-Objects/blob/master/Compare-NET-Objects/TypeComparers/StringComparer.cs

You can pass the members into your custom string comparer.

**Comment by drdamour** [comment]
@GregFinzer i should have pointed out that my fields aren't on the current object but nested throughout an object graph so forcing string comparer wasn't what i was hoping for

**Comment by GregFinzer** [comment]
Ok
