### ISSUE TITLE
MaxDepth For Comparison Feature

### ISSUE THREAD

**Issue by erdemgonul** [GregFinzer/Compare-Net-Objects#228]
I want to compare the first level properties of  comparison objects. For example we have a property of complex object array.

```
class ComparisonObj
{
     public ComplexObject[] Property {get;set;}
}
class ComplexObject
{
     public string A {get;set;}
     public string B {get;set;}
}
```

I am not interested in element of array , I am interested   in if  ComparisonObj.Property  is changed or not.  So could you add maxDepth feature please? For example I want to use your great library with maxDepth=1 feature.

**Comment by GregFinzer** [comment]
That sounds like a great idea.  Please implement in a pull request.
