### ISSUE TITLE
IgnoreCollectionOrder in combination with CustomComparer

### ISSUE THREAD

**Issue by boosterch** [GregFinzer/Compare-Net-Objects#23]
Hello Greg,

I have an issue when using IgnoreCollectionOrder in combination with a CustomComparer.
We need a CustomComparer to handle a small difference in a decimal.

I looked into the code and I think the issue occurs in method CompareOutOfOrder.
My objects will never generate the same matchIndex,  because of the possible small difference between decimals.

I thought a possible solution was to use the default comparer while trying to find a matching object.
However this generates a lot of differences.

```
`                    //if (matchIndex1 == matchIndex2)
                    {
                        CompareParms childParms = new CompareParms
                        {
                            Result = parms.Result,
                            Config = parms.Config,
                            ParentObject1 = parms.Object1,
                            ParentObject2 = parms.Object2,
                            Object1 = enumerator1.Current,
                            Object2 = enumerator2.Current,
                            BreadCrumb = currentBreadCrumb
                        };

                        bool blnIsMatch = _rootComparer.Compare(childParms);
                        if (blnIsMatch)
                        {
                            _alreadyCompared.Add(matchIndex1);
                            found = true;
                            break;
                        }
                    }
```

`

Hope you can help me with this.
Thanks. Regards, Corné

**Comment by GregFinzer** [comment]
Corné, sorry, I am just too busy to support this project.  You will have to figure out a fix yourself.

**Comment by GregFinzer** [comment]
Corné,

I would add an id to your class to match them up or find another identifier that stays consistent.

Thanks,
Greg
