### ISSUE TITLE
Alternative to IgnoreObjectTypes while comparing two inetrface (IList)

### ISSUE THREAD

**Issue by goyzhang** [GregFinzer/Compare-Net-Objects#232]
It's very common that, as polymorphism indicates, for example, we want to compare two IList<int> while not caring their concrete type(can be `List` or `Array` or custom type). 

Correct me if I'm wrong, according to the doc, currently to enable this we can only do `logic.Config.IgnoreObjectTypes = true;`.
However, this will perform a "duck-typing" compare which is too strong and is a overall configuration. Can we have a property to allow interface-based type comparison by only allowing inherited type?  The concept is similar to Type.IsAssignableFrom(Type) Method.

**Comment by GregFinzer** [comment]
That sounds like a great feature.  Please implement and I will approve the pull request.

**Comment by GregFinzer** [comment]
Released in Version 4.74
https://github.com/GregFinzer/Compare-Net-Objects/releases/tag/v4.74

https://www.nuget.org/packages/CompareNETObjects/4.74.0
