### ISSUE TITLE
"CompareReadOnly = false" is not working as expected.

### ISSUE THREAD

**Issue by snys98** [GregFinzer/Compare-Net-Objects#245]
I had a compare logic like this for comparing all settable instance properties.
```
private static CompareLogic _compareLogic = new CompareLogic(new ComparisonConfig()
        {
            CompareFields = false,
            CompareReadOnly = false,
            CompareStaticFields = false,
            CompareStaticProperties = false,
            MaxStructDepth = 5,
        });
```
however, some getter is triggered during the comparation.

![image](https://user-images.githubusercontent.com/11873100/147666453-857ba149-1b97-412d-94ff-532cce03d751.png)

maybe properties with `CanWrite == false` should be filtered in `ExcludeLogic.ShouldExcludeMember`?

![image](https://user-images.githubusercontent.com/11873100/147666766-a12fc4d6-3b7c-41db-b884-b2af17715547.png)

**Comment by GregFinzer** [comment]
Thanks for reporting this issue.

**Comment by GregFinzer** [comment]
Fixed and deployed to NuGet
