### ISSUE TITLE
IgnoreDateTimeOffsetTimezones does not work with DateTime

### ISSUE THREAD

**Issue by hsnsalhi** [GregFinzer/Compare-Net-Objects#246]
Hello,
IgnoreDateTimeOffsetTimezones config option does not work when object is of type DateTime
I have done a workaround to make it working by modifying the CompareType method of DateComparer
I just convert DateTime to DateTimeOffset and use the same logic done in DateTimeOffsetComparer

`
        public override void CompareType(CompareParms parms)
        {
            //This should never happen, null check happens one level up
            if (parms.Object1 == null || parms.Object2 == null)
                return;

            DateTimeOffset date1 = (DateTime) parms.Object1;
            DateTimeOffset date2 = (DateTime) parms.Object2;

            if (parms.Config.IgnoreDateTimeOffsetTimezones)
			{
                date1 = date1.ToUniversalTime();
                date2 = date2.ToUniversalTime();
			}

            if (Math.Abs(date1.Subtract(date2).TotalMilliseconds) > parms.Config.MaxMillisecondsDateDifference)
                AddDifference(parms);

        }
`

**Comment by GregFinzer** [comment]
Thank you for reporting this issue

**Comment by hsnsalhi** [comment]
I solved my problem in a fork, I created a pull request for that. here is the link https://github.com/GregFinzer/Compare-Net-Objects/issues/116

**Comment by GregFinzer** [comment]
Deployed to NuGet
