### ISSUE TITLE
Compares on System.__ComObject's don't work

### ISSUE THREAD

**Issue by jamesjohnmcguire** [GregFinzer/Compare-Net-Objects#249]
Not surprising actually.  It seems because of late-binding to native COM object, reflection doesn't pick up any properties.

Here is an example of trying to compare 2 Outlook MailItems, which are basically wrappers around a COM object.

```
	MailItem mailItem = CreateMailItem("someone@example.com", "This is the subject", "This is the message.");
	MailItem mailItem2 = CreateMailItem("someoneelse@example.com", "This is another subject", "This is the message.");

	CompareLogic compareLogic = new CompareLogic();
	ComparisonResult compareResult = compareLogic.Compare(mailItem, mailItem2);

	if (compareResult.AreEqual)
	{
		Console.WriteLine("Objects are the same");
	}
	else
	{
		Console.WriteLine(compareResult.DifferencesString);
	}

```
Always states the objects are equal since it doesn't find any properties.

A brief explanation is given here: [https://stackoverflow.com/questions/9735394/reflection-on-com-interop-objects](https://stackoverflow.com/questions/9735394/reflection-on-com-interop-objects)

I imagine this would take a fair amount of work to get this working.  But it would be super great to have this support!

In the meantime, perhaps check if the underlying type is a COM object and throw a 'Not supported' exception.

**Comment by GregFinzer** [comment]
@jamesjohnmcguire You would need to create a custom comparer specifically for the MailItem type.  I have updated the readme.md with this limitation.  https://github.com/GregFinzer/Compare-Net-Objects/wiki/Custom-Comparers
