### ISSUE TITLE
Question about json format

### ISSUE THREAD

**Issue by sebasijan** [GregFinzer/Compare-Net-Objects#250]
Hello, is there any option to represent the diff/changes in any other format, in particular json? 

Or would I need to do that conversion manually?

**Comment by GregFinzer** [comment]
That is not built into Compare .NET Objects.  You would need to use something like Newtonsoft Json:
https://www.nuget.org/packages/Newtonsoft.Json/

`Person p1 = null;
Person p2 = new Person();
ComparisonResult result = _compare.Compare(p1, p2);
string json = JsonConvert.SerializeObject(result.Differences, Formatting.Indented);`
