### ISSUE TITLE
Missing NET 6 version

### ISSUE THREAD

**Issue by joer33304** [GregFinzer/Compare-Net-Objects#253]
As NET 5 LTS is expiring in 2 month, can we get a 6 version please ?

**Comment by ValeraT1982** [comment]
Going to fix it in the next version

**Comment by joer33304** [comment]
Great, is there an ETA ?

**Comment by GregFinzer** [comment]
It has a .NET Standard 2.0 build.  It is already compatible with .NET 6

Go here and click on the frameworks tab.  
https://www.nuget.org/packages/CompareNETObjects/

**Comment by joer33304** [comment]
Ah sorry, I used the wrong fork CompareObjects. Using your linked version it works, Thanks
