### ISSUE TITLE
Why can't I get CollectionMatchingSpec to work?

### ISSUE THREAD

**Issue by sebasijan** [GregFinzer/Compare-Net-Objects#254]
Say I pass in 2 instances of this class for actual/expected:

    public sealed record CompanyDTO
    {
        Public IReadOnlyCollection<AddressDTO> Addresses { get; init; }
     }

where

    AddressDTO
    {
           public Guid Id { get; init; }
           public string Address { get; init; }
     }

Previously I swear I could get a change in one of the addresses to appear like this:

        Addresses[Id: "b9e628e3-9ce1-4b27-8e82-e669d5871a10"].Address : [
                "1 test street",
                "2 test street"
        ]

But now every time I compare, it just appears like this (ignoring my CollectionMatchingSpec completely):

        Addresses[1].Address : [
                "1 test street",
                "2 test street"
        ]

where `1` seems to be simply the index of the collection, and `Addresses[1].Address` is coming from the difference `PropertyName`

How did I get it to do that before? And is this documented anywhere?

My config:

    private static readonly ComparisonConfig ComparisonConfig = new()
    {
        IgnoreMissingProperties = true,
        MaxDifferences = int.MaxValue,
        CollectionMatchingSpec =
        {
            { typeof(AddressDTO), new[] { nameof(AddressDTO.Id) } }
        }
    };

**Comment by sebasijan** [comment]
Turns out it only works as above when setting `IgnoreCollectionOrder` to `true`

**Comment by GregFinzer** [comment]
I have updated the doc:  
https://github.com/GregFinzer/Compare-Net-Objects/commit/f578c6158983365a4b580dab43b847aee4e9a6aa
