### ISSUE TITLE
Option of relative double precision for doubles

### ISSUE THREAD

**Issue by IsakNaslundBh** [GregFinzer/Compare-Net-Objects#258]
First, thanks for a great tool!

We have some objects we want to compare where the order of magnitude of the double values can vary by quite a significant amount. One property might be in the order of magnitude of e+11 and another property e-6. For some applications we want to check that the values are within an acceptable tolerance, say within 6 significant digits, rather than exact. With the current 

https://github.com/GregFinzer/Compare-Net-Objects/blob/f578c6158983365a4b580dab43b847aee4e9a6aa/Compare-NET-Objects/ComparisonConfig.cs#L537

and 

https://github.com/GregFinzer/Compare-Net-Objects/blob/f578c6158983365a4b580dab43b847aee4e9a6aa/Compare-NET-Objects/TypeComparers/DoubleComparer.cs#L33-L48

This seems not possible for a single object carrying both of those properties.

I take it from https://github.com/GregFinzer/Compare-Net-Objects/issues/148 and https://github.com/GregFinzer/Compare-Net-Objects/commit/d86e74fe58f50642ec90de11fb4f58cb3da41533 that it was an intentional change, which I can understand as well.

Wonder if it would be possible to get a boolean setting added, like `RelativeDoublePrecision` added to the config that could allow for the  behaviour previous to https://github.com/GregFinzer/Compare-Net-Objects/commit/d86e74fe58f50642ec90de11fb4f58cb3da41533 to be used?

Also related to https://github.com/GregFinzer/Compare-Net-Objects/issues/182

**Comment by GregFinzer** [comment]
I think the best course of action would be for your project to use a custom comparer.  That way current double functionality stays in tact.  

See:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Custom-Comparers

**Comment by IsakNaslundBh** [comment]
Thanks, will have a look at the custom comparers, think that will resort our issues!
