### ISSUE TITLE
Ignoring DateTime.Kind?

### ISSUE THREAD

**Issue by qfyra** [GregFinzer/Compare-Net-Objects#259]
In 4.76.0, how would I go about configuring CompareLogic to ignore the Kind property of DateTime objects? IgnoreDateTimeOffsetTimezones = true does not work it seems. 

Diff string looks like this: 

`Types [DateTime,DateTime], Item Expected.StartDate != Actual.StartDate, Values (2022-03-28 13:46:00,2022-03-28 13:46:00)`

The only differences between the objects is Kind.Utc vs Kind.Unspecified.

<img width="238" alt="expected" src="https://user-images.githubusercontent.com/59998991/160413990-770af905-8a56-415b-8315-de39dc0987d1.png">

<img width="235" alt="actual" src="https://user-images.githubusercontent.com/59998991/160413994-7c815771-e2ff-4a5f-81a4-3a9569414ef4.png">

I **think** the Unspecified kind is due to a bug/feature in .Net Core 3 APIs. It only happens when I call the API with Postman using a body containing:

`"StartDate": "{{dateTimeNow}}"`

... where dateTimeNow is specified in the following way in the pre-request script:

`var dateTimeNow = pm.variables.replaceIn("{{$isoTimestamp}}");`

I also **think** the common solution to this problem is to force Kind.Utc onto DateTime objects created from the incoming request body, and I could potentially do that, but I'm not sure at this point what it would do on the API consumer side.

**Comment by GregFinzer** [comment]
@qfyra Can you look at the code for the DateComparer.cs?  What would you propose to handle this situation?  There is this block since version 4.75:

`            if (date1.Kind != date2.Kind)
            {
                date1 = date1.ToUniversalTime();
                date2 = date2.ToUniversalTime();
            }`

https://github.com/GregFinzer/Compare-Net-Objects/blob/master/Compare-NET-Objects/TypeComparers/DateComparer.cs

**Comment by qfyra** [comment]
Not sure what the best solution is yet. I did write a little console app test (.net core 3.1) to try and figure out what was going on. The issue can be seen using a simple DateTime.TryParse. 


```
using KellermanSoftware.CompareNetObjects;
using System;

namespace DateTimeKindTest
{
	class Program
	{
		static void Main(string[] args)
		{
			var nowUtc = DateTime.UtcNow.Date;
			DateTime.TryParse(nowUtc.ToString("yyyy-MM-dd"), out DateTime nowUtcParsed);

			var compareLogic = new CompareLogic();
			compareLogic.Config.IgnoreDateTimeOffsetTimezones = true;

			var compareResult1 = compareLogic.Compare(nowUtc, nowUtcParsed);

			// Both ticks are the same here, even though Kind is different (Utc vs Unspecified)
			Console.WriteLine(compareResult1.DifferencesString);
			Console.WriteLine($"nowUtc {nowUtc.ToLongDateString()} - {nowUtc.Ticks} - {nowUtc.Kind}");
			Console.WriteLine($"nowUtc {nowUtcParsed.ToLongDateString()} - {nowUtcParsed.Ticks} - {nowUtcParsed.Kind}");

			// Doing the same comparison and assignment as in DateComparer.cs
			if (nowUtc.Kind != nowUtcParsed.Kind)
			{
				nowUtc = nowUtc.ToUniversalTime();
				// looks like Kind.Unspecified is interpreted as Kind.Local when calling ToUniversalTime(),
				// meaning ticks are now different
				nowUtcParsed = nowUtcParsed.ToUniversalTime();
			}

			var compareResult2 = compareLogic.Compare(nowUtc, nowUtcParsed);

			// Ticks are different now, meaning AreEqual is false
			Console.WriteLine(compareResult2.DifferencesString);
			Console.WriteLine($"nowUtc {nowUtc.ToLongDateString()} - {nowUtc.Ticks} - {nowUtc.Kind}");
			Console.WriteLine($"nowUtc {nowUtcParsed.ToLongDateString()} - {nowUtcParsed.Ticks} - {nowUtcParsed.Kind}");

		}
	}
}

```

**Comment by GregFinzer** [comment]
So maybe if one of dates the kind is unspecified then do not do the ToUniversalTime() ?

**Comment by qfyra** [comment]
I think you're onto something, but I would actually go one step further and make a nullable setting with which you can specify what Kind should be used by the comparelogic if the Kinds are different AND one of the Kinds are unspecified.

If the setting is null (which would be the default setting value), the current code in DateComparer.cs will do the exact same thing it does today, i.e. convert to UTC. This ensures backwards compatibility with 4.76. 

However, if the setting is specified by the user with a DateTimeKind, the code will substitute the Unspecified kind with whatever the user wanted.  I'm thinking along the lines of this (the conditionals can probably be optimized a bit) :

```
DateTimeKind? DateTimeKindToUseWhenUnspecified;

...

// user specifies a Kind in the comparelogic
compareLogic.Config.DateTimeKindToUseWhenUnspecified = DateTimeKind.Utc;

...

if (date1.Kind != date2.Kind)
{
	if(date1.Kind == DateTimeKind.Unspecified && DateTimeKindToUseWhenUnspecified!= null)
		date1 = DateTime.SpecifyKind(date1, DateTimeKindToUseWhenUnspecified.Value);
	
	if(date2.Kind == DateTimeKind.Unspecified && DateTimeKindToUseWhenUnspecified != null)
		date2 = DateTime.SpecifyKind(date2, DateTimeKindToUseWhenUnspecified.Value);

	date1 = date1.ToUniversalTime();
	date2 = date2.ToUniversalTime();
}
```

**Comment by GregFinzer** [comment]
I have made the default to use as UTC with the ability to not fill it in.

**Comment by ltrzesniewski** [comment]
FYI this affects us as well. Our tests started failing after updating the library because of the behavior change in #116. I have downgrade until the next release.

**Comment by GregFinzer** [comment]
Deployed:  Deployed:  https://www.nuget.org/packages/CompareNETObjects/4.77.0

**Comment by ltrzesniewski** [comment]
Thanks! 🙂
