### ISSUE TITLE
If different object types generate the same HashCode the program can fail to find differences  

### ISSUE THREAD

**Issue by MikaelWilen** [GregFinzer/Compare-Net-Objects#26]
I found that if a parent object have the same HashCode that its child object the program fails to find differences in the child object.
Example code:
In the code below I have a parent that always will get the same Hashcode that its Child. When testing the program cant find the difference between the child objects despite that one have Value=1 and the other Value = 2.

        public class Child
        {
            public int Value { get; set; }
            public override int GetHashCode()
            {
                    return Value;
            }
        }
        public class Parent
        {
            public int Value { get; set; }
            public Child Child { get; set; }
            public override int GetHashCode()
            {
                return Child.Value;
            }
        }
        [Test]
        public void TestMethod()
        {
            var parent1 = new Parent() {Value= 1, Child = new Child() {Value = 1} };
            var parent2 = new Parent() {Value= 1, Child = new Child() {Value = 2} };

            var comparer = new CompareLogic();
            var result = comparer.Compare(parent1, parent2);

            Assert.IsFalse(result.AreEqual);
        }

Msdn states the following: 
Two objects that are equal return hash codes that are equal. However, the reverse is not true: equal hash codes do not imply object equality, because different (unequal) objects can have identical hash codes. 
•You should not assume that equal hash codes imply object equality.
https://msdn.microsoft.com/en-us/library/system.object.gethashcode%28v=vs.110%29.aspx

Regards
Mikael W

**Comment by GregFinzer** [comment]
Mikael,

I am not fixing this one.

Thanks,
Greg

**Comment by LosManos** [comment]
Without digging into the code of Compare-Net-Objects it looks like Compare-Net-Objects only checks the hash for this case. Is this a correct assumption?

**Comment by GregFinzer** [comment]
That is correct.
