### ISSUE TITLE
QuantityTypes behaviour change between 4.75.0 to 4.76.0

### ISSUE THREAD

**Issue by DotanNirBsii** [GregFinzer/Compare-Net-Objects#260]
im trying to compare two QuantityTypes in version 76, let say Angle, but the compare is failing on:
`
Begin Differences (1 differences):
Types [Double,Double], Item Expected.ElevD.PositiveInfinity.Value != Actual.ElevD.PositiveInfinity.Value, Values (∞,∞)
End Differences (Maximum of 1 differences shown).
`
whent the compare is something like 
```
GenerateCompareLogic().Compare(5 * QuantityTypes.Angle.Degree, 5 * QuantityTypes.Angle.Degree) 
```

each QuantityTypes one has PositiveInfinity prop which are built as
https://github.com/QuantityTypes/QuantityTypes/blob/02c70eaaca25f1d4d279b205f4bd36bd54ae7392/Source/CodeGenerator/Template.cs#L62

so the comparer is doing the struct compare and inside there is the double one:
https://github.com/GregFinzer/Compare-Net-Objects/blob/80bd7ebc79c65ec23ceef0642afd67cee00bc961/Compare-NET-Objects/TypeComparers/DoubleComparer.cs#L42

so we have 

```
double.IsNaN(double.PositiveInfinity - double.PositiveInfinity)
```
which is true so the compare is failing. not sure what is the change from the prev version, i think this is a bug, but im not too familiar with the lib to be certain. thanks

**Comment by GregFinzer** [comment]
@DotanNirBsii I am unable to reproduce the issue.  Here is the passing test:

`        [Test]
        public void PositiveInfinityAndNegativeInfinityShouldBeDifferent()
        {
            double positiveInfinity = Double.PositiveInfinity;
            double negativeInfinity = Double.NegativeInfinity;

            CompareLogic compareLogic = new CompareLogic();
            var result = compareLogic.Compare(positiveInfinity, negativeInfinity);
            Console.WriteLine(result.DifferencesString);
            Assert.IsFalse(result.AreEqual);
        }`

Here is the output:

Begin Differences (1 differences):
Types [Double,Double], Item Expected != Actual, Values (∞,-∞)
End Differences (Maximum of 1 differences shown).

**Comment by dotannir1** [comment]
sorry about the delay, lost temp access to my work account. can you try the following:

```
[Test]
public void  PositiveInfinityShouldBeTheSame()
{
	double positiveInfinity = Double.PositiveInfinity;
	double positiveInfinity2 = Double.PositiveInfinity;

	CompareLogic compareLogic = new CompareLogic();
	var result = compareLogic.Compare(positiveInfinity, positiveInfinity2 );
	Console.WriteLine(result.DifferencesString);
	Assert.IsFalse(result.AreEqual);
}
```
and 

```
[Test]
public void AngelsShouldBeTheSame()
{
	CompareLogic compareLogic = new CompareLogic();
	var result = compareLogic.Compare(5 * Angle.Degree, 5 * Angle.Degree);
	Console.WriteLine(result.DifferencesString);
	Assert.IsFalse(result.AreEqual);
}
```
while the other im not sure should be the same, because comparing infinity is not define well, the second should be equal.
the problem is the second one contain a Positive Infinity angle, which contain a Positive Infinity double

**Comment by GregFinzer** [comment]
Ok.  I have created a fix.  Can you check it?

**Comment by DotanNirBsii** [comment]
> Ok. I have created a fix. Can you check it?

the code seems ok to me, if the test is passing i think this is a good fix. thanks 
(i didnt run the code itself)

**Comment by GregFinzer** [comment]
Deployed:  https://www.nuget.org/packages/CompareNETObjects/4.77.0
