### ISSUE TITLE
Only first difference between object properties is returned

### ISSUE THREAD

**Issue by alelom** [GregFinzer/Compare-Net-Objects#264]
### Description and replication instructions

Using Nuget package version 4.77.0. 

In the following test:

```cs
void Main()
{
	Point p1 = new Point() { X = 101, Y = 102, Z = 103 };
	Point p2 = new Point() { X = 0, Y = 0, Z = 0 };

	CompareLogic compareLogic = new CompareLogic() { };

	ComparisonResult result = compareLogic.Compare(p1, p2);
	result.Differences.Dump(); // Dump() prints the object in LinqPad
}

public class Point
{
	public double X { get; set; }
	public double Y { get; set; }
	public double Z { get; set; }
}
```

The `Differences` includes only the difference in the `X` property:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/6352844/179503354-4bef59f0-7c24-44f9-ab79-e11c10c2f9af.png">

If the `p1` object has its `X` property to `0`, making it equal to `p2.X`, then only the difference in `Y` property is returned.

### Desired behaviour
All differences in all properties `X`, `Y` and `Z` should be returned.

**Comment by alelom** [comment]
Apologies, I only now realise that I missed to set the `MaxDifferences`. Is there any way to set `MaxDifferences` equal to e.g. the number of public properties by default?

```cs
CompareLogic compareLogic = new CompareLogic() { Config = new ComparisonConfig() { MaxDifferences = 10 } };
```

**Comment by GregFinzer** [comment]
Sorry it does not have that functionality.  Just set it to the max and that should work fine for you.

**Comment by GregFinzer** [comment]
@alelom it is in the Wiki here under Getting Started:  https://github.com/GregFinzer/Compare-Net-Objects/wiki/Getting-Started
