### ISSUE TITLE
Is there a way to support IEnumerable comparison inside objects for compare?

### ISSUE THREAD

**Issue by betsson-vyza** [GregFinzer/Compare-Net-Objects#265]
Hi,
I've noticed IEnumerable collections inside objects are always equal.
Is there a plan to add support for such?

**Comment by betsson-vyza** [comment]
[testCompareNetObjects.zip](https://github.com/GregFinzer/Compare-Net-Objects/files/9276555/testCompareNetObjects.zip)
Attached sln to reproduce the issue.

**Comment by GregFinzer** [comment]
@betsson-vyza There is currently no plan to support IEnumerable collections.  If you would like to create that functionality with a test that would be great.
