### ISSUE TITLE
Debug version of library on Nuget

### ISSUE THREAD

**Issue by KSYMEK** [GregFinzer/Compare-Net-Objects#266]
Hello, 

I was trying to run some benchmarks using BenchmarkDotnet but as far as I see the nuget version has a debug version of library.

```
Assembly Bench which defines benchmarks references non-optimized KellermanSoftware.Compare-NET-Objects
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can disable this policy by using 'config.WithOptions(ConfigOptions.DisableOptimizationsValidator)'.
```

**Comment by GregFinzer** [comment]
It is built in release mode.  I am not sure why it says it is in Debug mode.  I just did another redeploy.  There is no need to run any benchmarks as it is going to be slow by definition because it is using reflection.  If you want better performance, implement IComparable.

**Comment by KSYMEK** [comment]
Yeah I know it will not be fast as IComparable but I just wanted to make assertion how performance looks like in my project case

**Comment by KSYMEK** [comment]
And now it's in release mode and works faster.

Before:

|                                        Method |          Mean |       Error |      StdDev |    Gen0 |   Gen1 | Allocated |
|---------------------------------------------- |--------------:|------------:|------------:|--------:|-------:|----------:|
|      1 | 69,470.312 ns | 209.2798 ns | 163.3919 ns | 12.4512 | 0.2441 |  163328 B |
|   2 | 74,481.891 ns | 618.7228 ns | 548.4817 ns |  8.4229 |      - |  111074 B |

After:

|                                        Method |          Mean |       Error |      StdDev |    Gen0 |   Gen1 | Allocated |
|---------------------------------------------- |--------------:|------------:|------------:|--------:|-------:|----------:|
|      1 | 50,435.124 ns | 991.2432 ns | 973.5333 ns | 12.4512 | 0.2441 |  163328 B |
|   2 | 50,651.431 ns | 661.5895 ns | 618.8512 ns |  8.4839 | 0.0610 |  111074 B |

**Comment by GregFinzer** [comment]
Ok so 20 milliseconds faster in release mode.
