### ISSUE TITLE
CompareReadonly = false still reads and gets the value for the property!!

### ISSUE THREAD

**Issue by srigithub99** [GregFinzer/Compare-Net-Objects#267]
I have given CompareReadonly = false in the config, it does not include the read-only variables in the differences which is the expected behaviour. But what my question is if we have given CompareReadonly=false the comparer should not even try to get the value for that property. In PropertyComparer.cs line 165 I guess it should be like if(!parms.Config.ReadOnly) continue;  In the existing implementation if it is a read only variable and CompareReadonly= false it adds to the current properties list. Actually it should skip the read only property [don't add to the current properties list] in that point itself. Correct me if I am wrong

**Comment by GregFinzer** [comment]
Ok.  Thanks for letting me know.

**Comment by GregFinzer** [comment]
@srigithub99 I have a large charity project I am working on and have very little time:  https://github.com/GregFinzer/BedBrigadeNational

If you would like to fix this defect, I would be happy to merge the pull request.

**Comment by GregFinzer** [comment]
I created a test to verify that it is not accessing the read only property.
https://github.com/GregFinzer/Compare-Net-Objects/pull/293
