### ISSUE TITLE
EnumComparer is not used by default

### ISSUE THREAD

**Issue by killergege** [GregFinzer/Compare-Net-Objects#269]
Hello,

I just noticed that the [EnumComparer](https://github.com/GregFinzer/Compare-Net-Objects/blob/master/Compare-NET-Objects/TypeComparers/EnumComparer.cs) is not added to the comparers by default.
So when you have enums of different types, you get the error `Object must be the same type as the enum`.

Searching the code, I noticed the comparer exist, so I added it manually, but is there a reason for not adding it by default ?

**Comment by GregFinzer** [comment]
Did it work when you added it manually?  Did all the other tests pass?

**Comment by GregFinzer** [comment]
Closing.  No response.
