### ISSUE TITLE
Crash in UWP app when compiled in .Net Native

### ISSUE THREAD

**Issue by scott-stoltz** [GregFinzer/Compare-Net-Objects#27]
Test project attached. Run project locally in x86 Debug...project runs. Switch to Release (.Net Native) and launch again...error.

[CompareNetObjectsTest.zip](https://github.com/GregFinzer/Compare-Net-Objects/files/700135/CompareNetObjectsTest.zip)

**Comment by rcolepeterson** [comment]
+1

**Comment by rcolepeterson** [comment]
This is the error I when switched to release ...

Unhandled exception at 0x7489F757 (combase.dll) in comparemetests.exe: Stack cookie instrumentation code detected a stack-based buffer overrun.

**Comment by scott-stoltz** [comment]
We've tried adding the namespace to a run-time directives file, but it did not fix the issue.

**Comment by GregFinzer** [comment]
I am unable to open the test project.  I am going to wait until Visual Studio 2017 is released.  I think my Visual Studio 2015 install is messed up.

**Comment by GregFinzer** [comment]
@rcolepeterson @scott-stoltz I just re-worked the .NET Core project with Visual Studio 2017.  Can you get the latest source and try it out to see if you still receive the same error?

**Comment by rcolepeterson** [comment]
Awesome and thx! I will check out.

Cole

Sent from my iPhone

On Apr 7, 2017, at 12:33 PM, GregFinzer <notifications@github.com<mailto:notifications@github.com>> wrote:


@rcolepeterson<https://github.com/rcolepeterson> @scott-stoltz<https://github.com/scott-stoltz> I just re-worked the .NET Core project with Visual Studio 2017. Can you get the latest source and try it out to see if you still receive the same error?

**Comment by GregFinzer** [comment]
@scott-stoltz Can you pull the latest and test?

**Comment by GregFinzer** [comment]
Fixed in version 3.08
https://www.nuget.org/packages/CompareNETObjects/3.8.0

**Comment by gbutler69** [comment]
Can I ask how you fixed this? I'm seeing an issue with a Xamarin.Forms UWP Applicaiton with the latest Xamarin.Forms and UWP etc. I've been going in circles trying to understand the issue. What solved for you?

**Comment by GregFinzer** [comment]
Gerald,

Sorry, I do not remember how I fixed this.  You would need to look back at the check ins around that version to see what changed.

Thanks,
Greg


________________________________
