### ISSUE TITLE
Version 4.77 breaks date comparison behavior

### ISSUE THREAD

**Issue by ssg** [GregFinzer/Compare-Net-Objects#270]
Version 4.77 seems to have started to compare "Kind" property of DateTimes which weren't taken into account before. This is a problem in unit tests when EF Core returned DateTimes are compared with instantiated DateTimes like `DateTime.Today`. EF Core assigns `DateTimeKind.Unspecified` while `DateTime.Today` defaults to `DateTimeKind.Local`.

This might be the more correct behavior, but it's a breaking change nevertheless. Definitely not a minor change. Is there a way to suppress the behavior?

**Comment by GregFinzer** [comment]
Did you try setting DateTimeKindToUseWhenUnspecified?

**Comment by GregFinzer** [comment]
No it was added with 4.77
