### ISSUE TITLE
Compare different types of IEnumerable doesn't work and doesn't compare properly

### ISSUE THREAD

**Issue by killergege** [GregFinzer/Compare-Net-Objects#273]
When you try to compare different IEnumerables (in my case an IEnumerable and Hashset), it fails with an NullException.

Test to reproduce :
```
        [Test]
        public void CompareListsTwoDifferentTypes()
        {
            IEnumerable<Person> list1 = new List<Person>
            {
                new Person() { Name = "Logan 5" },
                new Person() { Name = "Francis 7" }
            }.Select(x => x);

            HashSet<Officer> list2 = new HashSet<Officer>();
            list2.Add(new Officer() { Name = "Logan 5" });
            list2.Add(new Officer() { Name = "Francis 7" });

            ComparisonConfig config = new ComparisonConfig();
            config.IgnoreObjectTypes = true;

            CompareLogic compareLogic = new CompareLogic(config);
            var result = compareLogic.Compare(list1, list2);
            Assert.IsTrue(result.AreEqual);
        }
```
It generates 
```
System.ArgumentException : parms.Object2
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.ListsHaveDifferentCounts(CompareParms parms) in C:\Users\JulienNIGAY\Documents\Projects\External\Compare-Net-Objects\Compare-NET-Objects\TypeComparers\ListComparer.cs:line 119
```
The reason for the NullException is because `TypeHelper.IsEnumerable()` returns false for the Hashset which means that the following line (in `EnumerableComparer`) : `TypeHelper.IsEnumerable(t2) ? ConvertEnumerableToList(parms.Object2) : parms.Object2` will NOT convert the Object2 to List, and in ListComparer, the `as IList` will return null.

Doing some analysis, I think that `TypeHelper.IsEnumerable` will return false in too many cases.

It causes 2 issues :
* The above NullException, due to a cast issue.
* If you try to compare different enumables that are not IList, it will not trigger the `EnumableComparer`, and will compare the properties. Which mean that the following test will fail (in this one, I don't force to IEnumerable), although the data are different, as long as the number of entries is the same.
```
        [Test]
        public void CompareListsTwoDifferentTypes()
        {
            List<Person> list1 = new List<Person>();
            list1.Add(new Person() { Name = "Other name" });
            list1.Add(new Person() { Name = "Francis 7" });

            HashSet<Officer> list2 = new HashSet<Officer>();
            list2.Add(new Officer() { Name = "Logan 5" });
            list2.Add(new Officer() { Name = "Francis 7" });

            ComparisonConfig config = new ComparisonConfig();
            config.IgnoreObjectTypes = true;

            CompareLogic compareLogic = new CompareLogic(config);
            var result = compareLogic.Compare(list1, list2);
            Assert.IsFalse(result.AreEqual);
        }
```

A VERY quick fix is to update the TypeHelper.IsEnumerable to check for IEnumerable :  `return typeof(IEnumerable).IsAssignableFrom(type);`
This fixes the specific issues I mentioned, but it seems to break a few tests. So it could probably be improved, I don't know the lib well enough to understand the consequences, but I'll keep looking into it.
For instance, `string` will return true... Which is right, but maybe not what we want...

--------------
From what I see the tests fail because: 
* `EnumerableComparer` is high in the comparer's list, for me it should be after all more specific collection types comparers (to fix, I moved it after `CollectionComparer`, and moved `ImmutableArrayComparer` just before it)
* `CompareIndexerTests.TestIndexerLengthNegative` fail because it expect comparison details that `EnumerableComparer` won't report by default. Before it was handled by `ClassComparer`.
* `IgnoreOrderTests.CollectionsWithNestedColelctionsAndOtherdTypesAreUnsupported` fail because string is a `IEnumerable`, so I added `&& type != typeof(string)` to `IsEnumerable` (I didn't find better)
* `IgnoreTests.ExpandoObject` is also considered as a `IEnumerable` while before it was handled by the `ClassComparer`

So changes I made:
* `TypeHelper.IsEnumerable` I have is `return typeof(IEnumerable).IsAssignableFrom(type) && type != typeof(string)  && type.Name != "ExpandoObject"` (Yes, awful, didn't find better yet, I'm not used to dynamic types)
* Move `EnumerableComparer` lower and moved  `ImmutableArrayComparer` before
* Changed some expected differences (although changing settings might fix the test without changing the differences number)

Feel free to tell me I'm wrong and I misinterpreted the expected behavior of `EnumerableComparer` & `TypeHelper.IsEnumerable`

**Comment by GregFinzer** [comment]
Thanks for reporting this issue.

**Comment by GregFinzer** [comment]
@killergege I have a large charity project I am working on and have very little time:  https://github.com/GregFinzer/BedBrigadeNational

If you would like to fix this defect, I would be happy to merge the pull request.

**Comment by killergege** [comment]
Ok, I'll push the fixes I explained above, but I'll certainly miss a few things (hopefully the tests cover all cases ^^), and you don't mind "hardcoding" some conditions to exclude some specific types from IEnumerable.
