### ISSUE TITLE
Enhancement: Add ComparisonConfig.CompareBackingFields

### ISSUE THREAD

**Issue by Mch-Kuzyk** [GregFinzer/Compare-Net-Objects#277]
I want to share a problem that I have encountered while using this tool. 
I will be brief, I noticed that I have a special case at work when using your library, which is the need to ignore `ComparisonConfig.CompareBackingFields` especially in the case of auto properties of lists (list, hashset, array, etc.), which affects the performance.
For this, I would like to propose this improvement in favor of flexibility and improved performance by adding a separate configuration of backing fields in config.  
I already implemented this functionality in fork, so I'm ready to create a pull request.
Open for discussion on this topic.

**Comment by GregFinzer** [comment]
Sorry for the late response.  My father passed away recently and I am catching up.  So when CompareBackingFields is set to false, what exactly is ignored from the comparison?

**Comment by Mch-Kuzyk** [comment]
I am so very sorry for your loss.

When `ComparePrivateFields=false`, no private field is compared. 
When `ComparePrivateFields=true` and `CompareBackingFields=true`, all private fields are compared. 
When `ComparePrivateFields=true` and `CompareBackingFields=false`, only the private fields declared by the programmer and not the compiler are compared. Backing field is a private field generated by the compiler for the auto-property. For example, for the PropName property a private field named `<PropName>k__BackingField` will be generated. There is no reason to consider them in comparison if `CompareProperties=true` - in that case both the value from `PropName.get` (which returns the backing field) and the backing field will be compared. Thanks to this trick you can remove the number of comparisons in half if the code consists of auto-properties with a small number of declared private fields. That is, `ComparePrivateFields=true` + `ComparePrivateProperties=true` will typically be about half as slow as `ComparePrivateFields=true` + `ComparePrivateProperties=true` + `CompareBackingFields=false`.

**Comment by Mch-Kuzyk** [comment]
resolved by #279
