### ISSUE TITLE
Enhancement: Visual Studio 2022 and JetBrains Rider developing

### ISSUE THREAD

**Issue by Mch-Kuzyk** [GregFinzer/Compare-Net-Objects#278]
No information was found in the repository and wiki about the instructions with the source code of this library from under Visual Studio 2022.
I was able to get this project set up to work with Visual Studio 2022 and the environment to work with this library.
The instructions below are:
1. When installing VS2022, select ".net Desktop Development".
2. Download the .NET 4.6.1 Devpack from the Microsoft website and install. Link below.
https://dotnet.microsoft.com/en-us/download/dotnet-framework 
3. VS2022 in Solution Explorer will display message "This project is targeting a version of .NET which is not installed" press button "Install", after that click "Install" for .NET Core 2.1.
4. Microsoft doesn't support .NET 4.0, you need to download https://github.com/3F/netfx4sdk for installing .NET 4.0. Open terminal in core folder, run file "build.bat". After completing, change directory to "netfx4sdk-master\bin\Release\raw" and run "netfx4sdk.cmd -mode sys". If you see "Done" .NET 4.5 is installed on your system.
5. Install another DevPack .NET 4.5.1, 4.5.2, 4.6, 4.7, 4.7.1 from Microsoft link below.
https://dotnet.microsoft.com/en-us/download/dotnet-framework
7. Microsoft also doesn't support .NET 4.5. Open folder C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework, after that you need to copy all files from folder 4.5.1 to 4.5 and click "Replace" in all conflicts. 
Source: https://stackoverflow.com/questions/73648702/install-net-framework-4-5-targeting-pack

**Comment by GregFinzer** [comment]
Thanks for the suggestion

**Comment by GregFinzer** [comment]
Updated system requirements with your verbiage:  https://github.com/GregFinzer/Compare-Net-Objects/wiki/System-Requirements
