### ISSUE TITLE
No license file and no license specified

### ISSUE THREAD

**Issue by BrianMcBrayer** [GregFinzer/Compare-Net-Objects#28]
Hello,

I am curious what license this is offered under. Is it commercial or completely open-sourced? If I can add a preference, I like the MIT family of licenses :) .

Thanks for the consideration.

**Comment by GregFinzer** [comment]
See the license page:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Licensing

**Comment by BrianMcBrayer** [comment]
Thanks! I hadn't seen that.
