### ISSUE TITLE
Failing tests for netcoreapp2.0

### ISSUE THREAD

**Issue by Kebechet** [GregFinzer/Compare-Net-Objects#281]
While working on #276 I found out that these 2 tests are not passing:
in `CompareDictionaryTests` test: `TestDictionary` and
in `CompareIListTests` test:`ArrayTest`

**Comment by GregFinzer** [comment]
Ok thanks

**Comment by GregFinzer** [comment]
@Kebechet What are the errors that are received?  How did you reproduce the error?  Did you create an NUnit .NET Core App 2.0 project?

**Comment by GregFinzer** [comment]
No information received.  Closing.
