### ISSUE TITLE
OSS Sponsorship

### ISSUE THREAD

**Issue by drdamour** [GregFinzer/Compare-Net-Objects#286]
Hi, the team i work on sponsors OSS projects bi-annually and this library was chosen as our 2023-H1 awardee.  

The total reward is equivalent to 4 licenses of the list price at https://kellermansoftware.com/products/compare-net-objects ...but we aren't about buying support so really it's up to you how you want us to contribute.  Happy to just use that method or something like https://github.com/sponsors just let us know

congrats on the win, and thanks for giving us some useful software!

**Comment by GregFinzer** [comment]
I have signed up to be sponsored.  I am just waiting for approval.

**Comment by drdamour** [comment]
@GregFinzer the sponsorship was added/funded...unclear if you need to approve it or not.
