### ISSUE TITLE
DBNull.Value exception

### ISSUE THREAD

**Issue by sezginakman** [GregFinzer/Compare-Net-Objects#29]

**Comment by GregFinzer** [comment]
@sezginakman Please create an NUnit test to reproduce the issue and a fix.

**Comment by GregFinzer** [comment]
@sezginakman How is your fix going?

**Comment by GregFinzer** [comment]
I created this test and I am not getting any exception.  Closing the issue:

        [Test]
        public void DbNullTest()
        {
            CompareLogic compareLogic = new CompareLogic();

            ComparisonResult result = compareLogic.Compare(DBNull.Value, DBNull.Value);
            if (!result.AreEqual)
                Console.WriteLine(result.DifferencesString);
        }
