### ISSUE TITLE
Wrong comparison result on non-equal objects

### ISSUE THREAD

**Issue by ycherkes** [GregFinzer/Compare-Net-Objects#292]
Using library v4.79.0, NET6.0
Given following code:

```
[Test]
public void CompareByContentTest()
{
    // Arrange
    var compareLogic = new CompareLogic
    {
        Config = new ComparisonConfig
        {
            IgnoreObjectTypes = true
        }
    };

    var expectedPerson = new { Name = "TestName"};
    object actualPerson = 5; // or new object () or string.Empty;

    ComparisonResult result = compareLogic.Compare(expectedPerson, actualPerson);
    Assert.False(result.AreEqual, result.DifferencesString);
}
```

Expected:
Objects are not equal
Actual:
Objects are equal

**Comment by ycherkes** [comment]
This one gives the inconsistent result depending on the order of comparands:

```
[Test]
public void CompareByContentTest()
{
    // Arrange
    var compareLogic = new CompareLogic
    {
        Config = new ComparisonConfig
        {
            IgnoreObjectTypes = true,
            IgnoreMissingFields = false,
			CompareChildren = true
        }
    };

    var expectedPerson = new { Name = "TestName" };
    object actualPerson = 5;

    ComparisonResult passesResult = compareLogic.Compare(actualPerson, expectedPerson);
    Assert.False(passesResult.AreEqual, passesResult.DifferencesString);

    ComparisonResult failsResult = compareLogic.Compare(expectedPerson, actualPerson);
    Assert.False(failsResult.AreEqual, failsResult.DifferencesString);
}
```

**Comment by GregFinzer** [comment]
Compare .Net Objects does not support this use case.  If you would like to see this use case supported, please implement the functionality with a unit test and create a pull request.

**Comment by ycherkes** [comment]
@GregFinzer Do you have documentation covering this use case?

**Comment by GregFinzer** [comment]
Yes, if you look at the list of supported types, object is not one of them.  
https://github.com/GregFinzer/Compare-Net-Objects

**Comment by ycherkes** [comment]
> Yes, if you look at the list of supported types, object is not one of them. https://github.com/GregFinzer/Compare-Net-Objects

Do you mean, if I replace object actualPerson = 5 with int actualPerson = 5 it should compare int with instance of anonymous type correctly?
