### ISSUE TITLE
Not a bug report: a question on how to create/install a Custom Comparer

### ISSUE THREAD

**Issue by billwoo** [GregFinzer/Compare-Net-Objects#3]
First, thanks very much for this fantastic library !  It's such a pleasure to read/study clean, well-commented code.

The structure of the implementation of Custom Comparers, and their use in CompareObjects is easy for me to grok reading the code, but I can't figure out yet how, exactly, what to create, what to sub-class, what to override, etc. so that I can define/install a custom comparer, for example: for DateTime comparisons.

thanks, Bill Woodruff

**Comment by GregFinzer** [comment]
Bill,

Please see the help file topic, Custom Comparers.

Thanks,
Greg
