### ISSUE TITLE
Nested Collection Comparer doesn't work when differing number of items in collections in objects

### ISSUE THREAD

**Issue by edatrel** [GregFinzer/Compare-Net-Objects#30]
This works well if I am comparing two objects that both have the same number of items a nested list, but if one of the objects has a different number of items (one has 2 items and another has 1 item in the same nested child list). Maybe this is due to the code's flattening of the child collections during it's compare. I wish there was a way to have it consider what is different.
For example:

`
public class Title
{
 public int ID {get;set;}
 public string Name {get;set;}
}

public class Person
{
 public List<Title> Titles
}

var one = new Person{Titles = new List<Title>(){new Title{ID = 1, Name = "One"}}};

var two = new Person{Titles = new List<Title>(){new Title{ID = 1, Name = "One"}, new Title{ID = 2, Name = "Two"}}};

var c = new CompareLogic(new ComparisonConfig(){MaxDifferences = int.MaxValue}); // find all of them

var r = c.Compare(one, two);

// r.Differences should be the "Two" element of the Person.Titles collection.
`

**Comment by GregFinzer** [comment]
See the help file under Ignoring The Order

**Comment by edatrel** [comment]
When I do that if I have a null nested list in one entity and a list with items in it instead of getting each individual nested field I only get this for the differences.Object2Value one time

System.Collections.Generic.List`1[ReliasLearning.RLMS.Model.Entities.JobTitle]

Instead of getting each individual nested property listed out like it does when the items in the lists on both objects are equal

**Comment by GregFinzer** [comment]
I have no idea what you are talking about.  Can you post some example code?

**Comment by edatrel** [comment]
`    public class DiffChild
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class DiffParent
    {
        public string Name { get; set; }

        public List<DiffChild> Children { get; set; }
    }

private void Work()
{
var list = new Dictionary<string, string>();
            var c = new CompareLogic(new ComparisonConfig()
            {
                MaxDifferences = int.MaxValue, // don't just stop at the first difference - find all of them
                IgnoreCollectionOrder = true, // allow differing number of objects
            });
            var r = c.Compare(new DiffParent(), new DiffParent() {Name = "foo", Children = new List<DiffChild>() {new DiffChild() {ID = 1, Name = "moo"} } });
            foreach (var i in r.Differences)
            {
                list.Add($"OLD{(i.PropertyName.Length > 1 ? i.PropertyName.Substring(1) : i.PropertyName)}",
                    i?.Object1Value);
                list.Add(i.PropertyName.Length > 1 ? i.PropertyName.Substring(1) : i.PropertyName, i?.Object2Value);
            }

![values](https://cloud.githubusercontent.com/assets/25351564/22334160/44259f18-e39f-11e6-9716-7eb46b5efd5b.png)

}
`

**Comment by GregFinzer** [comment]
I see.  I agree that would be a nice feature to treat the null the name as an empty list.  Go ahead and add an NUnit test and implement this functionality.  Please make it a configuration option so it does not break other people's expected results.

**Comment by GregFinzer** [comment]
@edatrel How is your fix going?

**Comment by edatrel** [comment]
I'm in a holding pattern on the task that has to do with this code at the moment - have to wait until they give me the go-ahead to go back to it. Sorry about that.

________________________________

**Comment by GregFinzer** [comment]
Waited long enough for the fix.  Closing the issue.

**Comment by oghenez** [comment]
> This works well if I am comparing two objects that both have the same number of items a nested list, but if one of the objects has a different number of items (one has 2 items and another has 1 item in the same nested child list). Maybe this is due to the code's flattening of the child collections during it's compare. I wish there was a way to have it consider what is different.
> For example:
> 
> `
> public class Title
> {
> public int ID {get;set;}
> public string Name {get;set;}
> }
> 
> public class Person
> {
> public List<Title> Titles
> }
> 
> var one = new Person{Titles = new List<Title>(){new Title{ID = 1, Name = "One"}}};
> 
> var two = new Person{Titles = new List<Title>(){new Title{ID = 1, Name = "One"}, new Title{ID = 2, Name = "Two"}}};
> 
> var c = new CompareLogic(new ComparisonConfig(){MaxDifferences = int.MaxValue}); // find all of them
> 
> var r = c.Compare(one, two);
> 
> // r.Differences should be the "Two" element of the Person.Titles collection.
> `

This library https://github.com/ValeraT1982/ObjectsComparer seems to handle this error well

**Comment by GregFinzer** [comment]
@oghenez This should help you:  https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths

**Comment by GregFinzer** [comment]
@oghenez If that does not help then feel free to implement the new functionality.
