### ISSUE TITLE
Ignoring private dotnet internals

### ISSUE THREAD

**Issue by emalfroy** [GregFinzer/Compare-Net-Objects#301]
Hi,
I have a question about ignoring private dotnet internals. When you enable ComparePrivateFields, it compares on private members on dotnet type of List. e.g. Capacity is different. When adding/removing items to the list for example.
I only want to compare private fields of my own types.
```
var compareLogic = new CompareLogic(new ComparisonConfig
{
    ComparePrivateFields = true,
});
```
How can I achieve this?

Thanks in advance

Greetings

**Comment by jvandaal** [comment]
It works! Thanks!
