### ISSUE TITLE
Add API for removing type comparers

### ISSUE THREAD

**Issue by mattbrailsford** [GregFinzer/Compare-Net-Objects#306]
I've been debugging an issue in a project I'm building on .NET 8 whereby when I compare an object I was constantly getting an exception `Could not load file or assembly System.Drawing.Common v6.0.0` and I couldn't for the life of me figure out why this dependency would be needed.

In debugging, it looks like it  boils down to the `FontComparer` which compares the `Font` type as found in `System.Drawing.Common`.

In my project, I can guarantee that my entities will never have a property of the `Font` type and so I would like to be able to remove the `FontComparer` from the list of `RootComparer` type comparers. Unfortunately the `TypeComparers` property on the `RootComparer` is internal and so I'm currently having to use some reflection to do this.

It would be great if, maybe in the `CompareLogic.Config` we could also provide a list of TypeComparers to exclude.

**Comment by mwinkler** [comment]
Same issue here....

**Comment by knoxi** [comment]
+1 here with latest .net 7

**Comment by GregFinzer** [comment]
I will do a deploy by Tuesday.

**Comment by GregFinzer** [comment]
Deployed.  Closing issue.
