### ISSUE TITLE
Comparing different type ints throws an exception.

### ISSUE THREAD

**Issue by jcd-zillow** [GregFinzer/Compare-Net-Objects#308]
I'm trying to compare two objects which have the same signatures but often different types.  I have no control on the objects, as these objects are defined by structures I don't control.  This simplified example generates the error in 4.82.0 using version 6 of the .net framework:

 ```
private class DbTest
 {
     public int? A { get; set; } = 1;
 }

 private class ApiTest
 {
     public Int64 A { get; set; } = 1;
 }

    public void TestCompare()
    {
        var db = new DbTest();
        var api = new ApiTest();


        var compare = new CompareLogic()
        {
            Config = new ComparisonConfig() { ActualName = "API", ExpectedName = "DB", IgnoreObjectTypes = true }
        };
        var result = compare.Compare(db, api);

    }
```

EXPECTED:

I would expect that since I ignore types, it should show the two values are equal (no differences).  If differences were to appear, I'd expect them as part of a result object, not an exception.

ACTUAL:  

An exception occurs.  This is an example of the exception you might see:

Message: 
System.ArgumentException : Object must be of type Int32.

  Stack Trace: 
Int32.CompareTo(Object value)
SimpleTypeComparer.CompareType(CompareParms parms)
RootComparer.PerformBaseTypeComparison(CompareParms parms, Type t1, Type t2)
RootComparer.Compare(CompareParms parms)
PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
ClassComparer.CompareType(CompareParms parms)
RootComparer.PerformBaseTypeComparison(CompareParms parms, Type t1, Type t2)
RootComparer.Compare(CompareParms parms)
CompareLogic.Compare(Object expectedObject, Object actualObject)
SampleTest.TestCompare() line 68

**Comment by GregFinzer** [comment]
This is not something that is supported by the library.  Feel free to implement with unit tests and create a pull request.
