### ISSUE TITLE
Need to generate "diff" that has ALL nestsed properties

### ISSUE THREAD

**Issue by edatrel** [GregFinzer/Compare-Net-Objects#31]
We'd like to just get the flattened diff list of all nested properties in one object
`
public class Title
{
public int ID {get;set;}
public string Name {get;set;}
}

public class Person
{
public string FirstName {get;set;}
public string LastName {get;set;}
public List<Title> Titles {get;set;}
}

var one = new Person{FirstName = "First", LastName = "Last", Titles = new List<Title>(){new Title{ID = 1, Name = "One"}}};

var c = new CompareLogic(new ComparisonConfig(){MaxDifferences = int.MaxValue}); // find all of them

var r = c.Compare(one, new Person());</p> <p>// r.Differences should include all nested properties
`

**Comment by GregFinzer** [comment]
See the ComparisonResult.Differences property
