### ISSUE TITLE
WinMergeU.exe not found, if installed to non-default directory

### ISSUE THREAD

**Issue by MagicAndre1981** [GregFinzer/Compare-Net-Objects#33]
`winMergeReport.LaunchApplication` trows `FileNotFoundException("WinMergeU.exe")` if WinMergeU.exe is installed to non-default directory.

Windows already store the correct location in registry under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\WinMergeU.exe` so your search (`public string FindWinMerge()`) is not required.

**Comment by GregFinzer** [comment]
Good call out.  Thanks for letting me know.

**Comment by GregFinzer** [comment]
Fixed:
https://github.com/GregFinzer/Compare-Net-Objects/commit/d1bb913c0980229c0e4e465868c7d0160ac5da8a
