### ISSUE TITLE
Get friendly name form DisplayName in ViewModel

### ISSUE THREAD

**Issue by jonathanS8080** [GregFinzer/Compare-Net-Objects#35]
Hi,
I have a Model variable called FirstName which has a DisplayName of First name. is there a way to get the Display Name from the model which makes the Audit a bit more friendly?
Thanks

Jon

**Comment by GregFinzer** [comment]
Jon,

Hey Jon, could you post an example please?  Is this an attribute?

One of the things you could do I loop through the list of differences in the result and then provide some sort of translation dictionary.

Thanks,
Greg

**Comment by GregFinzer** [comment]
@jonathanS8080 No response.  Closing issue.
