### ISSUE TITLE
Comparing list of items containing a nullable decimal value gives difference when it shouldn't

### ISSUE THREAD

**Issue by jdextraze** [GregFinzer/Compare-Net-Objects#36]
Given I have a class with a nullable decimal property
```
class MyItem
{
	public decimal? NullableDecimal { get; set; }
}
```
When I compare a decimal value of 10m with a decimal value of 10.0m in a list, I get a difference.

Example unit test using fluent assertions:
```
var config = new ComparisonConfig
{
	IgnoreCollectionOrder = true,
	MaxDifferences = int.MaxValue
};
var basicComparison = new CompareLogic { Config = config };

basicComparison.Compare(
		new List<MyItem>
		{
			new MyItem { NullableDecimal = 10.0m }
		},
		new List<MyItem>
		{
			new MyItem { NullableDecimal = 10m }
		}
	)
	.Differences.Should()
	.BeEmpty();
```
this test fails but it shouldn't.

**Comment by GregFinzer** [comment]
My apologies.  It will be a while before I can get to any defects.

**Comment by jdextraze** [comment]
It's alright. We removed the nullable from the decimal for now and it fix our issue. I might take a look at it myself since I know what cause the issue.

**Comment by mihasic** [comment]
https://github.com/GregFinzer/Compare-Net-Objects/pull/37

**Comment by mihasic** [comment]
My pull request is more like a workaround than a proper fix, but I did not feel like making most of the code immutable. If to make most of comparison immutable, it would be possible to reuse typed comparers.

**Comment by GregFinzer** [comment]
Merged.
