### ISSUE TITLE
Do not install the chm file into the target project.

### ISSUE THREAD

**Issue by PhilipDaniels** [GregFinzer/Compare-Net-Objects#39]
Please don't do this, I just installed Compare-Net-Objects into library A which is used by about 20 other libraries (including test projects!), and now I have 20 copies of this binary blob cluttering up my projects and Git repos.

**Comment by manchas** [comment]
+1, that's really annoying.

**Comment by GregFinzer** [comment]
I am still thinking about an alternative.  When the help file was not in there, I received frequent emails asking me where the help file was.

**Comment by GregFinzer** [comment]
Fixed in version 3.08
https://www.nuget.org/packages/CompareNETObjects/3.8.0
