### ISSUE TITLE
Possible IgnoreCollectionOrder issue

### ISSUE THREAD

**Issue by hammie1010** [GregFinzer/Compare-Net-Objects#4]
If Config.IgnoreCollectionOrder = true and I'm comparing two lists, the comparison result only compares the count of the list and not the objects within the lists themselves. How would I compare all the items in a list against each other?

Ex:

            compareObjects.Config.MaxDifferences = 999999999;
            compareObjects.Config.TreatStringEmptyAndNullTheSame = true;
            compareObjects.Config.IgnoreCollectionOrder = true;
            compareObjects.Config.CompareChildren = true;
            compareObjects.Config.CollectionMatchingSpec = new Dictionary<Type, IEnumerable<string>>(){{typeof(string),new List<string>{"EntityId"} }};

            var testResult = compareObjects.Compare(previousRecords.ToList(), mergeResult.ToList());

**Comment by hammie1010** [comment]
Oh I see - I setup the CollectionMatchingSpec wrong.

**Comment by GregFinzer** [comment]
I am glad you figured it out.
