### ISSUE TITLE
Type specific IgnoreCollectionOrder property

### ISSUE THREAD

**Issue by rmanish04** [GregFinzer/Compare-Net-Objects#41]
I have successfully used IgnoreCollectionOrder property to compare two lists that may not necessarily be in the same order. However, this applies to all collections that this instance of CompareLogic may encounter. 

This means if an item in a Collection has a member that is a List, I have no way to specify that for this member List I do not want to IgnoreCollectionOrder.

Example: 

```
public class MyClass
{
	public MyClass(string id, List<string> stringList)
	{
		this.Id = id;
		this.StringList = stringList;
	}

	public string Id { get; set; }

	public List<string> StringList { get; set; } 
}

var compareLogic = new CompareLogic();
compareLogic.Config.IgnoreCollectionOrder = true;

var obj1 = new List<MyClass>();
obj1.Add(new MyClass("mem1", new List<string>() {"foo", "bar"}));
obj1.Add(new MyClass("mem2", new List<string>() {"foo", "bar"}));

var obj2 = new List<MyClass>();
obj2.Add(new MyClass("mem2", new List<string>() {"bar", "foo"}));
obj2.Add(new MyClass("mem1", new List<string>() { "bar", "foo" }));

var result = compareLogic.Compare(obj1, obj2);
Assert.IsFalse(result.AreEqual, result.DifferencesString);
```

In the above example, I don't care about the order of members of type MyClass - but once I find a member with Id "mem1" (by using collectionspec) , I want that the list of strings be in the exact same order. So {"bar", "foo"} is not the same as {"foo", "bar"}.

I couldn't find a way to specify this. Is this a feature that can be added?

**Comment by GregFinzer** [comment]
@rmanish04 Sure that sounds like a good feature.  Please implement.  Please create a corresponding NUnit test with the code and then I will merge in the changes.
