### ISSUE TITLE
Exception retrieving Current enumerator property of non-enumerable entity

### ISSUE THREAD

**Issue by ekovalik** [GregFinzer/Compare-Net-Objects#43]
While parsing deeply nested Lists, an InvalidOperationException exception is thrown when retrieving the Current enumerator property of an entity that is not a list (i.e. a child leaf object). This results in the system incorrectly returning a Not Match condition when in fact the Lists are equal (and causes several unit tests to fail).

See Pull Request #42 for potential fix.

**Comment by GregFinzer** [comment]
Merged
