### ISSUE TITLE
Returns Exception Because of Null

### ISSUE THREAD

**Issue by mmsyther** [GregFinzer/Compare-Net-Objects#45]
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in KellermanSoftware.Compare-NET-Objects.dll
Additional information: Object reference not set to an instance of an object.

There is the error: Here is the code snippet. dt[0] and dt[1] are the data tables being compared.
 CompareLogic myCompareLogic = new CompareLogic();
            ComparisonConfig myComparsionConfig = new ComparisonConfig();
            ComparisonResult myComparsionResult = new ComparisonResult(myComparsionConfig);
            RootComparer myRootComparer = new RootComparer();
            DataTableComparer myDataTableComparer = new DataTableComparer(myRootComparer);
            CompareParms myCompareParms = new CompareParms();
            //myCompareParms.Object1Type.
            myCompareParms.Object1 = dt[0];
            myCompareParms.Object2 = dt[1];
            myDataTableComparer.CompareType(myCompareParms);
            myCompareLogic.Config.MaxDifferences = 1000;
            myComparsionResult = myCompareLogic.Compare(dt[0], dt[1]);

**Comment by GregFinzer** [comment]
Please create a test that can be run.

**Comment by GregFinzer** [comment]
Looking at the code above, you are instantiating the DataTableComparer.  It should not be used.  Only the myCompareLogic.Compare
