### ISSUE TITLE
netstandard1.6 for .NET Core version

### ISSUE THREAD

**Issue by fubar-coder** [GregFinzer/Compare-Net-Objects#46]
Is there a reason why the library supports only netstandard1.6 and up? Shouldn't it be possible to target netstandard1.0 (or at least 1.3)? netstandard1.6 isn't currently supported by any .NET Framework (not even 4.7).

**Comment by GregFinzer** [comment]
@fubar-coder I will change the distribution to something earlier.

**Comment by GregFinzer** [comment]
@fubar-coder I changed it to version 1.3.  It can't go any lower since the binding flags are not in 1.0 to 1.2.  Please test.

**Comment by fubar-coder** [comment]
I found the issue that `LogicEqualityComparer.cs` is missing from the .NET Core project.
I also have the suggestion to remove the `obj\` folder from source control.
Most of the tests did work as expected (with the exception of tests affected by #49 .

**Comment by GregFinzer** [comment]
@fubar-coder Done.  Please check again.

**Comment by GregFinzer** [comment]
@fubar-coder Deployed to Nuget
