### ISSUE TITLE
Enumeration has already started or has already finished when IgnoreCollectionOrder = true

### ISSUE THREAD

**Issue by rndthoughts** [GregFinzer/Compare-Net-Objects#47]
I am using the following code:

```
var compareLogic = new CompareLogic();

var specSubjectsTaught =new Dictionary<Type, IEnumerable<string>>
{
    {typeof(SubjectsTaughtModel), new[] {"Id"}}
};

compareLogic.Config.IgnoreCollectionOrder = true;
compareLogic.Config.CollectionMatchingSpec = specSubjectsTaught;

var result = compareLogic.Compare(originalEntity, modifiedEntity);
```

SubjectsTaughtModel is a type used within a list on one of the property of my object.  When i set IgnoreCollectionOrder to true, the Compare method throws:

`
"Enumeration has already started or has already finished"`

**Comment by GregFinzer** [comment]
@rndthoughts I think you will need to change your IEnumerable into a List
