### ISSUE TITLE
Setting SkipInvalidIndexers also skips valid indexers (master)

### ISSUE THREAD

**Issue by fubar-coder** [GregFinzer/Compare-Net-Objects#49]
Setting `SkipInvalidIndexers` to `true` also skips valid indexers. The problem was found while running the tests with `DataTable`s like `DataTableNegativeColumnNameTest`. The indexers for the relations also contain an indexer that accepts a string. This one should be ignored.

**Comment by GregFinzer** [comment]
@fubar-coder The functionality is correct.  It does not support non-integer indexers.  Closing issue.

**Comment by fubar-coder** [comment]
@GregFinzer Are you sure that it is correct that setting `SkipInvalidIndexers` to `true` also skips valid indexers? This really doesn't sound right to me.

**Comment by GregFinzer** [comment]
Changed
