### ISSUE TITLE
Ignore properties

### ISSUE THREAD

**Issue by jordyvaneijk** [GregFinzer/Compare-Net-Objects#5]
Is there a possibility to ignore certain properties in a class? I could not find it
lets say i have a poco Person

`public class Person
{
    public int Id { get; set; }
    public string GivenName { get; set; }
    public string LastName { get; set; }
    public string SomeProperty { get; set; }
}`

I want to ignore the SomeProperty during comparison how can i do that?

**Comment by GregFinzer** [comment]
Yes.  Please see the Config.MembersToIgnore

**Comment by jordyvaneijk** [comment]
I Saw that one but isn't it possible or a very nice to have to do this by attributes because if you create an generic solution you don't want to tell the comparer to ignore a field by supplieing it a list of strings i think.

Better would by something like JSON.net has JSONIgnore or XMLIgnore etc...

**Comment by GregFinzer** [comment]
Sure there is that option too.  Just add whatever attribute type you want to AttributesToIgnore and then decorate it.

**Comment by GregFinzer** [comment]
There is a built in one called CompareIgnoreAttribute that you can add to the AttributesToIgnore collection.

**Comment by jordyvaneijk** [comment]
Thank you so much, i was looking for that!

**Comment by desertrambler** [comment]
I found that attribute in your test class, which isn't included in my project when I include the Nuget package. Are you just saying I should copy that class to my code so I can use it?

**Comment by GregFinzer** [comment]
Sure that is fine.  You can use whatever attribute you would like.
