### ISSUE TITLE
netstandard1.6 dll is not signed

### ISSUE THREAD

**Issue by SergeyKanzhelev** [GregFinzer/Compare-Net-Objects#52]
Getting error:

```
CSC : warning CS8002: Referenced assembly 'KellermanSoftware.Compare-NET-Objects-Core, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. 
```
when trying to use it for `netcoreapp1.1` unit tests project

**Comment by GregFinzer** [comment]
Sergey,

It will take a while until I can get to these issues.

Thanks,
Greg

**Comment by SergeyKanzhelev** [comment]
Sure. Thanks! We are building the same code for multiple target frameworks so we are OK now - tests disabled for one of the platform. 

BTW, the reason we need unit tests assemblies to be signed is that we have use `InternalsVisibleTo` so test projects can access internal objects for mocking and verifying.

**Comment by GregFinzer** [comment]
Signed.  Version 3.10 is up on Nuget

**Comment by SergeyKanzhelev** [comment]
Thanks!
