### ISSUE TITLE
Compare typed and dynamic objects

### ISSUE THREAD

**Issue by Ephesos** [GregFinzer/Compare-Net-Objects#53]
I tried comparing a dynamic object and one with known type, but the comparer seems to fail at this task.
Below is a sample I tried - required json.net.

I also played with the IgnoreObjectTypes flag, but it seems to always return true if the two object types are different at the root.

```
class Program
    {
        static string json =
        @"
        {
        	""Name"": ""Jim"",
        	""Surname"": ""Doe"",
        	""Interests"": [""Swimming"", ""Books"", ""Biking""],
        	""Stuff"": {
        		""Foo"": ""bar"",
        		""Hmm"": 42
        	}
        }";

        static void Main(string[] args)
        {
            dynamic newHuman = JsonConvert.DeserializeObject(json);

            var human = new Human
            {
                Name = "John",
                Surname = "Doe",
                Interests = new string[] { "Swimming", "Books", "Biking" },
                Stuff = new Stuff
                {
                    Foo = "bar",
                    Hmm = 42
                }
            };

            var compareLogic = new CompareLogic(new ComparisonConfig { IgnoreObjectTypes = true });
            var result = compareLogic.Compare(newHuman, human);
        }

        private class Human
        {
            public string Name { get; set; }
            public string Surname { get; set; }
            public string[] Interests { get; set; }
            public Stuff Stuff { get; set; }
        }

        private class Stuff
        {
            public string Foo { get; set; }
            public int Hmm { get; set; }
        }
    }
```

**Comment by GregFinzer** [comment]
It looks like you are comparing Jim Doe and John Doe which are different.

**Comment by Ephesos** [comment]
That is why I raised the issue. If you run the sample, the **result.AreEqual** property is **true**. 
From my testing this is what happens:

- With IgnoreObjectTypes = false, the resut.AreEqual is false because the two root types are different, and no property value checks are needed.
- With IgnoreObjectTypes = true, the resut.AreEqual is always true, but I didn't have time to debug the library and check why.

**Comment by GregFinzer** [comment]
Yep, sounds like a defect.  Please create a fix with a unit test and I will merge in the pull request.

**Comment by GregFinzer** [comment]
I spent several hours on this today.  It did not support dynamic objects at all.  The reflection works completely different for dynamic objects.  The new version is checked in and up on nuget version 3.10

        [Test]
        public void DifferentDynamicObjectsShouldNotBeEqual()
        {
            dynamic human1 = new System.Dynamic.ExpandoObject();
            human1.Name = "John";
            human1.Surname = "Doe";
            human1.Interests = new string[] {"Swimming", "Books", "Biking"};
            human1.Stuff = new System.Dynamic.ExpandoObject();
            human1.Stuff.Foo = "bar";
            human1.Stuff.Hmm = 42;

            dynamic human2 = new System.Dynamic.ExpandoObject();
            human2.Name = "Jane";
            human2.Surname = "Doe";
            human2.Interests = new string[] { "Swimming", "Books", "Biking" };
            human2.Stuff = new System.Dynamic.ExpandoObject();
            human2.Stuff.Foo = "bar";
            human2.Stuff.Hmm = 42;

            var oc = new CompareLogic();
            oc.Config.IgnoreObjectTypes = true;
            oc.Config.CompareChildren = true;

            var result = oc.Compare(human1, human2);
            Console.WriteLine(result.DifferencesString);
            Assert.IsFalse(result.AreEqual);
        }
