### ISSUE TITLE
Use of WeakReference in Difference class means diff values can get set to null at any time

### ISSUE THREAD

**Issue by PhilipDaniels** [GregFinzer/Compare-Net-Objects#54]
Small unit tests probably won't trigger a garbage collection. On the other hand, I have a large DTO object with many hundreds of properties, many on nested objects. I have written a fuzzer which sets the fields of this structure to random values. I then run instances of these DTOs through your lib in a loop.

The following behaviour is observed.

After the comparison has completed and the differences have been returned, several diffs are observed to have the old and new values (`Difference.Object1` & `Difference.Object2`) set to null. It can happen with value types as well as object types.

The problem is that the `Difference` class uses a `WeakReference`. https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/weak-references A WeakReference does not guarantee the value will be available - the garbage collector can come in under you at any time and collect the object, and your `WeakReference` will then become `null`.

n.b. The problem is difficult to reproduce in the debugger because garbage collections do not run at predictable times.

I believe the fix is simply to change the 4 properties in `Difference` to be `object` and remove the corresponding `new WeakReference` calls.

**Comment by PhilipDaniels** [comment]
FYI I have made a fork that contains that change. https://github.com/PhilipDaniels/Compare-Net-Objects

I have tested it in my large-DTO code base and it fixes the problem. I cannot easily give you that test though because it contains proprietary information from work.

**Comment by GregFinzer** [comment]
Took out references to weak reference.  This will be in a future version.
