### ISSUE TITLE
Get a TargetParameterCountException on comparing a class with indexer.

### ISSUE THREAD

**Issue by AlPecin** [GregFinzer/Compare-Net-Objects#55]
Hi,

I have attached an unit test class to reproduce this effect.

[TargetParameterCountException.zip](https://github.com/GregFinzer/Compare-Net-Objects/files/1302651/TargetParameterCountException.zip)

**Comment by elmojo** [comment]
I too am seeing this error "System.Reflection.TargetParameterCountException: Parameter count mismatch".

It is failing on a property that derives from "IDictionary<string, List<string>>".

**Comment by GregFinzer** [comment]
It will be a long while until I can look at this issue.

**Comment by GregFinzer** [comment]
I ran the tests for version 3.10 and it is working fine.  I checked in your test as part of the solution.

**Comment by elmojo** [comment]
Awesome.  I downloaded the latest nuGet and uncommented my failing tests and they all pass now.  Thanks!
