### ISSUE TITLE
How to use Config.InterfaceMembers with generics ?

### ISSUE THREAD

**Issue by Micke3rd** [GregFinzer/Compare-Net-Objects#57]
Hi Greg,
`compareLogic.Config.InterfaceMembers` is a nice property to work with mocks e.g. in unittesting.
I come to it limits, if i work with generic collections, cause interfaces like ICollection<> / IList<> dont fit to a property of concret type like `ICollection<integer>`
Because of that to define `InterfaceMembers.Add(typeof(ICollection<>))`  wouldnt help to ignore the specific class behind the collection interface.
I could say `InterfaceMembers.Add(typeof(ICollection<int>))`, of course, but my model has to many of that collections respectively i dont wanna think about all combinations.

ICollection<> dont inherits ICollection
therefore `InterfaceMembers.Add(typeof(ICollection))`  wouldnt help too.

Do u have any suggestions how to solve that issue :-) ?

**Comment by GregFinzer** [comment]
Can you create an example test for me to see what you are doing?

**Comment by GregFinzer** [comment]
Did not give example.  Closing issue.
