### ISSUE TITLE
Ability to ignore certain structs? Like Guid?

### ISSUE THREAD

**Issue by desertrambler** [GregFinzer/Compare-Net-Objects#6]
I have a need to be able to ignore all Guids in my class comparisons. I finally realized that adding typeof(Guid) to the ClassTypesToIgnore doesn't work because Guid is a struct. As a workaround, most of my Guids are for properties named "Id", so I added "Id" to my MembersToIgnore, but I was wondering if there is a good way to ignore ALL Guids (or other struct)?

**Comment by GregFinzer** [comment]
Cindy,

Unfortunately there is no built in way to do this.  I do think that is a good idea and other people would need the same thing.  If you would like, add the property IgnoreGuids to the ComparisonConfig and implement.  I will be happy to merge that functionality in.

DesertRambler is a cool handle but I think that DessertHandler would be more delicious.  :)

Thanks,
Greg
