### ISSUE TITLE
CollectionMatchingSpec on base object

### ISSUE THREAD

**Issue by Cezus** [GregFinzer/Compare-Net-Objects#61]
Hi,

We have a lot of DTO's we want to compare (like 120 of them) and they have all one thing in common and that is a base class where the identifier property is placed in. The thing is that we want to compare two unordered lists of these objects. When I configure the following:

                CollectionMatchingSpec = new Dictionary<System.Type, IEnumerable<string>>()
                {
                    {
                        typeof(BasePuicEntity),
                        new List<string>() { "Puic" }
                    }
                },
                IgnoreCollectionOrder = true

It does not work because in the example above I entered the type of the base class. When I replace the base class with the concrete implementation of this base class, named 'Track', the comparison is working.

I created a pull request that solves this case.

With kind regards,

Cees

**Comment by GregFinzer** [comment]
I will look at this someday.  I am very busy.  Sorry.

**Comment by Cezus** [comment]
No problem, I understand. Hope I can make it faster for you by presenting the solution =]

**Comment by GregFinzer** [comment]
Hey I merged in the change but it is missing the class DeriveFromOfficer.  Can you post that?

**Comment by Cezus** [comment]
Great! Okey weird.. I'm now on a train, I will post it in a few hours. Sorry about that

**Comment by Cezus** [comment]
I created a new Pull Request for the missing class, =] #66

**Comment by GregFinzer** [comment]
I will get back to this several months later after there are around 10 more issues logged.

**Comment by GregFinzer** [comment]
Done
