### ISSUE TITLE
Validation fails while ignoring class types.

### ISSUE THREAD

**Issue by Cezus** [GregFinzer/Compare-Net-Objects#63]
The following unittest I created, shows the bug I found. While having two list to compare with different object types in it, the validation fails when the ClassTypesToIgnore are having different ID's.

If you copy the code below to ConfigTests.cs and run it you will see that the validation fails. But when you give both the Officers the same ID the test will succeed. (Please note that the officers names are also different.)

What do you think of it?

```c#
        [Test]
        public void ClassTypeInListIgnorePositive()
        {
            var comparisonConfig = new ComparisonConfig()
            {
                MaxDifferences = int.MaxValue,
                MembersToIgnore = new List<string>() { "Type" },
                ClassTypesToIgnore = new List<Type>() { typeof(Officer) }, 
                CollectionMatchingSpec = new Dictionary<System.Type, IEnumerable<string>>()
                {
                    {
                        typeof(Officer),
                        new List<string>() { "ID" }
                    },
                    {
                        typeof(Person),
                        new List<string>() { "ID" }
                    }
                },
                TreatStringEmptyAndNullTheSame = true,
                IgnoreCollectionOrder = true
            };

            _compare.Config = comparisonConfig;

            var list1 = new List<object>();
            var list2 = new List<object>();

            Officer p1 = new Officer();
            p1.ID = 2;
            p1.Name = "Greg";
            p1.Type = Deck.AstroPhysics;

            Officer p2 = new Officer();
            p2.ID = 1;
            p2.Name = "Leyla";
            p2.Type = Deck.Engineering;

            Person p3 = new Person();
            p3.ID = 3;
            p3.Name = "Henk";
            p3.DateCreated = DateTime.Now;

            Person p4 = new Person();
            p4.ID = 3;
            p4.Name = "Henk";
            p4.DateCreated = p3.DateCreated;

            list1.Add(p1);
            list1.Add(p3);
            list2.Add(p2);
            list2.Add(p4);

            var result = _compare.Compare(list1, list2);
            Assert.IsTrue(result.AreEqual, result.DifferencesString);
        }

```

**Comment by GregFinzer** [comment]
Cezus, that is the expected functionality.  It is matching by ID

**Comment by Cezus** [comment]
That is true but it should ignore the objects of type Officer, right? Even if the ID's are different.


`                ClassTypesToIgnore = new List<Type>() { typeof(Officer) },`

**Comment by GregFinzer** [comment]
That is just really wacky.  Why would you compare two lists and want to ignore one of the objects.  What would you compare the first object to?

**Comment by Cezus** [comment]
I think that is a good question.. I think that I would expect that the list would be treated as if the classtypestoignore are not part of the list.. so in the example above it would Except the Officers from both lists and only compare the persons. Both list's first item would be a Person.

**Comment by GregFinzer** [comment]
Okay, I will implement.  I will get back to this several months later after there are around 10 more issues logged.

**Comment by GregFinzer** [comment]
Implemented
