### ISSUE TITLE
Excluding child collections

### ISSUE THREAD

**Issue by desertrambler** [GregFinzer/Compare-Net-Objects#7]
I have a complex object that has a child collection that I need to exclude from comparing. I have not been able to exclude it by either the collection type itself (typeof(HashSet<childType>)), nor by the element type (typeof(childType)) in the ClassTypesToIgnore. The only way I was able to exclude it was by member name in the MembersToIgnore list.

Is there a better way?

Cindy

**Comment by GregFinzer** [comment]
Cindy,

Did you try using the AttributesToIgnore?

Thanks,
Greg

**Comment by desertrambler** [comment]
I wasn’t sure how to use that. Do you have a list of attributes defined in your project that are for this purpose? Or are we just supposed to use whatever attributes .NET gives us?

**Comment by GregFinzer** [comment]
You can add whatever attribute you want or use something in .NET.  There is also one built in.  See this question:

https://github.com/GregFinzer/Compare-Net-Objects/issues/5
