### ISSUE TITLE
get root object of difference

### ISSUE THREAD

**Issue by shakazulu89** [GregFinzer/Compare-Net-Objects#70]
when looping differences how would i get the root object of a deeply nested item? parentobject property only goes up on level .. something with the breadcrumb i assume, how do i walk up the path until the root?im missing something simple probably :)

**Comment by shakazulu89** [comment]
for clarity:
i have this breadcrumb: 

> .product_specs[key:BLOMB:DWT25502SS].classification.this_item_in_other_colors.LongLength

i want to get the key of the root... 

i mean i managed with string manipulation for now but has to be better way hehe...

**Comment by GregFinzer** [comment]
There is no better way.  It does not keep track of the list of all the parents.

**Comment by shakazulu89** [comment]
ok greg thanks for the follow up!
