### ISSUE TITLE
Possible bug in CompareLogic.cs

### ISSUE THREAD

**Issue by Mansari** [GregFinzer/Compare-Net-Objects#73]
Hi. We noticed this under SetupWithAppConfigSettings in CompareLogic.s

            if (Settings.Default.MembersToIgnore != null)
            {
                foreach (var attribute in Settings.Default.MembersToIgnore)
                {
                    Config.AttributesToIgnore.Add(Type.GetType(attribute));
                }
            }

It seems although you reference the members to ignore property, you load the settings into attributes to ignore. Not sure if this is a typo or intended, but just noting it.

**Comment by GregFinzer** [comment]
Yes, that is a dreaded copy and paste error.

**Comment by GregFinzer** [comment]
Fixed
