### ISSUE TITLE
PropertyName has a period in front of it

### ISSUE THREAD

**Issue by Ibrahim-Islam** [GregFinzer/Compare-Net-Objects#74]
```
Difference propName = diff.PropertyName //propName == ".SomePropertyName" 
```

**Comment by GregFinzer** [comment]
Fixed

**Comment by TimSirmovics** [comment]
How was this classed as a bug?
After updating the NuGet package I had to go over my code base and update every property name string for this libary to no longert include the leading period.

**Comment by dominiquesamson** [comment]
Same as TimSirmovics here, we were a bit confused about that one, we thought that it was some jsonpath style convention.
