### ISSUE TITLE
Porting some older code to .NET Standard

### ISSUE THREAD

**Issue by tudorserbanconnatix** [GregFinzer/Compare-Net-Objects#75]
Hello,
I am porting some older code that was based on v3.5 of CompareNetObjects to a .NET Standard library that uses v4.3. The code is now failing to build because some properties are missing in the new version, namely:

Difference.DisplayName
Difference.ApprovalDifference
ComparisonConfig.AttributesToInclude
ComparisonConfig.DisplayAttribute

Any guidance on what to do in this case or what they were supposed to be used for originally? Thanks.

**Comment by GregFinzer** [comment]
Sorry, no time to leave a detailed response.  Look at the source code and the tests.
