### ISSUE TITLE
ComparisonConfig.IgnoreObjectTypes should not handle properties diff

### ISSUE THREAD

**Issue by janid1967** [GregFinzer/Compare-Net-Objects#78]
I want to be able to compare 2 objects of different types, and see if they have exact same public properties, including values in these properties. This can't be done since I need to set IgnoreObjectTypes = true to be able to compare objects of different types. 

Then IgnoreObjectTypes also skip handling properties in PropertyComparer. If object A has property X, but object B don't have property X, PropertyComparer.CompareProperty don't report this as a diff. I want this to be reported as a diff

`if (parms.Config.IgnoreObjectTypes && secondObjectInfo == null)
                return;
`

I also want that existing props in object B, that misses in object A, is reported as a diff

**Comment by GregFinzer** [comment]
@janid1967 This would be a new feature that there would need to be a new config option.  Please add a new Config option called ShowTypeDifferences and default to false.  When it is true then add the difference in types.  Please also create a corresponding NUnit test.  I will merge in your pull request.

**Comment by GregFinzer** [comment]
@janid1967 How is the implementation for this feature going?  Do you plan to create a pull request soon?

**Comment by janid1967** [comment]
I don't have any plans to do it in near future. Busy with other things...

**Comment by GregFinzer** [comment]
@janid1967 okay.  I will close this card.  You can open it again later once you implement the functionality.
