### ISSUE TITLE
"You must add a reference to assembly 'KellermanSoftware.Compare-NET-Objects-Core, Version=4.4.0.0..."

### ISSUE THREAD

**Issue by moconnell** [GregFinzer/Compare-Net-Objects#81]
I have a nuget package that references Compare-Net-Objects v4.3.0 - I have just converted this to target netstandard2.0. 

I am now trying to reference this package from a project that targets .NET Framework 4.6.2 and am receiving the following error:

```
Error 	CS0012	The type 'ComparisonResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'KellermanSoftware.Compare-NET-Objects-Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=dccbd7ce7d6a58c0'.
```

That version number does not even exist yet!

Please advise.

**Comment by GregFinzer** [comment]
Typically, when you get that error in Visual Studio, you are referencing an assembly with a higher version.  So if you have a .NET Framework 3.5 project, you are referencing a .NET Framework 4.0 project.
