### ISSUE TITLE
NuGet package has a leading zero

### ISSUE THREAD

**Issue by PhilipDaniels** [GregFinzer/Compare-Net-Objects#84]
```
package id="CompareNETObjects" version="4.04.0.0" targetFramework="net45" />
```

This is non-standard and is causing problems in NuGet in VS2015, upgrades of packages sometimes fail.

**Comment by GregFinzer** [comment]
@PhilipDaniels this is going to take a very long time to fix as it affects the base build process.

**Comment by PhilipDaniels** [comment]
Hi @GregFinzer,

You might just need to update your version of NuGet. It looks like they made some changes in this area. Haven't dug in detail, but this thread implies later versions trim zeros: https://github.com/NuGet/Home/issues/3050

**Comment by GregFinzer** [comment]
It is not just that.  It is a change of the base build logic, then manually modifying over 25 different projects with the associated installers.  Then performing a build and deploy of each.

**Comment by PhilipDaniels** [comment]
For reference, the specific message that is being generated:

```
One or more unresolved package dependency constraints detected in the existing
packages.config file. All dependency constraints must be resolved to add or update
packages. If these packages are being updated this message may be ignored, if not
the following error(s) may be blocking the current package operation:
'FluentAssertions 4.19.4', 'XYZ 1.9.18057.70 constraint: CompareNETObjects (>= 4.3.0)'
```

Here XYZ is one of my libraries that uses CompareNETObjects.

**Comment by GregFinzer** [comment]
Ok, thanks.
