### ISSUE TITLE
Comparion of objects inheriting from Dictionary fails

### ISSUE THREAD

**Issue by phlegethon** [GregFinzer/Compare-Net-Objects#88]
I created a class that inherits from Dictionary<string, string>and added a Id property.
If i compare two instances of this class with different id's they are still considered to be equal.

Ive put together a little solution that illustrates this problem: 

https://github.com/phlegethon/DictionaryCompareTest

**Comment by GregFinzer** [comment]
@phlegethon It definitely does not support custom dictionaries like what you have done.  This would be an enhancement.  Please implement the functionality and I will merge in the pull request.

**Comment by GregFinzer** [comment]
The class that you will need to modify is DictionaryComparer

**Comment by GregFinzer** [comment]
@phlegethon How is your enhancement going?  Have you almost completed the work?

**Comment by phlegethon** [comment]
Hi,

I haven't started on it!

Other projects have a much higher priority than learning your code base and
working on a fix.. you know what it's like!

**Comment by GregFinzer** [comment]
It has been six months.  No one wanted to implement this feature.  Closing.
