### ISSUE TITLE
Tagged releases in GitHub?

### ISSUE THREAD

**Issue by sugarjig** [GregFinzer/Compare-Net-Objects#90]
First of all, thanks for creating this extremely useful library. We've started using it in our application's test code, and it's been very helpful.

We like to keep our dependencies up-to-date, or at least know when we're behind. Our current method of being notified of new versions is subscribing to the GitHub releases RSS feeds. We're a macOS shop, so we don't have the luxury of Visual Studio informing us. We also have dependencies in languages other than .NET, so the RSS feeds help to centralize all the information.

Would it be possible to create a tagged release in GitHub when a new version is published to NuGet?

**Comment by GregFinzer** [comment]
Thanks for the kind words.  Sure.  It is done.

**Comment by sugarjig** [comment]
Great! Thank you!
