### ISSUE TITLE
Nested Objects - Compare Null

### ISSUE THREAD

**Issue by PascalSenn** [GregFinzer/Compare-Net-Objects#91]
Hey there

This awesome piece of software does it's job very well. 
There's just one feature missing. (As far as I know)
If a nested object property is null in first place and the gets set. The comparer doesn't track all the nested properties. 
For visualizing all the chances this is needed. 

Am I missing something? If there is no configuration option, how is this to implement?

```csharp
public class A {
     public B NestedObject {get; set;}
}
``` 
Comparing A will not track properties of B if any of the A object have a null reference on B

**Comment by GregFinzer** [comment]
@PascalSenn nope, sorry it does not have this feature.  You can certainly implement something like that.

**Comment by PascalSenn** [comment]
Thanks for the response. I'm gonna store the whole child object, I guess.
