### ISSUE TITLE
Treat empty collection and null the same option

### ISSUE THREAD

**Issue by strohhut** [GregFinzer/Compare-Net-Objects#92]
It would be nice to be able to configure this.

**Comment by GregFinzer** [comment]
@strohhut sounds good.  Please implement and I will be happy to merge in the pull request.

**Comment by strohhut** [comment]
I have to extend `CollectionComparer.IsTypeMatch` so it allows one side to be null (just like `StringComparer.IsTypeMatch`). If I do this then `CollectionComparer.Compare` now also executes when one side is null. This is problematic for `ExcludeLogic.ShouldExcludeClass` because this method expects the types of both sides. But I only get the type when the value is not null.

**Comment by GregFinzer** [comment]
Thanks for the update.  It looks like you will need to modify in other areas then.

**Comment by strohhut** [comment]
I saw that there are many classes that I would need to touch like `ByteArrayComparer`, `HashSetComparer`, etc. Unfortunately this is too complex for me to do right now.

Feel free to close this featue request.

Thank you!

**Comment by GregFinzer** [comment]
No problem.  Best of luck with your projects.
