### ISSUE TITLE
Regex in Members to Ignore

### ISSUE THREAD

**Issue by duraes** [GregFinzer/Compare-Net-Objects#93]
Would be nice to have the option to pass an Regex to select witch members to Ignore.

Today i have to set "Url"
But would like to use "Images\.(.+)\.Url"

To ignore "Images.Images[Order:3,Size:200].Url"

Witch leads me to ignore ALL "Url", with can be misleading.

**Comment by GregFinzer** [comment]
@duraes sounds good.  Please implement and I will be happy to merge in the pull request.

**Comment by GregFinzer** [comment]
It has been six months.  No one wanted to implement this feature.  Closing.
