### ISSUE TITLE
Upgrading to version 4.52 breaks references

### ISSUE THREAD

**Issue by slope-software-taylor** [GregFinzer/Compare-Net-Objects#94]
Upgrading from 4.51 to 4.52 causes the following error when attempting to call the assembly:

Could not load file or assembly 'KellermanSoftware.Compare-NET-Objects, Version=4.52.0.0, Culture=neutral, PublicKeyToken=d970ace04cc85217' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by slope-software-taylor** [comment]
FYI for anyone dealing with this:  A workaround is to put a binding redirect in your config file, like so:

`<dependentAssembly>
    <assemblyIdentity name="KellermanSoftware.Compare-NET-Objects" publicKeyToken="d970ace04cc85217" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.52.0.0" newVersion="4.51.0.0" />
      </dependentAssembly>`

**Comment by GregFinzer** [comment]
@slope-software-taylor Is it because the NuGet package is 4.5.2 but the assembly version is actually 4.5.1?  Or is it some other reason?

**Comment by slope-software-taylor** [comment]
@GregFinzer I'm not exactly sure.  My situation is I have an ASP.NET web project referencing a services project.  The services project references Compare-Net-Objects. After building, the assembly dll in the services bin folder is version 4.52.0.0, but the one in the web project is 4.51.0.0.

I've tried cleaning, rebuilding, closing and re-opening VS, and even installing the NuGet package on the web project to see if that would help it see the right version.  If I manually copy the assembly over and replace the one in the web bin folder, that works too.

It's also potentially worth noting that the ClassTypesToInclude configuration parameter does not seem to be working with collections regardless of the assembly that I reference (I know this was supposed to be fixed in 4.52.)

Thanks for the quick response!

**Comment by GregFinzer** [comment]
@slope-software-taylor That sounds like a problem with NuGet or Visual Studio.  Compare .NET Objects is just a standard NuGet package.  There is nothing special.  

Could you post a failing test for the ClassTypesToInclude problem?

Thanks,
Greg

**Comment by slope-software-taylor** [comment]
@GregFinzer The ClassTypesToInclude issue seems to only happen when IgnoreCollectionOrder is true.  Here's a unit test that fails (I added a persons list to the HoldingsReport object for illustration, as well):

```
[Test]
        public void ClassTypeIncludePositive2()
        {
            _compare.Config.IgnoreCollectionOrder = true;
            _compare.Config.ClassTypesToInclude.Add(typeof(HoldingsReport));
            _compare.Config.ClassTypesToInclude.Add(typeof(Holding));

            var holdingReport1 = new HoldingsReport
            {
                Id = 1,
                Holdings = new List<Holding>
                {
                    new Holding { Id = 1, Name = "Holding1" }
                },
                Persons = new List<Person>
                {
                    new Person { ID = 1, Name = "Person1" }
                }
            };

            var holdingReport2 = new HoldingsReport
            {
                Id = 1,
                Holdings = new List<Holding>
                {
                    new Holding { Id = 1, Name = "Holding1" }
                },
                Persons = new List<Person>
                {
                    new Person { ID = 2, Name = "Person2" }
                }
            };

            var result = _compare.Compare(holdingReport1, holdingReport2);
            Assert.IsTrue(result.AreEqual, result.DifferencesString);
        }
```

If you set IgnoreCollectionOrder to false, this test passes.

**Comment by slope-software-taylor** [comment]
@GregFinzer I put in a PR for what I believe to be the fix for the IgnoreCollectionOrder issue.

**Comment by slope-software-taylor** [comment]
The versioning issue ended up being some kind of crazy project package caching issue in VS.  I was able to resolve after some trouble.
